export type ClinicalIntakeText = Record<string, string>;

const en: ClinicalIntakeText = {
  title: "Your clinical intake, before the consultation.",
  subtitle: "Tell JeevanLink what brings you in. Speak or tap. We organize the history into a clinician-ready draft.",
  consentTitle: "Consent & control",
  consentText: "Your answers are used to prepare a clinical-history draft for clinician review. This tool does not diagnose or prescribe.",
  listenExplanation: "Listen to explanation",
  audioGuided: "Audio-guided consent",
  voiceLanguage: "Voice language",
  humanVerification: "Human verification required",
  patient: "Patient",
  preConsultation: "Pre-consultation clinical intake",
  step: "Step",
  of: "of",
  historyMode: "Choose history mode",
  general: "General",
  generalDescription: "Standard clinical history interview",
  ayush: "AYUSH / Ayurveda",
  ayushDescription: "Dashavidha + Ahara-Vihara fields",
  chiefComplaint: "What brings you in today?",
  chiefComplaintSubtitle: "Start with the patient's own words. You can refine the history next.",
  hpiTitle: "History of Present Illness",
  hpiSubtitle: "These prompts follow a controlled clinical-history structure. The patient can speak or type.",
  onset: "When did it start?",
  duration: "How long has it been present?",
  character: "How would you describe it?",
  location: "Where is it located?",
  radiation: "Does it move or spread anywhere?",
  severity: "How severe is it?",
  aggravating: "What makes it worse?",
  relieving: "What makes it better?",
  associatedSymptoms: "Any other symptoms along with it?",
  hpiHintChestPain: "For chest pain, also note whether it spreads to your arm, jaw, neck or back, and whether it comes with sweating or breathlessness.",
  hpiHintFever: "For fever, also note the pattern (continuous or coming and going) and the highest temperature you've measured, if any.",
  hpiHintCough: "For cough, also note whether it's dry or brings up phlegm, and the colour of the phlegm if any.",
  hpiHintAbdominalPain: "For abdominal pain, also note whether it's linked to eating, bowel movements, or vomiting.",
  hpiHintHeadache: "For headaches, also note whether light, noise or movement makes it worse, and whether there's any vision change.",
  pastTitle: "Past & current history",
  pastSubtitle: "List what the patient already knows. Leave fields blank when not reported.",
  pastMedical: "Past medical history",
  pastSurgical: "Past surgical history",
  medications: "Current medications",
  allergies: "Allergies",
  family: "Family history",
  occupation: "Occupation",
  diet: "Diet",
  sleep: "Sleep",
  smoking: "Smoking / tobacco",
  alcohol: "Alcohol",
  reviewTitle: "Review of systems & investigations",
  reviewSubtitle: "This is a structured capture layer, not an autonomous diagnosis.",
  ros: "Review of systems",
  investigations: "Prior investigations",
  documentsTitle: "Add prior medical documents",
  documentsDescription: "Upload a prescription, laboratory report or discharge summary. The existing AI document pipeline will extract available clinical entities for this intake.",
  analyze: "Analyze documents",
  analyzing: "Analyzing…",
  selectedSuffix: "document(s) selected.",
  aiContext: "AI-extracted context",
  safetyScreen: "Safety screen",
  safetyText: "Possible urgent symptoms will be flagged for human triage. The system will not diagnose or prescribe.",
  review: "Review history",
  reviewSubtitle2: "Review the draft before sending it into the existing clinician-verification workflow.",
  submit: "Send for clinician review",
  submitting: "Submitting…",
  submitted: "Submitted for clinician verification",
  complete: "Your intake is saved as a pending clinical record.",
  completionNote: "The existing clinician-verification workflow remains the final authority. Your intake will not become trusted longitudinal information until verified.",
  openRecords: "Open Health Records",
  backDashboard: "Back to dashboard",
  urgent: "Urgent attention flagged",
  triageNote: "This is a triage escalation signal and not a diagnosis.",
  voiceTouch: "Voice + touch",
  voiceTouchDescription: "Two ways to answer every prompt",
  speakPrompt: "You can answer by voice or typing.",
  redFlagEscalation: "Red-flag escalation",
  redFlagDescription: "Urgent symptoms can interrupt routine intake",
  redFlagBody: "JeevanLink flags configured urgent symptom patterns for human attention. It does not diagnose or prescribe.",
  verificationGate: "Verification gate",
  verificationBody: "Every intake is saved as PENDING. Clinician verification remains the source of truth before the record becomes trusted.",
  continue: "Continue",
  back: "Back",
  speak: "Speak",
  stop: "Stop",
  listening: "Listening…",
  transcribing: "Transcribing…",
  voiceUnavailable: "Voice recording is not available in this browser. You can type the answer instead.",
  voiceFailed: "Voice capture could not be completed. Please try again or type your answer.",
  transcriptionFailed: "Unable to transcribe this recording. Please try again or type the answer.",
  notReported: "Not reported",
  enterAnswer: "Enter your answer…",
  quickChestPain: "Chest pain",
  quickFever: "Fever",
  quickCough: "Cough",
  quickAbdominalPain: "Abdominal pain",
  quickHeadache: "Headache",
  quickOther: "Other",
  ayushContext: "AYUSH context",
  ayushIntro: "Capture additional Ayurvedic context without replacing clinician judgment.",
  dashavidhaNotesPlaceholder: "Additional notes (optional)",
  prakritiTitle: "Prakriti (constitution)",
  prakritiDescription: "The patient's baseline constitution, established at birth. Select the closest classical type.",
  vikritiTitle: "Vikriti (current imbalance)",
  vikritiDescription: "The current deviation from baseline constitution, if any.",
  saraTitle: "Sara (tissue quality)",
  saraDescription: "Overall quality/essence of body tissues (dhatus). Note which tissue if relevant.",
  samhananaTitle: "Samhanana (body build)",
  samhananaDescription: "Compactness and consolidation of body build.",
  pramanaTitle: "Pramana (body proportion)",
  pramanaDescription: "Proportion of body measurements relative to the ideal.",
  satmyaTitle: "Satmya (suitability)",
  satmyaDescription: "What the patient is habituated and well-adapted to, in diet, climate and lifestyle.",
  sattvaTitle: "Sattva (mental strength)",
  sattvaDescription: "Psychological strength and mental resilience.",
  aharaShaktiTitle: "Ahara Shakti (digestive capacity)",
  aharaShaktiDescription: "Capacity to take in food and capacity to digest it — assessed separately.",
  abhyavaharanaShaktiLabel: "Abhyavaharana Shakti (appetite / intake capacity)",
  jaranaShaktiLabel: "Jarana Shakti (digestive / metabolic capacity)",
  vyayamaShaktiTitle: "Vyayama Shakti (exercise capacity)",
  vyayamaShaktiDescription: "Physical stamina and tolerance for exertion.",
  vayaTitle: "Vaya (age category)",
  vayaDescription: "Classical age-band, which affects dosha strength and treatment planning.",
  vayaYearsLabel: "Exact age in years (optional)",
  aharaViharaPlaceholder: "Typical daily diet and lifestyle pattern…",
  nidanaPlaceholder: "What the patient believes triggered or caused this…",
  sampraptiPlaceholder: "Clinical reasoning on disease process — usually completed or refined by the clinician…",
  doshaVata: "Vata",
  doshaPitta: "Pitta",
  doshaKapha: "Kapha",
  doshaVataPitta: "Vata-Pitta",
  doshaPittaKapha: "Pitta-Kapha",
  doshaVataKapha: "Vata-Kapha",
  doshaSama: "Sama (Tridoshaja / balanced)",
  vikritiNoImbalance: "No significant imbalance noted",
  gradePravara: "Pravara (High)",
  gradeMadhyama: "Madhyama (Moderate)",
  gradeAvara: "Avara (Low)",
  satmyaSama: "Sama Satmya — balanced, well-adapted",
  satmyaVishama: "Vishama Satmya — irregular, poor adaptability",
  satmyaEkaRasa: "Eka Rasa Satmya — habituated to one dominant taste",
  vayaBala: "Bala — childhood (up to ~16 yrs)",
  vayaMadhyama: "Madhyama / Yuva — adult (16–70 yrs)",
  vayaVriddha: "Vriddha — elderly (70+ yrs)",
  dashavidhaReviewTitle: "Dashavidha Pariksha",
  noDocuments: "No prior documents selected.",
  microphone: "Microphone",
  consentClinicalHistory: "I consent to clinical-history capture.",
  consentDocumentProcessing: "I understand medical documents may be processed to prepare context.",
  consentClinicianSharing: "I consent to sharing this draft with the treating clinician for review.",
  a11yAudioGuided: "Audio guide",
  a11yHighContrast: "High contrast",
  a11yLargeText: "Large text",
};

const hi: ClinicalIntakeText = {
  title: "परामर्श से पहले आपकी क्लिनिकल हिस्ट्री।",
  subtitle: "JeevanLink को बताएं कि आपको आज किस समस्या के लिए सहायता चाहिए। बोलें या टैप करें।",
  consentTitle: "सहमति और नियंत्रण",
  consentText: "आपके उत्तर क्लिनिशियन समीक्षा के लिए क्लिनिकल हिस्ट्री ड्राफ्ट बनाने में उपयोग होंगे। यह टूल निदान या दवा निर्धारित नहीं करता।",
  listenExplanation: "व्याख्या सुनें",
  audioGuided: "ऑडियो-निर्देशित सहमति",
  voiceLanguage: "आवाज़ की भाषा",
  humanVerification: "मानवीय सत्यापन आवश्यक",
  patient: "मरीज़",
  preConsultation: "परामर्श-पूर्व क्लिनिकल इंटेक",
  step: "चरण",
  of: "में से",
  historyMode: "हिस्ट्री का प्रकार चुनें",
  general: "सामान्य",
  generalDescription: "मानक क्लिनिकल हिस्ट्री इंटरव्यू",
  ayush: "आयुष / आयुर्वेद",
  ayushDescription: "दशविध + आहार-विहार फ़ील्ड",
  chiefComplaint: "आज आपको किस समस्या के लिए सहायता चाहिए?",
  chiefComplaintSubtitle: "पहले मरीज़ के अपने शब्दों में बताएं। आगे हिस्ट्री को बेहतर किया जा सकता है।",
  hpiTitle: "वर्तमान बीमारी का इतिहास",
  hpiSubtitle: "ये प्रश्न नियंत्रित क्लिनिकल हिस्ट्री संरचना का पालन करते हैं। मरीज़ बोल या टाइप कर सकता है।",
  onset: "कब शुरू हुआ?",
  duration: "कितने समय से है?",
  character: "आप इसे कैसे बताएंगे?",
  location: "यह कहाँ है?",
  radiation: "क्या यह कहीं और फैलता है?",
  severity: "कितनी गंभीरता है?",
  aggravating: "इसे क्या बढ़ाता है?",
  relieving: "इसे क्या कम करता है?",
  associatedSymptoms: "इसके साथ और कोई लक्षण हैं?",
  hpiHintChestPain: "सीने में दर्द के लिए, यह भी बताएं कि क्या यह आपकी बांह, जबड़े, गर्दन या पीठ तक फैलता है, और क्या इसके साथ पसीना आना या सांस फूलना है।",
  hpiHintFever: "बुखार के लिए, यह भी बताएं कि यह लगातार है या आता-जाता रहता है, और यदि मापा हो तो सबसे अधिक तापमान क्या रहा।",
  hpiHintCough: "खांसी के लिए, यह भी बताएं कि यह सूखी है या बलगम वाली, और यदि बलगम है तो उसका रंग क्या है।",
  hpiHintAbdominalPain: "पेट दर्द के लिए, यह भी बताएं कि क्या इसका संबंध खाने, मल त्याग, या उल्टी से है।",
  hpiHintHeadache: "सिरदर्द के लिए, यह भी बताएं कि क्या रोशनी, आवाज़ या हिलने-डुलने से यह बढ़ता है, और क्या दृष्टि में कोई बदलाव है।",
  pastTitle: "पिछली और वर्तमान हिस्ट्री",
  pastSubtitle: "जो जानकारी मरीज़ को पता है वह दें। जो नहीं पता उसे खाली छोड़ सकते हैं।",
  pastMedical: "पिछली चिकित्सा हिस्ट्री",
  pastSurgical: "पिछली सर्जरी की हिस्ट्री",
  medications: "वर्तमान दवाएँ",
  allergies: "एलर्जी",
  family: "पारिवारिक हिस्ट्री",
  occupation: "पेशा",
  diet: "आहार",
  sleep: "नींद",
  smoking: "धूम्रपान / तंबाकू",
  alcohol: "शराब",
  reviewTitle: "सिस्टम रिव्यू और जांच",
  reviewSubtitle: "यह संरचित जानकारी संग्रह है, स्वचालित निदान नहीं।",
  ros: "सिस्टम रिव्यू",
  investigations: "पिछली जांच",
  documentsTitle: "पुराने मेडिकल दस्तावेज जोड़ें",
  documentsDescription: "प्रिस्क्रिप्शन, लैब रिपोर्ट या डिस्चार्ज सारांश अपलोड करें। मौजूदा AI दस्तावेज़ पाइपलाइन उपलब्ध क्लिनिकल जानकारी निकालेगी।",
  analyze: "दस्तावेज़ विश्लेषण करें",
  analyzing: "विश्लेषण हो रहा है…",
  selectedSuffix: "दस्तावेज़ चुने गए।",
  aiContext: "AI द्वारा निकाला गया संदर्भ",
  safetyScreen: "सुरक्षा जाँच",
  safetyText: "संभावित आपात लक्षण मानव ट्रायेज के लिए फ़्लैग किए जाएंगे। सिस्टम निदान या दवा नहीं देगा।",
  review: "हिस्ट्री की समीक्षा",
  reviewSubtitle2: "क्लिनिशियन सत्यापन के लिए भेजने से पहले ड्राफ्ट की समीक्षा करें।",
  submit: "क्लिनिशियन समीक्षा के लिए भेजें",
  submitting: "भेजा जा रहा है…",
  submitted: "क्लिनिशियन सत्यापन के लिए भेजा गया",
  complete: "आपकी हिस्ट्री पेंडिंग क्लिनिकल रिकॉर्ड के रूप में सेव हो गई है।",
  completionNote: "मौजूदा क्लिनिशियन-सत्यापन वर्कफ़्लो अंतिम प्राधिकरण है। सत्यापन तक आपकी हिस्ट्री trusted longitudinal जानकारी नहीं बनेगी।",
  openRecords: "हेल्थ रिकॉर्ड खोलें",
  backDashboard: "डैशबोर्ड पर वापस",
  urgent: "तुरंत ध्यान आवश्यक",
  triageNote: "यह ट्रायेज एस्केलेशन संकेत है, निदान नहीं।",
  voiceTouch: "आवाज़ + टच",
  voiceTouchDescription: "हर प्रश्न का उत्तर दो तरीकों से दें",
  speakPrompt: "आप बोलकर या टाइप करके जवाब दे सकते हैं।",
  redFlagEscalation: "रेड-फ्लैग एस्केलेशन",
  redFlagDescription: "आपात लक्षण सामान्य इंटेक रोक सकते हैं",
  redFlagBody: "JeevanLink कॉन्फ़िगर किए गए आपात लक्षणों को मानव ध्यान के लिए फ़्लैग करता है। यह निदान या दवा नहीं देता।",
  verificationGate: "सत्यापन गेट",
  verificationBody: "हर इंटेक PENDING के रूप में सेव होती है। रिकॉर्ड trusted बनने से पहले क्लिनिशियन सत्यापन अंतिम स्रोत है।",
  continue: "जारी रखें",
  back: "पीछे",
  speak: "बोलें",
  stop: "रोकें",
  listening: "सुन रहे हैं…",
  transcribing: "टेक्स्ट में बदल रहे हैं…",
  voiceUnavailable: "इस ब्राउज़र में वॉइस रिकॉर्डिंग उपलब्ध नहीं है। आप उत्तर टाइप कर सकते हैं।",
  voiceFailed: "वॉइस कैप्चर पूरा नहीं हो सका। फिर से कोशिश करें या उत्तर टाइप करें।",
  transcriptionFailed: "रिकॉर्डिंग को टेक्स्ट में बदलना संभव नहीं हुआ। फिर से कोशिश करें या टाइप करें।",
  notReported: "रिपोर्ट नहीं किया गया",
  enterAnswer: "अपना उत्तर लिखें…",
  quickChestPain: "सीने में दर्द",
  quickFever: "बुखार",
  quickCough: "खाँसी",
  quickAbdominalPain: "पेट दर्द",
  quickHeadache: "सिरदर्द",
  quickOther: "अन्य",
  ayushContext: "आयुष संदर्भ",
  ayushIntro: "क्लिनिशियन के निर्णय को बदले बिना अतिरिक्त आयुर्वेदिक संदर्भ दर्ज करें।",
  dashavidhaNotesPlaceholder: "अतिरिक्त टिप्पणी (वैकल्पिक)",
  prakritiTitle: "प्रकृति (शारीरिक संरचना)",
  prakritiDescription: "जन्म से निर्धारित मूल शारीरिक संरचना। निकटतम शास्त्रीय प्रकार चुनें।",
  vikritiTitle: "विकृति (वर्तमान असंतुलन)",
  vikritiDescription: "मूल प्रकृति से वर्तमान विचलन, यदि कोई हो।",
  saraTitle: "सार (धातु गुणवत्ता)",
  saraDescription: "शरीर के धातुओं (ऊतकों) की समग्र गुणवत्ता। प्रासंगिक होने पर बताएं कौन सा धातु।",
  samhananaTitle: "संहनन (शारीरिक गठन)",
  samhananaDescription: "शरीर की सुदृढ़ता और सुसंहतता।",
  pramanaTitle: "प्रमाण (शारीरिक अनुपात)",
  pramanaDescription: "आदर्श की तुलना में शरीर के माप का अनुपात।",
  satmyaTitle: "सात्म्य (अनुकूलता)",
  satmyaDescription: "आहार, जलवायु और जीवनशैली में रोगी किस चीज़ का आदी और अनुकूल है।",
  sattvaTitle: "सत्व (मानसिक बल)",
  sattvaDescription: "मानसिक शक्ति और सहनशीलता।",
  aharaShaktiTitle: "आहार शक्ति (पाचन क्षमता)",
  aharaShaktiDescription: "भोजन ग्रहण करने की क्षमता और उसे पचाने की क्षमता — अलग-अलग आंकी जाती है।",
  abhyavaharanaShaktiLabel: "अभ्यवहरण शक्ति (भूख / ग्रहण क्षमता)",
  jaranaShaktiLabel: "जरण शक्ति (पाचन / चयापचय क्षमता)",
  vyayamaShaktiTitle: "व्यायाम शक्ति (व्यायाम क्षमता)",
  vyayamaShaktiDescription: "शारीरिक सहनशक्ति और परिश्रम सहन करने की क्षमता।",
  vayaTitle: "वय (आयु वर्ग)",
  vayaDescription: "शास्त्रीय आयु-वर्ग, जो दोष बल और उपचार योजना को प्रभावित करता है।",
  vayaYearsLabel: "सटीक आयु (वर्षों में) (वैकल्पिक)",
  aharaViharaPlaceholder: "सामान्य दैनिक आहार और जीवनशैली का पैटर्न…",
  nidanaPlaceholder: "रोगी के अनुसार इस समस्या का कारण या ट्रिगर…",
  sampraptiPlaceholder: "रोग-प्रक्रिया पर नैदानिक विश्लेषण — आमतौर पर क्लिनिशियन द्वारा पूर्ण/परिष्कृत किया जाता है…",
  doshaVata: "वात",
  doshaPitta: "पित्त",
  doshaKapha: "कफ",
  doshaVataPitta: "वात-पित्त",
  doshaPittaKapha: "पित्त-कफ",
  doshaVataKapha: "वात-कफ",
  doshaSama: "सम (त्रिदोषज / संतुलित)",
  vikritiNoImbalance: "कोई उल्लेखनीय असंतुलन नहीं",
  gradePravara: "प्रवर (उच्च)",
  gradeMadhyama: "मध्यम",
  gradeAvara: "अवर (कम)",
  satmyaSama: "सम सात्म्य — संतुलित, अच्छी तरह अनुकूलित",
  satmyaVishama: "विषम सात्म्य — अनियमित, कम अनुकूलनशीलता",
  satmyaEkaRasa: "एकरस सात्म्य — एक प्रमुख रस का आदी",
  vayaBala: "बाल — बचपन (लगभग 16 वर्ष तक)",
  vayaMadhyama: "मध्यम / युवा — वयस्क (16–70 वर्ष)",
  vayaVriddha: "वृद्ध — वृद्धावस्था (70+ वर्ष)",
  dashavidhaReviewTitle: "दशविध परीक्षा",
  noDocuments: "कोई पुराना दस्तावेज़ चयनित नहीं है।",
  microphone: "माइक्रोफ़ोन",
  consentClinicalHistory: "मैं क्लिनिकल हिस्ट्री कैप्चर के लिए सहमत हूँ।",
  consentDocumentProcessing: "मैं समझता/समझती हूँ कि संदर्भ तैयार करने के लिए मेडिकल दस्तावेज़ प्रोसेस किए जा सकते हैं।",
  consentClinicianSharing: "मैं इस ड्राफ्ट को उपचार कर रहे क्लिनिशियन के साथ समीक्षा के लिए साझा करने के लिए सहमत हूँ।",
  a11yAudioGuided: "ऑडियो गाइड",
  a11yHighContrast: "उच्च कंट्रास्ट",
  a11yLargeText: "बड़ा टेक्स्ट",
};

const bn: ClinicalIntakeText = {
  title: "পরামর্শের আগে আপনার ক্লিনিকাল ইতিহাস।",
  subtitle: "JeevanLink-কে বলুন আজ কী কারণে এসেছেন। কথা বলুন বা ট্যাপ করুন।",
  consentTitle: "সম্মতি ও নিয়ন্ত্রণ",
  consentText: "আপনার উত্তর ক্লিনিশিয়ান পর্যালোচনার জন্য ক্লিনিকাল ইতিহাসের খসড়া তৈরি করতে ব্যবহার হবে। এই টুল রোগ নির্ণয় বা ওষুধ নির্ধারণ করে না।",
  listenExplanation: "ব্যাখ্যা শুনুন",
  audioGuided: "অডিও-নির্দেশিত সম্মতি",
  voiceLanguage: "ভয়েসের ভাষা",
  humanVerification: "মানব যাচাই প্রয়োজন",
  patient: "রোগী",
  preConsultation: "পরামর্শ-পূর্ব ক্লিনিকাল ইনটেক",
  step: "ধাপ",
  of: "এর",
  historyMode: "ইতিহাসের ধরন বেছে নিন",
  general: "সাধারণ",
  generalDescription: "মানক ক্লিনিকাল ইতিহাস ইন্টারভিউ",
  ayush: "আয়ুষ / আয়ুর্বেদ",
  ayushDescription: "দশবিধ + আহার-বিহার ফিল্ড",
  chiefComplaint: "আজ কী সমস্যা নিয়ে এসেছেন?",
  chiefComplaintSubtitle: "প্রথমে রোগীর নিজের ভাষায় বলুন। পরের ধাপে ইতিহাস আরও নির্দিষ্ট করা যাবে।",
  hpiTitle: "বর্তমান অসুস্থতার ইতিহাস",
  hpiSubtitle: "প্রশ্নগুলো একটি নিয়ন্ত্রিত ক্লিনিকাল ইতিহাস কাঠামো অনুসরণ করে। কথা বা টাইপ করা যায়।",
  onset: "কখন শুরু হয়েছে?",
  duration: "কতদিন ধরে আছে?",
  character: "কীভাবে বর্ণনা করবেন?",
  location: "কোথায় রয়েছে?",
  radiation: "কোথাও ছড়ায় কি?",
  severity: "কতটা তীব্র?",
  aggravating: "কী করলে বাড়ে?",
  relieving: "কী করলে কমে?",
  associatedSymptoms: "এর সঙ্গে অন্য কোনো উপসর্গ আছে?",
  hpiHintChestPain: "বুকে ব্যথার ক্ষেত্রে, এটাও উল্লেখ করুন যে এটি হাত, চোয়াল, ঘাড় বা পিঠে ছড়িয়ে পড়ে কিনা, এবং এর সাথে ঘাম বা শ্বাসকষ্ট আছে কিনা।",
  hpiHintFever: "জ্বরের ক্ষেত্রে, এটাও উল্লেখ করুন যে এটি ক্রমাগত না মাঝে মাঝে আসে, এবং পরিমাপ করা থাকলে সর্বোচ্চ তাপমাত্রা কত ছিল।",
  hpiHintCough: "কাশির ক্ষেত্রে, এটাও উল্লেখ করুন যে এটি শুকনো নাকি কফযুক্ত, এবং কফ থাকলে তার রং কী।",
  hpiHintAbdominalPain: "পেটে ব্যথার ক্ষেত্রে, এটাও উল্লেখ করুন যে এটি খাওয়া, মলত্যাগ, বা বমির সাথে সম্পর্কিত কিনা।",
  hpiHintHeadache: "মাথাব্যথার ক্ষেত্রে, এটাও উল্লেখ করুন যে আলো, শব্দ বা নড়াচড়ায় এটি বাড়ে কিনা, এবং দৃষ্টিতে কোনো পরিবর্তন আছে কিনা।",
  pastTitle: "আগের ও বর্তমান ইতিহাস",
  pastSubtitle: "রোগী যা জানেন তা লিখুন। না জানা থাকলে ফাঁকা রাখতে পারেন।",
  pastMedical: "আগের রোগের ইতিহাস",
  pastSurgical: "আগের অস্ত্রোপচারের ইতিহাস",
  medications: "বর্তমান ওষুধ",
  allergies: "অ্যালার্জি",
  family: "পারিবারিক ইতিহাস",
  occupation: "পেশা",
  diet: "খাদ্যাভ্যাস",
  sleep: "ঘুম",
  smoking: "ধূমপান / তামাক",
  alcohol: "অ্যালকোহল",
  reviewTitle: "সিস্টেম রিভিউ ও পরীক্ষা",
  reviewSubtitle: "এটি কাঠামোবদ্ধ তথ্য সংগ্রহ; স্বয়ংক্রিয় রোগ নির্ণয় নয়।",
  ros: "সিস্টেম রিভিউ",
  investigations: "আগের পরীক্ষা",
  documentsTitle: "আগের মেডিকেল নথি যোগ করুন",
  documentsDescription: "প্রেসক্রিপশন, ল্যাব রিপোর্ট বা ডিসচার্জ সারাংশ আপলোড করুন। বিদ্যমান AI ডকুমেন্ট পাইপলাইন উপলব্ধ ক্লিনিকাল তথ্য বের করবে।",
  analyze: "ডকুমেন্ট বিশ্লেষণ করুন",
  analyzing: "বিশ্লেষণ হচ্ছে…",
  selectedSuffix: "টি ডকুমেন্ট নির্বাচিত হয়েছে।",
  aiContext: "AI থেকে পাওয়া তথ্য",
  safetyScreen: "নিরাপত্তা পরীক্ষা",
  safetyText: "সম্ভাব্য জরুরি উপসর্গ মানব ট্রায়াজের জন্য চিহ্নিত হবে। সিস্টেম রোগ নির্ণয় বা ওষুধ দেবে না।",
  review: "ইতিহাস পর্যালোচনা",
  reviewSubtitle2: "ক্লিনিশিয়ান যাচাইয়ের জন্য পাঠানোর আগে ড্রাফট পর্যালোচনা করুন।",
  submit: "ক্লিনিশিয়ান পর্যালোচনার জন্য পাঠান",
  submitting: "পাঠানো হচ্ছে…",
  submitted: "ক্লিনিশিয়ান যাচাইয়ের জন্য পাঠানো হয়েছে",
  complete: "আপনার ইতিহাস পেন্ডিং ক্লিনিকাল রেকর্ড হিসেবে সেভ হয়েছে।",
  completionNote: "মৌজুদ ক্লিনিশিয়ান-যাচাই প্রক্রিয়াই চূড়ান্ত কর্তৃপক্ষ। যাচাই না হওয়া পর্যন্ত এটি trusted longitudinal তথ্য হবে না।",
  openRecords: "হেলথ রেকর্ড খুলুন",
  backDashboard: "ড্যাশবোর্ডে ফিরে যান",
  urgent: "জরুরি মনোযোগ প্রয়োজন",
  triageNote: "এটি ট্রায়াজ এস্কেলেশন সংকেত, রোগ নির্ণয় নয়।",
  voiceTouch: "ভয়েস + টাচ",
  voiceTouchDescription: "প্রতিটি প্রশ্নের উত্তর দেওয়ার দুটি উপায়",
  speakPrompt: "আপনি কথা বলে বা টাইপ করে উত্তর দিতে পারেন।",
  redFlagEscalation: "রেড-ফ্ল্যাগ এস্কেলেশন",
  redFlagDescription: "জরুরি উপসর্গ স্বাভাবিক ইনটেক থামাতে পারে",
  redFlagBody: "JeevanLink কনফিগার করা জরুরি উপসর্গ মানব মনোযোগের জন্য চিহ্নিত করে। এটি রোগ নির্ণয় বা ওষুধ দেয় না।",
  verificationGate: "যাচাই গেট",
  verificationBody: "প্রতিটি ইনটেক PENDING হিসেবে সেভ হয়। রেকর্ড trusted হওয়ার আগে ক্লিনিশিয়ান যাচাইই চূড়ান্ত উৎস।",
  continue: "চালিয়ে যান",
  back: "পিছনে",
  speak: "বলুন",
  stop: "থামুন",
  listening: "শুনছি…",
  transcribing: "টেক্সটে বদলানো হচ্ছে…",
  voiceUnavailable: "এই ব্রাউজারে ভয়েস রেকর্ডিং পাওয়া যাচ্ছে না। আপনি উত্তর টাইপ করতে পারেন।",
  voiceFailed: "ভয়েস ক্যাপচার সম্পূর্ণ হয়নি। আবার চেষ্টা করুন বা উত্তর টাইপ করুন।",
  transcriptionFailed: "রেকর্ডিংকে টেক্সটে রূপান্তর করা যায়নি। আবার চেষ্টা করুন বা টাইপ করুন।",
  notReported: "জানানো হয়নি",
  enterAnswer: "আপনার উত্তর লিখুন…",
  quickChestPain: "বুকে ব্যথা",
  quickFever: "জ্বর",
  quickCough: "কাশি",
  quickAbdominalPain: "পেটে ব্যথা",
  quickHeadache: "মাথাব্যথা",
  quickOther: "অন্যান্য",
  ayushContext: "আয়ুষ প্রসঙ্গ",
  ayushIntro: "ক্লিনিশিয়ানের সিদ্ধান্তের বিকল্প না হয়ে অতিরিক্ত আয়ুর্বেদিক তথ্য দিন।",
  dashavidhaNotesPlaceholder: "অতিরিক্ত মন্তব্য (ঐচ্ছিক)",
  prakritiTitle: "প্রকৃতি (দৈহিক গঠন)",
  prakritiDescription: "জন্ম থেকে নির্ধারিত মূল দৈহিক গঠন। নিকটতম শাস্ত্রীয় ধরন নির্বাচন করুন।",
  vikritiTitle: "বিকৃতি (বর্তমান ভারসাম্যহীনতা)",
  vikritiDescription: "মূল প্রকৃতি থেকে বর্তমান বিচ্যুতি, যদি থাকে।",
  saraTitle: "সার (ধাতু গুণমান)",
  saraDescription: "শরীরের ধাতুর (কলার) সামগ্রিক গুণমান। প্রাসঙ্গিক হলে কোন ধাতু উল্লেখ করুন।",
  samhananaTitle: "সংহনন (দৈহিক গঠনশৈলী)",
  samhananaDescription: "শরীরের দৃঢ়তা ও সংহতি।",
  pramanaTitle: "প্রমাণ (দৈহিক অনুপাত)",
  pramanaDescription: "আদর্শের তুলনায় দেহের পরিমাপের অনুপাত।",
  satmyaTitle: "সাত্ম্য (উপযোগিতা)",
  satmyaDescription: "খাদ্য, জলবায়ু ও জীবনযাত্রায় রোগী কীসে অভ্যস্ত ও মানানসই।",
  sattvaTitle: "সত্ত্ব (মানসিক শক্তি)",
  sattvaDescription: "মানসিক দৃঢ়তা ও সহনশীলতা।",
  aharaShaktiTitle: "আহার শক্তি (হজম ক্ষমতা)",
  aharaShaktiDescription: "খাদ্য গ্রহণের ক্ষমতা এবং তা হজম করার ক্ষমতা — আলাদাভাবে মূল্যায়ন করা হয়।",
  abhyavaharanaShaktiLabel: "অভ্যবহরণ শক্তি (ক্ষুধা / গ্রহণ ক্ষমতা)",
  jaranaShaktiLabel: "জরণ শক্তি (পাচক / বিপাক ক্ষমতা)",
  vyayamaShaktiTitle: "ব্যায়াম শক্তি (ব্যায়াম ক্ষমতা)",
  vyayamaShaktiDescription: "শারীরিক সহনশক্তি ও পরিশ্রম সহ্য করার ক্ষমতা।",
  vayaTitle: "বয় (বয়সের শ্রেণি)",
  vayaDescription: "শাস্ত্রীয় বয়স-শ্রেণি, যা দোষের শক্তি ও চিকিৎসা পরিকল্পনাকে প্রভাবিত করে।",
  vayaYearsLabel: "সঠিক বয়স (বছরে) (ঐচ্ছিক)",
  aharaViharaPlaceholder: "স্বাভাবিক দৈনন্দিন খাদ্য ও জীবনযাত্রার ধরন…",
  nidanaPlaceholder: "রোগীর মতে এই সমস্যার কারণ বা ট্রিগার…",
  sampraptiPlaceholder: "রোগ-প্রক্রিয়ার ক্লিনিক্যাল বিশ্লেষণ — সাধারণত ক্লিনিশিয়ান দ্বারা সম্পূর্ণ/পরিমার্জিত হয়…",
  doshaVata: "বাত",
  doshaPitta: "পিত্ত",
  doshaKapha: "কফ",
  doshaVataPitta: "বাত-পিত্ত",
  doshaPittaKapha: "পিত্ত-কফ",
  doshaVataKapha: "বাত-কফ",
  doshaSama: "সম (ত্রিদোষজ / ভারসাম্যপূর্ণ)",
  vikritiNoImbalance: "উল্লেখযোগ্য কোনো ভারসাম্যহীনতা নেই",
  gradePravara: "প্রবর (উচ্চ)",
  gradeMadhyama: "মধ্যম",
  gradeAvara: "অবর (নিম্ন)",
  satmyaSama: "সম সাত্ম্য — সুষম, ভালোভাবে খাপ খাওয়ানো",
  satmyaVishama: "বিষম সাত্ম্য — অনিয়মিত, কম অভিযোজনযোগ্যতা",
  satmyaEkaRasa: "একরস সাত্ম্য — একটি প্রধান রসে অভ্যস্ত",
  vayaBala: "বাল — শৈশব (আনুমানিক ১৬ বছর পর্যন্ত)",
  vayaMadhyama: "মধ্যম / যুব — প্রাপ্তবয়স্ক (১৬–৭০ বছর)",
  vayaVriddha: "বৃদ্ধ — বার্ধক্য (৭০+ বছর)",
  dashavidhaReviewTitle: "দশবিধ পরীক্ষা",
  noDocuments: "কোনও পুরনো নথি নির্বাচিত হয়নি।",
  microphone: "মাইক্রোফোন",
  consentClinicalHistory: "আমি ক্লিনিকাল ইতিহাস সংগ্রহে সম্মতি দিচ্ছি।",
  consentDocumentProcessing: "আমি বুঝি যে প্রসঙ্গ তৈরির জন্য মেডিকেল নথি প্রক্রিয়াকরণ করা হতে পারে।",
  consentClinicianSharing: "আমি এই খসড়াটি চিকিৎসাকারী ক্লিনিশিয়ানের সঙ্গে পর্যালোচনার জন্য শেয়ার করতে সম্মতি দিচ্ছি।",
  a11yAudioGuided: "অডিও গাইড",
  a11yHighContrast: "উচ্চ কনট্রাস্ট",
  a11yLargeText: "বড় লেখা",
};

const ta: ClinicalIntakeText = {
  title: "ஆலோசனைக்கு முன் உங்கள் மருத்துவ வரலாறு.",
  subtitle: "இன்று உங்களை இங்கே கொண்டு வந்த காரணத்தை JeevanLink-க்கு சொல்லுங்கள். பேசுங்கள் அல்லது தட்டுங்கள்.",
  consentTitle: "ஒப்புதல் மற்றும் கட்டுப்பாடு",
  consentText: "உங்கள் பதில்கள் மருத்துவர் பரிசீலனைக்கான மருத்துவ வரலாறு வரைவை உருவாக்க பயன்படுத்தப்படும். இந்த கருவி நோயறிதல் அல்லது மருந்து பரிந்துரை செய்யாது.",
  listenExplanation: "விளக்கத்தை கேளுங்கள்",
  audioGuided: "ஆடியோ வழிகாட்டிய ஒப்புதல்",
  voiceLanguage: "குரல் மொழி",
  humanVerification: "மனித சரிபார்ப்பு அவசியம்",
  patient: "நோயாளர்",
  preConsultation: "ஆலோசனைக்கு முன் கிளினிக்கல் இன்டேக்",
  step: "படி",
  of: "இல்",
  historyMode: "வரலாறு வகையைத் தேர்வு செய்யுங்கள்",
  general: "பொது",
  generalDescription: "நிலையான மருத்துவ வரலாறு நேர்காணல்",
  ayush: "ஆயுஷ் / ஆயுர்வேதம்",
  ayushDescription: "தசவித + ஆகார-விஹார விவரங்கள்",
  chiefComplaint: "இன்று உங்களை இங்கே கொண்டு வந்த பிரச்சனை என்ன?",
  chiefComplaintSubtitle: "முதலில் நோயாளியின் சொந்த வார்த்தைகளில் சொல்லுங்கள். அடுத்த படியில் வரலாற்றை விரிவுபடுத்தலாம்.",
  hpiTitle: "தற்போதைய நோயின் வரலாறு",
  hpiSubtitle: "இந்த கேள்விகள் கட்டுப்படுத்தப்பட்ட மருத்துவ வரலாறு அமைப்பைப் பின்பற்றுகின்றன. பேசவும் தட்டச்சு செய்யவும் முடியும்.",
  onset: "எப்போது தொடங்கியது?",
  duration: "எவ்வளவு காலமாக உள்ளது?",
  character: "அதை எப்படி விவரிப்பீர்கள்?",
  location: "எங்கு உள்ளது?",
  radiation: "வேறு இடத்திற்குப் பரவுகிறதா?",
  severity: "எவ்வளவு தீவிரம்?",
  aggravating: "எது மோசமாக்குகிறது?",
  relieving: "எது குறைக்கிறது?",
  associatedSymptoms: "இதனுடன் வேறு அறிகுறிகள் உள்ளனவா?",
  hpiHintChestPain: "மார்பு வலிக்கு, அது உங்கள் கை, தாடை, கழுத்து அல்லது முதுகுக்குப் பரவுகிறதா, மற்றும் வியர்வை அல்லது மூச்சுத் திணறலுடன் வருகிறதா என்பதையும் குறிப்பிடவும்.",
  hpiHintFever: "காய்ச்சலுக்கு, அது தொடர்ச்சியாகவா அல்லது வந்து போகிறதா என்பதையும், அளவிட்டிருந்தால் அதிகபட்ச வெப்பநிலை என்ன என்பதையும் குறிப்பிடவும்.",
  hpiHintCough: "இருமலுக்கு, அது வறண்டதா அல்லது கபத்துடன் வருகிறதா, கபம் இருந்தால் அதன் நிறம் என்ன என்பதையும் குறிப்பிடவும்.",
  hpiHintAbdominalPain: "வயிற்று வலிக்கு, அது சாப்பிடுவது, மலம் கழிப்பது, அல்லது வாந்தியுடன் தொடர்புடையதா என்பதையும் குறிப்பிடவும்.",
  hpiHintHeadache: "தலைவலிக்கு, ஒளி, சத்தம் அல்லது அசைவால் அது மோசமாகிறதா, மற்றும் பார்வையில் ஏதேனும் மாற்றம் உள்ளதா என்பதையும் குறிப்பிடவும்.",
  pastTitle: "முந்தைய மற்றும் தற்போதைய வரலாறு",
  pastSubtitle: "நோயாளிக்கு தெரிந்த தகவலை பதிவு செய்யுங்கள். தெரியாவிட்டால் காலியாக விடுங்கள்.",
  pastMedical: "முந்தைய மருத்துவ வரலாறு",
  pastSurgical: "முந்தைய அறுவை சிகிச்சை வரலாறு",
  medications: "தற்போதைய மருந்துகள்",
  allergies: "ஒவ்வாமைகள்",
  family: "குடும்ப வரலாறு",
  occupation: "தொழில்",
  diet: "உணவுமுறை",
  sleep: "தூக்கம்",
  smoking: "புகை / புகையிலை",
  alcohol: "மதுபானம்",
  reviewTitle: "உடல் அமைப்பு மதிப்பாய்வு மற்றும் பரிசோதனைகள்",
  reviewSubtitle: "இது கட்டமைக்கப்பட்ட தகவல் சேகரிப்பு; தானியங்கி நோயறிதல் அல்ல.",
  ros: "உடல் அமைப்பு மதிப்பாய்வு",
  investigations: "முந்தைய பரிசோதனைகள்",
  documentsTitle: "முந்தைய மருத்துவ ஆவணங்களைச் சேர்க்கவும்",
  documentsDescription: "மருந்து சீட்டு, ஆய்வக அறிக்கை அல்லது டிஸ்சார்ஜ் சுருக்கத்தை பதிவேற்றுங்கள். தற்போதைய AI ஆவண அமைப்பு கிடைக்கும் மருத்துவ தகவல்களைப் பிரித்தெடுக்கும்.",
  analyze: "ஆவணங்களை பகுப்பாய்வு செய்யவும்",
  analyzing: "பகுப்பாய்வு நடைபெறுகிறது…",
  selectedSuffix: "ஆவணம் தேர்ந்தெடுக்கப்பட்டது.",
  aiContext: "AI மூலம் பெறப்பட்ட தகவல்",
  safetyScreen: "பாதுகாப்பு சரிபார்ப்பு",
  safetyText: "சாத்தியமான அவசர அறிகுறிகள் மனித ட்ரயாஜ் கவனத்திற்கு குறியிடப்படும். அமைப்பு நோயறிதல் அல்லது மருந்து பரிந்துரை செய்யாது.",
  review: "வரலாற்றை மதிப்பாய்வு செய்யவும்",
  reviewSubtitle2: "மருத்துவர் சரிபார்ப்புக்கு அனுப்புவதற்கு முன் வரைவைப் பாருங்கள்.",
  submit: "மருத்துவர் மதிப்பாய்வுக்கு அனுப்பவும்",
  submitting: "அனுப்பப்படுகிறது…",
  submitted: "மருத்துவர் சரிபார்ப்புக்கு அனுப்பப்பட்டது",
  complete: "உங்கள் தகவல் pending clinical record ஆக சேமிக்கப்பட்டது.",
  completionNote: "தற்போதைய மருத்துவர் சரிபார்ப்பு செயல்முறையே இறுதி அதிகாரம். சரிபார்ப்பு முடியும் வரை இது நம்பகமான நீண்டகால பதிவாகாது.",
  openRecords: "சுகாதார பதிவுகளைத் திறக்கவும்",
  backDashboard: "டாஷ்போர்டுக்கு திரும்பவும்",
  urgent: "அவசர கவனம் குறியிடப்பட்டது",
  triageNote: "இது ட்ரயாஜ் எஸ்கலேஷன் சிக்னல்; நோயறிதல் அல்ல.",
  voiceTouch: "குரல் + தொடுதல்",
  voiceTouchDescription: "ஒவ்வொரு கேள்விக்கும் பதிலளிக்க இரண்டு வழிகள்",
  speakPrompt: "குரலில் அல்லது தட்டச்சு செய்து பதிலளிக்கலாம்.",
  redFlagEscalation: "ரெட்-ஃப்ளாக் எஸ்கலேஷன்",
  redFlagDescription: "அவசர அறிகுறிகள் வழக்கமான இன்டேக்கை நிறுத்தலாம்",
  redFlagBody: "JeevanLink உள்ளமைக்கப்பட்ட அவசர அறிகுறிகளை மனித கவனத்திற்காக குறியிடுகிறது. இது நோயறிதல் அல்லது மருந்து வழங்காது.",
  verificationGate: "சரிபார்ப்பு வாயில்",
  verificationBody: "ஒவ்வொரு இன்டேக்கும் PENDING ஆக சேமிக்கப்படும். பதிவு நம்பகமானதாக மாறுவதற்கு முன் மருத்துவர் சரிபார்ப்பு இறுதி ஆதாரமாகும்.",
  continue: "தொடரவும்",
  back: "பின்செல்",
  speak: "பேசுங்கள்",
  stop: "நிறுத்துங்கள்",
  listening: "கேட்கிறேன்…",
  transcribing: "உரையாக மாற்றப்படுகிறது…",
  voiceUnavailable: "இந்த உலாவியில் குரல் பதிவு கிடைக்கவில்லை. பதிலை தட்டச்சு செய்யலாம்.",
  voiceFailed: "குரல் பதிவு முடிக்கப்படவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது தட்டச்சு செய்யவும்.",
  transcriptionFailed: "இந்த பதிவை உரையாக மாற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது தட்டச்சு செய்யவும்.",
  notReported: "தெரிவிக்கப்படவில்லை",
  enterAnswer: "உங்கள் பதிலை உள்ளிடுங்கள்…",
  quickChestPain: "மார்பு வலி",
  quickFever: "காய்ச்சல்",
  quickCough: "இருமல்",
  quickAbdominalPain: "வயிற்று வலி",
  quickHeadache: "தலைவலி",
  quickOther: "மற்றவை",
  ayushContext: "ஆயுஷ் தகவல்",
  ayushIntro: "மருத்துவர் முடிவை மாற்றாமல் கூடுதல் ஆயுர்வேத தகவலை பதிவு செய்யுங்கள்.",
  dashavidhaNotesPlaceholder: "கூடுதல் குறிப்புகள் (விருப்பம்)",
  prakritiTitle: "பிரக்ருதி (உடல் இயல்பு)",
  prakritiDescription: "பிறப்பிலிருந்தே நிர்ணயிக்கப்பட்ட அடிப்படை உடல் இயல்பு. நெருக்கமான பாரம்பரிய வகையைத் தேர்ந்தெடுக்கவும்.",
  vikritiTitle: "விக்ருதி (தற்போதைய சமநிலைக் குறைவு)",
  vikritiDescription: "அடிப்படை பிரக்ருதியிலிருந்து தற்போதைய விலகல், இருந்தால்.",
  saraTitle: "சார (திசு தரம்)",
  saraDescription: "உடல் தாதுக்களின் (திசுக்களின்) மொத்த தரம். பொருந்தினால் எந்த தாது எனக் குறிப்பிடவும்.",
  samhananaTitle: "சம்ஹனன (உடல் அமைப்பு)",
  samhananaDescription: "உடலின் திடத்தன்மை மற்றும் ஒருங்கிணைப்பு.",
  pramanaTitle: "பிரமாண (உடல் விகிதம்)",
  pramanaDescription: "இலட்சிய அளவுடன் ஒப்பிடும்போது உடல் அளவீடுகளின் விகிதம்.",
  satmyaTitle: "சாத்ம்ய (பொருத்தப்பாடு)",
  satmyaDescription: "உணவு, தட்பவெப்பம் மற்றும் வாழ்க்கை முறையில் நோயாளி எதற்குப் பழக்கப்பட்டு ஏற்புடையவராக உள்ளார்.",
  sattvaTitle: "சத்வ (மன வலிமை)",
  sattvaDescription: "மனவலிமையும் தாங்கும் திறனும்.",
  aharaShaktiTitle: "ஆஹார சக்தி (செரிமான திறன்)",
  aharaShaktiDescription: "உணவை உட்கொள்ளும் திறனும் அதை செரிக்கும் திறனும் — தனித்தனியாக மதிப்பிடப்படும்.",
  abhyavaharanaShaktiLabel: "அப்யவஹரண சக்தி (பசி / உட்கொள்ளும் திறன்)",
  jaranaShaktiLabel: "ஜரண சக்தி (செரிமான / வளர்சிதை திறன்)",
  vyayamaShaktiTitle: "வ்யாயாம சக்தி (உடற்பயிற்சி திறன்)",
  vyayamaShaktiDescription: "உடல் சகிப்புத்தன்மையும் உழைப்பைத் தாங்கும் திறனும்.",
  vayaTitle: "வய (வயது வகை)",
  vayaDescription: "தோஷ வலிமை மற்றும் சிகிச்சை திட்டமிடலை பாதிக்கும் பாரம்பரிய வயது-வகை.",
  vayaYearsLabel: "சரியான வயது (ஆண்டுகளில்) (விருப்பம்)",
  aharaViharaPlaceholder: "வழக்கமான தினசரி உணவு மற்றும் வாழ்க்கை முறை…",
  nidanaPlaceholder: "இந்த பிரச்சினையை ஏற்படுத்தியதாக நோயாளி நம்புவது…",
  sampraptiPlaceholder: "நோய் செயல்முறை பற்றிய மருத்துவ பகுப்பாய்வு — பொதுவாக மருத்துவரால் நிறைவு/மேம்படுத்தப்படும்…",
  doshaVata: "வாதம்",
  doshaPitta: "பித்தம்",
  doshaKapha: "கபம்",
  doshaVataPitta: "வாத-பித்தம்",
  doshaPittaKapha: "பித்த-கபம்",
  doshaVataKapha: "வாத-கபம்",
  doshaSama: "சம (த்ரிதோஷஜ / சமநிலை)",
  vikritiNoImbalance: "குறிப்பிடத்தக்க சமநிலைக் குறைவு இல்லை",
  gradePravara: "பிரவர (உயர்)",
  gradeMadhyama: "மத்யம (நடுத்தரம்)",
  gradeAvara: "அவர (குறைவு)",
  satmyaSama: "சம சாத்ம்ய — சமநிலை, நன்கு பொருந்தியது",
  satmyaVishama: "விஷம சாத்ம்ய — ஒழுங்கற்ற, குறைந்த தகவமைப்பு",
  satmyaEkaRasa: "ஏகரச சாத்ம்ய — ஒரு முதன்மை சுவைக்குப் பழக்கப்பட்டது",
  vayaBala: "பால — குழந்தைப் பருவம் (சுமார் 16 வயது வரை)",
  vayaMadhyama: "மத்யம / யுவ — வயது வந்தோர் (16–70 வயது)",
  vayaVriddha: "வ்ருத்த — முதுமை (70+ வயது)",
  dashavidhaReviewTitle: "தசவித பரீக்ஷா",
  noDocuments: "முந்தைய ஆவணங்கள் தேர்ந்தெடுக்கப்படவில்லை.",
  microphone: "மைக்ரோஃபோன்",
  consentClinicalHistory: "மருத்துவ வரலாறு சேகரிப்புக்கு நான் ஒப்புக்கொள்கிறேன்.",
  consentDocumentProcessing: "சூழல் தயாரிக்க மருத்துவ ஆவணங்கள் செயலாக்கப்படலாம் என்பதை நான் புரிந்துகொள்கிறேன்.",
  consentClinicianSharing: "இந்த வரைவை சிகிச்சை அளிக்கும் மருத்துவருடன் மதிப்பாய்வுக்காக பகிர ஒப்புக்கொள்கிறேன்.",
  a11yAudioGuided: "ஆடியோ வழிகாட்டி",
  a11yHighContrast: "அதிக மாறுபாடு",
  a11yLargeText: "பெரிய எழுத்து",
};

const te: ClinicalIntakeText = {
  title: "సంప్రదింపుకు ముందు మీ క్లినికల్ హిస్టరీ.",
  subtitle: "ఈరోజు మిమ్మల్ని ఇక్కడికి తీసుకువచ్చిన కారణాన్ని JeevanLinkకు చెప్పండి. మాట్లాడండి లేదా ట్యాప్ చేయండి.",
  consentTitle: "సమ్మతి & నియంత్రణ",
  consentText: "మీ సమాధానాలు క్లినిషియన్ సమీక్ష కోసం క్లినికల్ హిస్టరీ డ్రాఫ్ట్ తయారు చేయడానికి ఉపయోగిస్తాం. ఈ సాధనం నిర్ధారణ లేదా మందుల సూచన చేయదు.",
  listenExplanation: "వివరణను వినండి",
  audioGuided: "ఆడియో మార్గదర్శక సమ్మతి",
  voiceLanguage: "వాయిస్ భాష",
  humanVerification: "మానవ ధృవీకరణ అవసరం",
  patient: "రోగి",
  preConsultation: "సంప్రదింపుకు ముందు క్లినికల్ ఇంటేక్",
  step: "దశ",
  of: "లో",
  historyMode: "హిస్టరీ రకాన్ని ఎంచుకోండి",
  general: "సాధారణ",
  generalDescription: "ప్రామాణిక క్లినికల్ హిస్టరీ ఇంటర్వ్యూ",
  ayush: "ఆయుష్ / ఆయుర్వేదం",
  ayushDescription: "దశవిధ + ఆహార-విహార వివరాలు",
  chiefComplaint: "ఈరోజు మిమ్మల్ని ఇక్కడికి తీసుకువచ్చిన సమస్య ఏమిటి?",
  chiefComplaintSubtitle: "మొదట రోగి తన మాటల్లో చెప్పాలి. తర్వాత హిస్టరీని మరింత వివరించవచ్చు.",
  hpiTitle: "ప్రస్తుత అనారోగ్య చరిత్ర",
  hpiSubtitle: "ఈ ప్రశ్నలు నియంత్రిత క్లినికల్ హిస్టరీ నిర్మాణాన్ని అనుసరిస్తాయి. మాట్లాడవచ్చు లేదా టైప్ చేయవచ్చు.",
  onset: "ఎప్పుడు ప్రారంభమైంది?",
  duration: "ఎంతకాలంగా ఉంది?",
  character: "దీనిని ఎలా వివరిస్తారు?",
  location: "ఇది ఎక్కడ ఉంది?",
  radiation: "ఇది మరెక్కడికైనా వ్యాపిస్తుందా?",
  severity: "ఎంత తీవ్రంగా ఉంది?",
  aggravating: "దీనిని ఏది ఎక్కువ చేస్తుంది?",
  relieving: "దీనిని ఏది తగ్గిస్తుంది?",
  associatedSymptoms: "దీనితో పాటు మరే ఇతర లక్షణాలు ఉన్నాయా?",
  hpiHintChestPain: "ఛాతి నొప్పి కోసం, ఇది మీ చేయి, దవడ, మెడ లేదా వీపుకు వ్యాపిస్తుందా, మరియు దీనితో పాటు చెమట లేదా శ్వాస ఆడకపోవడం ఉందా అని కూడా పేర్కొనండి.",
  hpiHintFever: "జ్వరం కోసం, ఇది నిరంతరంగా ఉందా లేదా వస్తూ పోతూ ఉందా, మరియు కొలిస్తే గరిష్ట ఉష్ణోగ్రత ఎంత అని కూడా పేర్కొనండి.",
  hpiHintCough: "దగ్గు కోసం, ఇది పొడిగా ఉందా లేదా కఫంతో వస్తుందా, కఫం ఉంటే దాని రంగు ఏమిటో కూడా పేర్కొనండి.",
  hpiHintAbdominalPain: "కడుపు నొప్పి కోసం, ఇది తినడం, మలవిసర్జన, లేదా వాంతితో సంబంధం కలిగి ఉందా అని కూడా పేర్కొనండి.",
  hpiHintHeadache: "తలనొప్పి కోసం, వెలుతురు, శబ్దం లేదా కదలిక వల్ల ఇది తీవ్రమవుతుందా, మరియు దృష్టిలో ఏదైనా మార్పు ఉందా అని కూడా పేర్కొనండి.",
  pastTitle: "గత & ప్రస్తుత చరిత్ర",
  pastSubtitle: "రోగికి తెలిసిన సమాచారాన్ని నమోదు చేయండి. తెలియనిది ఖాళీగా ఉంచండి.",
  pastMedical: "గత వైద్య చరిత్ర",
  pastSurgical: "గత శస్త్రచికిత్స చరిత్ర",
  medications: "ప్రస్తుత మందులు",
  allergies: "అలర్జీలు",
  family: "కుటుంబ చరిత్ర",
  occupation: "వృత్తి",
  diet: "ఆహారం",
  sleep: "నిద్ర",
  smoking: "ధూమపానం / పొగాకు",
  alcohol: "మద్యం",
  reviewTitle: "శరీర వ్యవస్థల సమీక్ష & పరీక్షలు",
  reviewSubtitle: "ఇది నిర్మిత సమాచార సేకరణ మాత్రమే; స్వయంచాలక నిర్ధారణ కాదు.",
  ros: "శరీర వ్యవస్థల సమీక్ష",
  investigations: "మునుపటి పరీక్షలు",
  documentsTitle: "మునుపటి వైద్య పత్రాలను జోడించండి",
  documentsDescription: "ప్రిస్క్రిప్షన్, ల్యాబ్ రిపోర్ట్ లేదా డిశ్చార్జ్ సారాంశాన్ని అప్‌లోడ్ చేయండి. ప్రస్తుత AI డాక్యుమెంట్ పైప్‌లైన్ అందుబాటులో ఉన్న క్లినికల్ సమాచారాన్ని తీసుకుంటుంది.",
  analyze: "పత్రాలను విశ్లేషించండి",
  analyzing: "విశ్లేషిస్తోంది…",
  selectedSuffix: "పత్రం ఎంచుకోబడింది.",
  aiContext: "AI ద్వారా పొందిన సందర్భం",
  safetyScreen: "భద్రతా తనిఖీ",
  safetyText: "సంభావ్య అత్యవసర లక్షణాలను మానవ ట్రయాజ్ కోసం గుర్తిస్తాం. వ్యవస్థ నిర్ధారణ లేదా మందుల సూచన చేయదు.",
  review: "హిస్టరీ సమీక్ష",
  reviewSubtitle2: "క్లినిషియన్ ధృవీకరణకు పంపే ముందు డ్రాఫ్ట్‌ను సమీక్షించండి.",
  submit: "క్లినిషియన్ సమీక్షకు పంపండి",
  submitting: "పంపుతోంది…",
  submitted: "క్లినిషియన్ ధృవీకరణకు పంపబడింది",
  complete: "మీ ఇంటేక్ పెండింగ్ క్లినికల్ రికార్డుగా సేవ్ అయింది.",
  completionNote: "ప్రస్తుత క్లినిషియన్ ధృవీకరణ ప్రక్రియే తుది అధికారం. ధృవీకరణ వరకు ఇది నమ్మదగిన దీర్ఘకాల రికార్డు కాదు.",
  openRecords: "హెల్త్ రికార్డ్స్ తెరవండి",
  backDashboard: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
  urgent: "అత్యవసర శ్రద్ధ గుర్తించబడింది",
  triageNote: "ఇది ట్రయాజ్ ఎస్కలేషన్ సంకేతం; నిర్ధారణ కాదు.",
  voiceTouch: "వాయిస్ + టచ్",
  voiceTouchDescription: "ప్రతి ప్రశ్నకు సమాధానం చెప్పడానికి రెండు మార్గాలు",
  speakPrompt: "మీరు మాట్లాడి లేదా టైప్ చేసి సమాధానం ఇవ్వవచ్చు.",
  redFlagEscalation: "రెడ్-ఫ్లాగ్ ఎస్కలేషన్",
  redFlagDescription: "అత్యవసర లక్షణాలు సాధారణ ఇంటేక్‌ను ఆపవచ్చు",
  redFlagBody: "JeevanLink గుర్తించిన అత్యవసర లక్షణాలను మానవ శ్రద్ధ కోసం ఫ్లాగ్ చేస్తుంది. ఇది నిర్ధారణ లేదా మందుల సూచన చేయదు.",
  verificationGate: "ధృవీకరణ గేట్",
  verificationBody: "ప్రతి ఇంటేక్ PENDINGగా సేవ్ అవుతుంది. రికార్డు trustedగా మారే ముందు క్లినిషియన్ ధృవీకరణ తుది ఆధారం.",
  continue: "కొనసాగించండి",
  back: "వెనక్కి",
  speak: "మాట్లాడండి",
  stop: "ఆపండి",
  listening: "వింటున్నాను…",
  transcribing: "టెక్స్ట్‌గా మారుస్తోంది…",
  voiceUnavailable: "ఈ బ్రౌజర్‌లో వాయిస్ రికార్డింగ్ అందుబాటులో లేదు. సమాధానాన్ని టైప్ చేయవచ్చు.",
  voiceFailed: "వాయిస్ క్యాప్చర్ పూర్తికాలేదు. మళ్లీ ప్రయత్నించండి లేదా టైప్ చేయండి.",
  transcriptionFailed: "ఈ రికార్డింగ్‌ను టెక్స్ట్‌గా మార్చలేకపోయాం. మళ్లీ ప్రయత్నించండి లేదా టైప్ చేయండి.",
  notReported: "తెలియజేయలేదు",
  enterAnswer: "మీ సమాధానం నమోదు చేయండి…",
  quickChestPain: "ఛాతి నొప్పి",
  quickFever: "జ్వరం",
  quickCough: "దగ్గు",
  quickAbdominalPain: "కడుపు నొప్పి",
  quickHeadache: "తలనొప్పి",
  quickOther: "ఇతర",
  ayushContext: "ఆయుష్ సందర్భం",
  ayushIntro: "క్లినిషియన్ నిర్ణయాన్ని భర్తీ చేయకుండా అదనపు ఆయుర్వేద సమాచారాన్ని నమోదు చేయండి.",
  noDocuments: "మునుపటి పత్రాలు ఎంచుకోలేదు.",
  microphone: "మైక్రోఫోన్",
  consentClinicalHistory: "క్లినికల్ హిస్టరీ సేకరణకు నేను సమ్మతిస్తున్నాను.",
  consentDocumentProcessing: "సందర్భం సిద్ధం చేయడానికి వైద్య పత్రాలు ప్రాసెస్ చేయబడవచ్చని నాకు తెలుసు.",
  consentClinicianSharing: "ఈ డ్రాఫ్ట్‌ను చికిత్స చేసే క్లినిషియన్‌తో సమీక్ష కోసం పంచుకోవడానికి నేను సమ్మతిస్తున్నాను.",
  a11yAudioGuided: "ఆడియో గైడ్",
  a11yHighContrast: "అధిక కాంట్రాస్ట్",
  a11yLargeText: "పెద్ద టెక్స్ట్",
  dashavidhaNotesPlaceholder: "అదనపు గమనికలు (ఐచ్ఛికం)",
  prakritiTitle: "ప్రకృతి (శరీర నిర్మాణం)",
  prakritiDescription: "పుట్టుక నుండి నిర్ధారించబడిన మూల శరీర నిర్మాణం. దగ్గరి శాస్త్రీయ రకాన్ని ఎంచుకోండి.",
  vikritiTitle: "వికృతి (ప్రస్తుత అసమతుల్యత)",
  vikritiDescription: "మూల నిర్మాణం నుండి ప్రస్తుత విచలనం, ఏదైనా ఉంటే.",
  saraTitle: "సార (కణజాల నాణ్యత)",
  saraDescription: "శరీర కణజాలాల (ధాతువుల) మొత్తం నాణ్యత/సారాంశం. సంబంధిత అయితే ఏ కణజాలం అని గమనించండి.",
  samhananaTitle: "సంహనన (శరీర నిర్మాణ దృఢత్వం)",
  samhananaDescription: "శరీర నిర్మాణం యొక్క సాంద్రత మరియు సమీకృతత్వం.",
  pramanaTitle: "ప్రమాణ (శరీర నిష్పత్తి)",
  pramanaDescription: "ఆదర్శానికి సంబంధించి శరీర కొలతల నిష్పత్తి.",
  satmyaTitle: "సాత్మ్య (అనుకూలత)",
  satmyaDescription: "ఆహారం, వాతావరణం మరియు జీవనశైలిలో రోగి అలవాటుపడిన మరియు బాగా అనుకూలించుకున్నది.",
  sattvaTitle: "సత్త్వ (మానసిక బలం)",
  sattvaDescription: "మానసిక బలం మరియు మానసిక స్థితిస్థాపకత.",
  aharaShaktiTitle: "ఆహార శక్తి (జీర్ణ సామర్థ్యం)",
  aharaShaktiDescription: "ఆహారం తీసుకునే సామర్థ్యం మరియు దానిని జీర్ణం చేసుకునే సామర్థ్యం — విడివిడిగా అంచనా వేయబడుతుంది.",
  abhyavaharanaShaktiLabel: "అభ్యవహరణ శక్తి (ఆకలి / తీసుకునే సామర్థ్యం)",
  jaranaShaktiLabel: "జరణ శక్తి (జీర్ణ / జీవక్రియ సామర్థ్యం)",
  vyayamaShaktiTitle: "వ్యాయామ శక్తి (వ్యాయామ సామర్థ్యం)",
  vyayamaShaktiDescription: "శారీరక సహనశక్తి మరియు శ్రమను తట్టుకునే సామర్థ్యం.",
  vayaTitle: "వయ (వయస్సు వర్గం)",
  vayaDescription: "శాస్త్రీయ వయో-వర్గం, ఇది దోష బలం మరియు చికిత్స ప్రణాళికను ప్రభావితం చేస్తుంది.",
  vayaYearsLabel: "ఖచ్చితమైన వయస్సు సంవత్సరాలలో (ఐచ్ఛికం)",
  aharaViharaPlaceholder: "సాధారణ రోజువారీ ఆహారం మరియు జీవనశైలి విధానం…",
  nidanaPlaceholder: "దీనిని ఏది ప్రేరేపించిందని లేదా కారణమైందని రోగి నమ్ముతున్నారు…",
  sampraptiPlaceholder: "వ్యాధి ప్రక్రియపై క్లినికల్ తార్కికం — సాధారణంగా క్లినీషియన్ చేత పూర్తి చేయబడుతుంది లేదా మెరుగుపరచబడుతుంది…",
  doshaVata: "వాత",
  doshaPitta: "పిత్త",
  doshaKapha: "కఫ",
  doshaVataPitta: "వాత-పిత్త",
  doshaPittaKapha: "పిత్త-కఫ",
  doshaVataKapha: "వాత-కఫ",
  doshaSama: "సమ (త్రిదోషజ / సమతుల్యం)",
  vikritiNoImbalance: "గణనీయమైన అసమతుల్యత గమనించబడలేదు",
  gradePravara: "ప్రవర (అధిక)",
  gradeMadhyama: "మధ్యమ (మధ్యస్థ)",
  gradeAvara: "అవర (తక్కువ)",
  satmyaSama: "సమ సాత్మ్య — సమతుల్యం, బాగా అనుకూలించుకున్నది",
  satmyaVishama: "విషమ సాత్మ్య — క్రమరహిత, పేద అనుకూలత",
  satmyaEkaRasa: "ఏక రస సాత్మ్య — ఒక ప్రధాన రుచికి అలవాటుపడినది",
  vayaBala: "బాల — బాల్యం (సుమారు 16 సంవత్సరాల వరకు)",
  vayaMadhyama: "మధ్యమ / యువ — వయోజన (16–70 సంవత్సరాలు)",
  vayaVriddha: "వృద్ధ — వృద్ధాప్యం (70+ సంవత్సరాలు)",
  dashavidhaReviewTitle: "దశవిధ పరీక్ష",
};

const mr: ClinicalIntakeText = {
  title: "सल्लामसलतीपूर्वी तुमची क्लिनिकल हिस्ट्री.",
  subtitle: "आज तुम्हाला येथे कशामुळे यावे लागले ते JeevanLink ला सांगा. बोला किंवा टॅप करा.",
  consentTitle: "संमती आणि नियंत्रण",
  consentText: "तुमची उत्तरे क्लिनिशियनच्या पुनरावलोकनासाठी क्लिनिकल हिस्ट्रीचा मसुदा तयार करण्यासाठी वापरली जातील. हे साधन निदान किंवा औषध देत नाही.",
  listenExplanation: "स्पष्टीकरण ऐका",
  audioGuided: "ऑडिओ-मार्गदर्शित संमती",
  voiceLanguage: "व्हॉइस भाषा",
  humanVerification: "मानवी पडताळणी आवश्यक",
  patient: "रुग्ण",
  preConsultation: "सल्ल्यापूर्वी क्लिनिकल इंटेक",
  step: "टप्पा",
  of: "पैकी",
  historyMode: "हिस्ट्रीचा प्रकार निवडा",
  general: "सामान्य",
  generalDescription: "मानक क्लिनिकल हिस्ट्री मुलाखत",
  ayush: "आयुष / आयुर्वेद",
  ayushDescription: "दशविध + आहार-विहार माहिती",
  chiefComplaint: "आज तुम्हाला कोणत्या समस्येसाठी मदत हवी आहे?",
  chiefComplaintSubtitle: "प्रथम रुग्णाने स्वतःच्या शब्दांत सांगा. पुढे हिस्ट्री अधिक स्पष्ट करता येईल.",
  hpiTitle: "सध्याच्या आजाराचा इतिहास",
  hpiSubtitle: "हे प्रश्न संरचित क्लिनिकल हिस्ट्री पद्धतीचे पालन करतात. रुग्ण बोलू किंवा टाइप करू शकतो.",
  onset: "कधी सुरू झाले?",
  duration: "किती काळापासून आहे?",
  character: "तुम्ही ते कसे वर्णन कराल?",
  location: "ते कुठे आहे?",
  radiation: "ते इतरत्र पसरते का?",
  severity: "तीव्रता किती आहे?",
  aggravating: "कशामुळे वाढते?",
  relieving: "कशामुळे कमी होते?",
  associatedSymptoms: "यासोबत आणखी काही लक्षणे आहेत का?",
  hpiHintChestPain: "छातीत दुखण्यासाठी, हे देखील नमूद करा की ते तुमच्या हातात, जबड्यात, मानेत किंवा पाठीत पसरते का, आणि त्यासोबत घाम येणे किंवा श्वास घेण्यास त्रास होतो का.",
  hpiHintFever: "तापासाठी, हे देखील नमूद करा की तो सतत आहे की येतो-जातो, आणि मोजले असल्यास सर्वाधिक तापमान किती होते.",
  hpiHintCough: "खोकल्यासाठी, हे देखील नमूद करा की तो कोरडा आहे की कफयुक्त, आणि कफ असल्यास त्याचा रंग काय आहे.",
  hpiHintAbdominalPain: "पोटदुखीसाठी, हे देखील नमूद करा की त्याचा संबंध जेवण, शौचास, किंवा उलटीशी आहे का.",
  hpiHintHeadache: "डोकेदुखीसाठी, हे देखील नमूद करा की प्रकाश, आवाज किंवा हालचालीने ते वाढते का, आणि दृष्टीत काही बदल आहे का.",
  pastTitle: "मागील आणि सध्याचा इतिहास",
  pastSubtitle: "रुग्णाला माहीत असलेली माहिती द्या. माहीत नसेल तर रिकामे ठेवा.",
  pastMedical: "मागील वैद्यकीय इतिहास",
  pastSurgical: "मागील शस्त्रक्रियेचा इतिहास",
  medications: "सध्याची औषधे",
  allergies: "अॅलर्जी",
  family: "कौटुंबिक इतिहास",
  occupation: "व्यवसाय",
  diet: "आहार",
  sleep: "झोप",
  smoking: "धूम्रपान / तंबाखू",
  alcohol: "मद्यपान",
  reviewTitle: "सिस्टम रिव्ह्यू आणि तपासण्या",
  reviewSubtitle: "ही संरचित माहिती नोंदवण्याची पद्धत आहे; स्वयंचलित निदान नाही.",
  ros: "सिस्टम रिव्ह्यू",
  investigations: "मागील तपासण्या",
  documentsTitle: "मागील वैद्यकीय कागदपत्रे जोडा",
  documentsDescription: "प्रिस्क्रिप्शन, लॅब रिपोर्ट किंवा डिस्चार्ज सारांश अपलोड करा. विद्यमान AI दस्तऐवज पाइपलाइन उपलब्ध क्लिनिकल माहिती काढेल.",
  analyze: "कागदपत्रांचे विश्लेषण करा",
  analyzing: "विश्लेषण सुरू आहे…",
  selectedSuffix: "कागदपत्रे निवडली आहेत.",
  aiContext: "AI ने काढलेली माहिती",
  safetyScreen: "सुरक्षा तपासणी",
  safetyText: "संभाव्य आपत्कालीन लक्षणे मानवी ट्रायाजसाठी चिन्हांकित केली जातील. प्रणाली निदान किंवा औषध देणार नाही.",
  review: "हिस्ट्री तपासा",
  reviewSubtitle2: "क्लिनिशियनकडे पाठवण्यापूर्वी मसुदा तपासा.",
  submit: "क्लिनिशियनच्या पुनरावलोकनासाठी पाठवा",
  submitting: "पाठवत आहे…",
  submitted: "क्लिनिशियन पडताळणीसाठी पाठवले",
  complete: "तुमची हिस्ट्री पेंडिंग क्लिनिकल रेकॉर्ड म्हणून सेव्ह झाली आहे.",
  completionNote: "विद्यमान क्लिनिशियन-व्हेरिफिकेशन प्रक्रिया अंतिम अधिकार आहे. पडताळणी होईपर्यंत ही trusted longitudinal माहिती होणार नाही.",
  openRecords: "हेल्थ रेकॉर्ड उघडा",
  backDashboard: "डॅशबोर्डवर परत जा",
  urgent: "तातडीचे लक्ष आवश्यक",
  triageNote: "हा ट्रायाज एस्कलेशन संकेत आहे, निदान नाही.",
  voiceTouch: "व्हॉइस + टच",
  voiceTouchDescription: "प्रत्येक प्रश्नाचे उत्तर देण्याचे दोन मार्ग",
  speakPrompt: "तुम्ही बोलून किंवा टाइप करून उत्तर देऊ शकता.",
  redFlagEscalation: "रेड-फ्लॅग एस्कलेशन",
  redFlagDescription: "आपत्कालीन लक्षणे नियमित इंटेक थांबवू शकतात",
  redFlagBody: "JeevanLink कॉन्फिगर केलेली तातडीची लक्षणे मानवी लक्षासाठी फ्लॅग करते. हे निदान किंवा औषध देत नाही.",
  verificationGate: "पडताळणी गेट",
  verificationBody: "प्रत्येक इंटेक PENDING म्हणून सेव्ह होतो. रेकॉर्ड trusted होण्यापूर्वी क्लिनिशियन पडताळणी अंतिम स्रोत आहे.",
  continue: "पुढे",
  back: "मागे",
  speak: "बोला",
  stop: "थांबा",
  listening: "ऐकत आहे…",
  transcribing: "टेक्स्टमध्ये बदलत आहे…",
  voiceUnavailable: "या ब्राउझरमध्ये व्हॉइस रेकॉर्डिंग उपलब्ध नाही. तुम्ही उत्तर टाइप करू शकता.",
  voiceFailed: "व्हॉइस कॅप्चर पूर्ण झाले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.",
  transcriptionFailed: "या रेकॉर्डिंगचे टेक्स्टमध्ये रूपांतर करता आले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.",
  notReported: "माहिती दिलेली नाही",
  enterAnswer: "तुमचे उत्तर लिहा…",
  quickChestPain: "छातीत दुखणे",
  quickFever: "ताप",
  quickCough: "खोकला",
  quickAbdominalPain: "पोटदुखी",
  quickHeadache: "डोकेदुखी",
  quickOther: "इतर",
  ayushContext: "आयुष संदर्भ",
  ayushIntro: "क्लिनिशियनचा निर्णय न बदलता अतिरिक्त आयुर्वेदिक संदर्भ नोंदवा.",
  noDocuments: "मागील कोणतीही कागदपत्रे निवडलेली नाहीत.",
  microphone: "मायक्रोफोन",
  consentClinicalHistory: "मी क्लिनिकल हिस्ट्री नोंदणीस संमती देतो/देते.",
  consentDocumentProcessing: "संदर्भ तयार करण्यासाठी वैद्यकीय कागदपत्रांवर प्रक्रिया होऊ शकते हे मला समजते.",
  consentClinicianSharing: "हा मसुदा उपचार करणाऱ्या क्लिनिशियनसोबत पुनरावलोकनासाठी शेअर करण्यास मी संमती देतो/देते.",
  a11yAudioGuided: "ऑडिओ मार्गदर्शक",
  a11yHighContrast: "उच्च कॉन्ट्रास्ट",
  a11yLargeText: "मोठा मजकूर",
  dashavidhaNotesPlaceholder: "अतिरिक्त टिपा (ऐच्छिक)",
  prakritiTitle: "प्रकृती (शारीरिक रचना)",
  prakritiDescription: "जन्मापासून निश्चित झालेली मूळ शारीरिक रचना. सर्वात जवळचा शास्त्रीय प्रकार निवडा.",
  vikritiTitle: "विकृती (सध्याचे असंतुलन)",
  vikritiDescription: "मूळ प्रकृतीपासूनचे सध्याचे विचलन, असल्यास.",
  saraTitle: "सार (ऊती गुणवत्ता)",
  saraDescription: "शरीरातील ऊतींची (धातूंची) एकूण गुणवत्ता/सार. संबंधित असल्यास कोणती ऊती हे नमूद करा.",
  samhananaTitle: "संहनन (शरीरबांधणी)",
  samhananaDescription: "शरीरबांधणीची घट्टपणा आणि एकसंधता.",
  pramanaTitle: "प्रमाण (शरीर प्रमाणबद्धता)",
  pramanaDescription: "आदर्शाच्या तुलनेत शरीराच्या मोजमापांचे प्रमाण.",
  satmyaTitle: "सात्म्य (अनुकूलता)",
  satmyaDescription: "आहार, हवामान आणि जीवनशैलीत रुग्ण ज्याची सवय झाली आहे आणि चांगल्या प्रकारे जुळवून घेतले आहे ते.",
  sattvaTitle: "सत्त्व (मानसिक शक्ती)",
  sattvaDescription: "मानसिक शक्ती आणि मानसिक लवचिकता.",
  aharaShaktiTitle: "आहार शक्ती (पचन क्षमता)",
  aharaShaktiDescription: "अन्न ग्रहण करण्याची क्षमता आणि ते पचवण्याची क्षमता — स्वतंत्रपणे मूल्यांकन केले जाते.",
  abhyavaharanaShaktiLabel: "अभ्यवहरण शक्ती (भूक / ग्रहण क्षमता)",
  jaranaShaktiLabel: "जारण शक्ती (पचन / चयापचय क्षमता)",
  vyayamaShaktiTitle: "व्यायाम शक्ती (व्यायाम क्षमता)",
  vyayamaShaktiDescription: "शारीरिक सहनशक्ती आणि श्रम सहन करण्याची क्षमता.",
  vayaTitle: "वय (वय गट)",
  vayaDescription: "शास्त्रीय वयोगट, जो दोष बल आणि उपचार नियोजनावर परिणाम करतो.",
  vayaYearsLabel: "नेमके वय वर्षांत (ऐच्छिक)",
  aharaViharaPlaceholder: "नेहमीचा दैनंदिन आहार आणि जीवनशैली पद्धत…",
  nidanaPlaceholder: "रुग्णाला वाटते की याला कशामुळे चालना मिळाली किंवा कारणीभूत ठरले…",
  sampraptiPlaceholder: "रोग प्रक्रियेवरील क्लिनिकल तर्क — सामान्यतः क्लिनिशियनद्वारे पूर्ण किंवा सुधारित केले जाते…",
  doshaVata: "वात",
  doshaPitta: "पित्त",
  doshaKapha: "कफ",
  doshaVataPitta: "वात-पित्त",
  doshaPittaKapha: "पित्त-कफ",
  doshaVataKapha: "वात-कफ",
  doshaSama: "सम (त्रिदोषज / संतुलित)",
  vikritiNoImbalance: "लक्षणीय असंतुलन आढळले नाही",
  gradePravara: "प्रवर (उच्च)",
  gradeMadhyama: "मध्यम (मध्यम)",
  gradeAvara: "अवर (कमी)",
  satmyaSama: "सम सात्म्य — संतुलित, चांगल्या प्रकारे जुळवून घेतलेले",
  satmyaVishama: "विषम सात्म्य — अनियमित, कमी अनुकूलता",
  satmyaEkaRasa: "एक रस सात्म्य — एका प्रमुख चवीची सवय असलेले",
  vayaBala: "बाल — बालपण (सुमारे 16 वर्षांपर्यंत)",
  vayaMadhyama: "मध्यम / युवा — प्रौढ (16–70 वर्षे)",
  vayaVriddha: "वृद्ध — वृद्धापकाळ (70+ वर्षे)",
  dashavidhaReviewTitle: "दशविध परीक्षा",
};

const gu: ClinicalIntakeText = {
  title: "પરામર્શ પહેલાં તમારી ક્લિનિકલ હિસ્ટરી.",
  subtitle: "આજે તમને અહીં શું લાવ્યું તે JeevanLinkને કહો. બોલો અથવા ટૅપ કરો.",
  consentTitle: "સંમતિ અને નિયંત્રણ",
  consentText: "તમારા જવાબો ક્લિનિશિયનની સમીક્ષા માટે ક્લિનિકલ હિસ્ટરીનો ડ્રાફ્ટ બનાવવા માટે વપરાશે. આ ટૂલ નિદાન અથવા દવા સૂચવતું નથી.",
  listenExplanation: "સમજૂતી સાંભળો",
  audioGuided: "ઑડિયો માર્ગદર્શિત સંમતિ",
  voiceLanguage: "વોઇસ ભાષા",
  humanVerification: "માનવીય ચકાસણી જરૂરી",
  patient: "દર્દી",
  preConsultation: "પરામર્શ પહેલાં ક્લિનિકલ ઇન્ટેક",
  step: "પગલું",
  of: "માંથી",
  historyMode: "હિસ્ટરીનો પ્રકાર પસંદ કરો",
  general: "સામાન્ય",
  generalDescription: "માનક ક્લિનિકલ હિસ્ટરી ઇન્ટરવ્યૂ",
  ayush: "આયુષ / આયુર્વેદ",
  ayushDescription: "દશવિધ + આહાર-વિહાર વિગતો",
  chiefComplaint: "આજે તમને કઈ સમસ્યા માટે મદદ જોઈએ છે?",
  chiefComplaintSubtitle: "સૌપ્રથમ દર્દીના પોતાના શબ્દોમાં કહો. આગળ હિસ્ટરી વધુ સ્પષ્ટ કરી શકાશે.",
  hpiTitle: "હાલની બીમારીનો ઇતિહાસ",
  hpiSubtitle: "આ પ્રશ્નો નિયંત્રિત ક્લિનિકલ હિસ્ટરી માળખાને અનુસરે છે. દર્દી બોલી અથવા ટાઇપ કરી શકે છે.",
  onset: "ક્યારે શરૂ થયું?",
  duration: "કેટલા સમયથી છે?",
  character: "તમે તેને કેવી રીતે વર્ણવશો?",
  location: "તે ક્યાં છે?",
  radiation: "શું તે ક્યાંક ફેલાય છે?",
  severity: "કેટલું ગંભીર છે?",
  aggravating: "તેને શું વધારે છે?",
  relieving: "તેને શું ઓછું કરે છે?",
  associatedSymptoms: "તેની સાથે અન્ય કોઈ લક્ષણો છે?",
  hpiHintChestPain: "છાતીના દુખાવા માટે, એ પણ નોંધો કે તે તમારા હાથ, જડબા, ગરદન અથવા પીઠમાં ફેલાય છે કે નહીં, અને તેની સાથે પરસેવો અથવા શ્વાસ લેવામાં તકલીફ છે કે નહીં.",
  hpiHintFever: "તાવ માટે, એ પણ નોંધો કે તે સતત છે કે આવે-જાય છે, અને માપ્યું હોય તો સૌથી વધુ તાપમાન કેટલું હતું.",
  hpiHintCough: "ખાંસી માટે, એ પણ નોંધો કે તે સૂકી છે કે કફવાળી, અને કફ હોય તો તેનો રંગ શું છે.",
  hpiHintAbdominalPain: "પેટના દુખાવા માટે, એ પણ નોંધો કે તેનો સંબંધ ખાવા, મળત્યાગ, અથવા ઉલટી સાથે છે કે નહીં.",
  hpiHintHeadache: "માથાના દુખાવા માટે, એ પણ નોંધો કે પ્રકાશ, અવાજ અથવા હલનચલનથી તે વધે છે કે નહીં, અને દ્રષ્ટિમાં કોઈ ફેરફાર છે કે નહીં.",
  pastTitle: "પાછલો અને વર્તમાન ઇતિહાસ",
  pastSubtitle: "દર્દીને જે માહિતી ખબર છે તે આપો. ખબર ન હોય તો ખાલી રાખો.",
  pastMedical: "પાછલો તબીબી ઇતિહાસ",
  pastSurgical: "પાછલી સર્જરીનો ઇતિહાસ",
  medications: "હાલની દવાઓ",
  allergies: "એલર્જી",
  family: "કુટુંબનો ઇતિહાસ",
  occupation: "વ્યવસાય",
  diet: "આહાર",
  sleep: "ઊંઘ",
  smoking: "ધુમ્રપાન / તમાકુ",
  alcohol: "દારૂ",
  reviewTitle: "સિસ્ટમ રિવ્યૂ અને તપાસો",
  reviewSubtitle: "આ રચનાત્મક માહિતી સંગ્રહ છે; સ્વચાલિત નિદાન નથી.",
  ros: "સિસ્ટમ રિવ્યૂ",
  investigations: "અગાઉની તપાસો",
  documentsTitle: "અગાઉના તબીબી દસ્તાવેજો ઉમેરો",
  documentsDescription: "પ્રિસ્ક્રિપ્શન, લેબ રિપોર્ટ અથવા ડિસ્ચાર્જ સારાંશ અપલોડ કરો. હાલની AI દસ્તાવેજ પાઇપલાઇન ઉપલબ્ધ ક્લિનિકલ માહિતી બહાર કાઢશે.",
  analyze: "દસ્તાવેજોનું વિશ્લેષણ કરો",
  analyzing: "વિશ્લેષણ થઈ રહ્યું છે…",
  selectedSuffix: "દસ્તાવેજ પસંદ થયો.",
  aiContext: "AI દ્વારા મેળવેલી માહિતી",
  safetyScreen: "સુરક્ષા ચકાસણી",
  safetyText: "શક્ય તાત્કાલિક લક્ષણો માનવીય ટ્રાયાજ માટે ફ્લેગ કરવામાં આવશે. સિસ્ટમ નિદાન કે દવા નહીં આપે.",
  review: "હિસ્ટરીની સમીક્ષા",
  reviewSubtitle2: "ક્લિનિશિયન સમીક્ષા માટે મોકલતા પહેલાં ડ્રાફ્ટ તપાસો.",
  submit: "ક્લિનિશિયન સમીક્ષા માટે મોકલો",
  submitting: "મોકલી રહ્યા છીએ…",
  submitted: "ક્લિનિશિયન ચકાસણી માટે મોકલાયું",
  complete: "તમારી ઇન્ટેક પેન્ડિંગ ક્લિનિકલ રેકોર્ડ તરીકે સેવ થઈ છે.",
  completionNote: "હાલની ક્લિનિશિયન ચકાસણી પ્રક્રિયા અંતિમ સત્તા છે. ચકાસણી પહેલાં આ trusted longitudinal માહિતી બનશે નહીં.",
  openRecords: "હેલ્થ રેકોર્ડ ખોલો",
  backDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
  urgent: "તાત્કાલિક ધ્યાન જરૂરી",
  triageNote: "આ ટ્રાયાજ એસ્કલેશન સંકેત છે, નિદાન નહીં.",
  voiceTouch: "વોઇસ + ટચ",
  voiceTouchDescription: "દરેક પ્રશ્નનો જવાબ આપવા બે રીતો",
  speakPrompt: "તમે બોલીને અથવા ટાઇપ કરીને જવાબ આપી શકો છો.",
  redFlagEscalation: "રેડ-ફ્લેગ એસ્કલેશન",
  redFlagDescription: "તાત્કાલિક લક્ષણો નિયમિત ઇન્ટેક રોકી શકે છે",
  redFlagBody: "JeevanLink ગોઠવાયેલા તાત્કાલિક લક્ષણોને માનવીય ધ્યાન માટે ફ્લેગ કરે છે. તે નિદાન કે દવા આપતું નથી.",
  verificationGate: "ચકાસણી ગેટ",
  verificationBody: "દરેક ઇન્ટેક PENDING તરીકે સેવ થાય છે. રેકોર્ડ trusted બનતા પહેલાં ક્લિનિશિયન ચકાસણી અંતિમ સ્ત્રોત છે.",
  continue: "આગળ",
  back: "પાછળ",
  speak: "બોલો",
  stop: "બંધ કરો",
  listening: "સાંભળી રહ્યા છીએ…",
  transcribing: "ટેક્સ્ટમાં ફેરવી રહ્યા છીએ…",
  voiceUnavailable: "આ બ્રાઉઝરમાં વોઇસ રેકોર્ડિંગ ઉપલબ્ધ નથી. તમે જવાબ ટાઇપ કરી શકો છો.",
  voiceFailed: "વોઇસ કૅપ્ચર પૂર્ણ થઈ શક્યું નથી. ફરી પ્રયાસ કરો અથવા ટાઇપ કરો.",
  transcriptionFailed: "આ રેકોર્ડિંગને ટેક્સ્ટમાં ફેરવી શક્યા નથી. ફરી પ્રયાસ કરો અથવા ટાઇપ કરો.",
  notReported: "જણાવ્યું નથી",
  enterAnswer: "તમારો જવાબ લખો…",
  quickChestPain: "છાતીમાં દુખાવો",
  quickFever: "તાવ",
  quickCough: "ઉધરસ",
  quickAbdominalPain: "પેટમાં દુખાવો",
  quickHeadache: "માથાનો દુખાવો",
  quickOther: "અન્ય",
  ayushContext: "આયુષ સંદર્ભ",
  ayushIntro: "ક્લિનિશિયનના નિર્ણયને બદલે નહીં, વધારાનો આયુર્વેદિક સંદર્ભ નોંધો.",
  noDocuments: "કોઈ અગાઉના દસ્તાવેજો પસંદ નથી.",
  microphone: "માઇક્રોફોન",
  consentClinicalHistory: "હું ક્લિનિકલ હિસ્ટરી કૅપ્ચર માટે સંમત છું.",
  consentDocumentProcessing: "હું સમજું છું કે સંદર્ભ તૈયાર કરવા માટે તબીબી દસ્તાવેજો પ્રોસેસ થઈ શકે છે.",
  consentClinicianSharing: "આ ડ્રાફ્ટને સારવાર કરતા ક્લિનિશિયન સાથે સમીક્ષા માટે શેર કરવા હું સંમત છું.",
  a11yAudioGuided: "ઓડિયો ગાઇડ",
  a11yHighContrast: "ઉચ્ચ કોન્ટ્રાસ્ટ",
  a11yLargeText: "મોટું લખાણ",
  dashavidhaNotesPlaceholder: "વધારાની નોંધો (વૈકલ્પિક)",
  prakritiTitle: "પ્રકૃતિ (શારીરિક બંધારણ)",
  prakritiDescription: "જન્મથી નિર્ધારિત મૂળ શારીરિક બંધારણ. સૌથી નજીકનો શાસ્ત્રીય પ્રકાર પસંદ કરો.",
  vikritiTitle: "વિકૃતિ (વર્તમાન અસંતુલન)",
  vikritiDescription: "મૂળ બંધારણમાંથી વર્તમાન વિચલન, જો કોઈ હોય તો.",
  saraTitle: "સાર (પેશી ગુણવત્તા)",
  saraDescription: "શરીરના પેશીઓ (ધાતુઓ) ની એકંદર ગુણવત્તા/સાર. સંબંધિત હોય તો કઈ પેશી તે નોંધો.",
  samhananaTitle: "સંહનન (શરીર બાંધો)",
  samhananaDescription: "શરીર બાંધાની ઘનતા અને એકત્રીકરણ.",
  pramanaTitle: "પ્રમાણ (શરીર પ્રમાણ)",
  pramanaDescription: "આદર્શની તુલનામાં શરીરના માપનું પ્રમાણ.",
  satmyaTitle: "સાત્મ્ય (અનુકૂળતા)",
  satmyaDescription: "આહાર, આબોહવા અને જીવનશૈલીમાં દર્દી જેની ટેવાયેલ છે અને સારી રીતે અનુકૂળ છે તે.",
  sattvaTitle: "સત્ત્વ (માનસિક શક્તિ)",
  sattvaDescription: "માનસિક શક્તિ અને માનસિક સ્થિતિસ્થાપકતા.",
  aharaShaktiTitle: "આહાર શક્તિ (પાચન ક્ષમતા)",
  aharaShaktiDescription: "ખોરાક લેવાની ક્ષમતા અને તેને પચાવવાની ક્ષમતા — અલગ રીતે મૂલ્યાંકિત.",
  abhyavaharanaShaktiLabel: "અભ્યવહરણ શક્તિ (ભૂખ / ગ્રહણ ક્ષમતા)",
  jaranaShaktiLabel: "જારણ શક્તિ (પાચન / ચયાપચય ક્ષમતા)",
  vyayamaShaktiTitle: "વ્યાયામ શક્તિ (કસરત ક્ષમતા)",
  vyayamaShaktiDescription: "શારીરિક સહનશક્તિ અને શ્રમ સહન કરવાની ક્ષમતા.",
  vayaTitle: "વય (વય વર્ગ)",
  vayaDescription: "શાસ્ત્રીય વય-વર્ગ, જે દોષ શક્તિ અને સારવાર આયોજનને અસર કરે છે.",
  vayaYearsLabel: "ચોક્કસ ઉંમર વર્ષોમાં (વૈકલ્પિક)",
  aharaViharaPlaceholder: "લાક્ષણિક દૈનિક આહાર અને જીવનશૈલી પેટર્ન…",
  nidanaPlaceholder: "દર્દી માને છે કે આનું કારણ શું અથવા શેનાથી ટ્રિગર થયું…",
  sampraptiPlaceholder: "રોગ પ્રક્રિયા પર ક્લિનિકલ તર્ક — સામાન્ય રીતે ક્લિનિશિયન દ્વારા પૂર્ણ અથવા શુદ્ધ કરવામાં આવે છે…",
  doshaVata: "વાત",
  doshaPitta: "પિત્ત",
  doshaKapha: "કફ",
  doshaVataPitta: "વાત-પિત્ત",
  doshaPittaKapha: "પિત્ત-કફ",
  doshaVataKapha: "વાત-કફ",
  doshaSama: "સમ (ત્રિદોષજ / સંતુલિત)",
  vikritiNoImbalance: "કોઈ નોંધપાત્ર અસંતુલન નોંધાયું નથી",
  gradePravara: "પ્રવર (ઉચ્ચ)",
  gradeMadhyama: "મધ્યમ (મધ્યમ)",
  gradeAvara: "અવર (નીચું)",
  satmyaSama: "સમ સાત્મ્ય — સંતુલિત, સારી રીતે અનુકૂળ",
  satmyaVishama: "વિષમ સાત્મ્ય — અનિયમિત, નબળી અનુકૂળતા",
  satmyaEkaRasa: "એક રસ સાત્મ્ય — એક પ્રભાવશાળી સ્વાદની ટેવ",
  vayaBala: "બાલ — બાળપણ (લગભગ 16 વર્ષ સુધી)",
  vayaMadhyama: "મધ્યમ / યુવા — પુખ્ત (16–70 વર્ષ)",
  vayaVriddha: "વૃદ્ધ — વૃદ્ધાવસ્થા (70+ વર્ષ)",
  dashavidhaReviewTitle: "દશવિધ પરીક્ષા",
};

const kn: ClinicalIntakeText = {
  title: "ಸಮಾಲೋಚನೆಗೂ ಮೊದಲು ನಿಮ್ಮ ಕ್ಲಿನಿಕಲ್ ಹಿಸ್ಟರಿ.",
  subtitle: "ಇಂದು ನಿಮ್ಮನ್ನು ಇಲ್ಲಿ ತಂದ ಸಮಸ್ಯೆಯನ್ನು JeevanLinkಗೆ ತಿಳಿಸಿ. ಮಾತನಾಡಿ ಅಥವಾ ಟ್ಯಾಪ್ ಮಾಡಿ.",
  consentTitle: "ಒಪ್ಪಿಗೆ ಮತ್ತು ನಿಯಂತ್ರಣ",
  consentText: "ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ವೈದ್ಯರ ಪರಿಶೀಲನೆಗಾಗಿ ಕ್ಲಿನಿಕಲ್ ಹಿಸ್ಟರಿ ಡ್ರಾಫ್ಟ್ ಮಾಡಲು ಬಳಸಲಾಗುತ್ತದೆ. ಈ ಸಾಧನ ರೋಗನಿರ್ಣಯ ಅಥವಾ ಔಷಧ ನೀಡುವುದಿಲ್ಲ.",
  listenExplanation: "ವಿವರಣೆಯನ್ನು ಕೇಳಿ",
  audioGuided: "ಆಡಿಯೋ ಮಾರ್ಗದರ್ಶಿತ ಒಪ್ಪಿಗೆ",
  voiceLanguage: "ಧ್ವನಿ ಭಾಷೆ",
  humanVerification: "ಮಾನವ ಪರಿಶೀಲನೆ ಅಗತ್ಯ",
  patient: "ರೋಗಿ",
  preConsultation: "ಸಮಾಲೋಚನೆಗೂ ಮೊದಲು ಕ್ಲಿನಿಕಲ್ ಇನ್‌ಟೇಕ್",
  step: "ಹಂತ",
  of: "ರಲ್ಲಿ",
  historyMode: "ಹಿಸ್ಟರಿ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  general: "ಸಾಮಾನ್ಯ",
  generalDescription: "ಪ್ರಮಾಣಿತ ಕ್ಲಿನಿಕಲ್ ಹಿಸ್ಟರಿ ಸಂದರ್ಶನ",
  ayush: "ಆಯುಷ್ / ಆಯುರ್ವೇದ",
  ayushDescription: "ದಶವಿಧ + ಆಹಾರ-ವಿಹಾರ ವಿವರಗಳು",
  chiefComplaint: "ಇಂದು ನಿಮ್ಮನ್ನು ಇಲ್ಲಿ ತಂದ ಸಮಸ್ಯೆ ಏನು?",
  chiefComplaintSubtitle: "ಮೊದಲು ರೋಗಿಯ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ಹೇಳಿ. ಮುಂದೆ ಹಿಸ್ಟರಿಯನ್ನು ಇನ್ನಷ್ಟು ವಿವರಿಸಬಹುದು.",
  hpiTitle: "ಪ್ರಸ್ತುತ ಅನಾರೋಗ್ಯದ ಇತಿಹಾಸ",
  hpiSubtitle: "ಈ ಪ್ರಶ್ನೆಗಳು ನಿಯಂತ್ರಿತ ಕ್ಲಿನಿಕಲ್ ಹಿಸ್ಟರಿ ರಚನೆಯನ್ನು ಅನುಸರಿಸುತ್ತವೆ. ಮಾತನಾಡಬಹುದು ಅಥವಾ ಟೈಪ್ ಮಾಡಬಹುದು.",
  onset: "ಯಾವಾಗ ಪ್ರಾರಂಭವಾಯಿತು?",
  duration: "ಎಷ್ಟು ದಿನಗಳಿಂದ ಇದೆ?",
  character: "ಇದನ್ನು ಹೇಗೆ ವಿವರಿಸುತ್ತೀರಿ?",
  location: "ಇದು ಎಲ್ಲಿ ಇದೆ?",
  radiation: "ಇದು ಬೇರೆಡೆಗೆ ಹರಡುತ್ತದೆಯೇ?",
  severity: "ಎಷ್ಟು ತೀವ್ರವಾಗಿದೆ?",
  aggravating: "ಇದನ್ನು ಏನು ಹೆಚ್ಚಿಸುತ್ತದೆ?",
  relieving: "ಇದನ್ನು ಏನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ?",
  associatedSymptoms: "ಇದರೊಂದಿಗೆ ಬೇರೆ ಯಾವುದೇ ಲಕ್ಷಣಗಳಿವೆಯೇ?",
  hpiHintChestPain: "ಎದೆ ನೋವಿಗೆ, ಅದು ನಿಮ್ಮ ತೋಳು, ದವಡೆ, ಕುತ್ತಿಗೆ ಅಥವಾ ಬೆನ್ನಿಗೆ ಹರಡುತ್ತದೆಯೇ, ಮತ್ತು ಅದರೊಂದಿಗೆ ಬೆವರುವಿಕೆ ಅಥವಾ ಉಸಿರಾಟದ ತೊಂದರೆ ಇದೆಯೇ ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ.",
  hpiHintFever: "ಜ್ವರಕ್ಕೆ, ಅದು ನಿರಂತರವಾಗಿದೆಯೇ ಅಥವಾ ಬಂದು ಹೋಗುತ್ತದೆಯೇ, ಮತ್ತು ಅಳೆದಿದ್ದರೆ ಗರಿಷ್ಠ ತಾಪಮಾನ ಎಷ್ಟಿತ್ತು ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ.",
  hpiHintCough: "ಕೆಮ್ಮಿಗೆ, ಅದು ಒಣಗಿದೆಯೇ ಅಥವಾ ಕಫದೊಂದಿಗೆ ಬರುತ್ತದೆಯೇ, ಕಫ ಇದ್ದರೆ ಅದರ ಬಣ್ಣ ಏನು ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ.",
  hpiHintAbdominalPain: "ಹೊಟ್ಟೆ ನೋವಿಗೆ, ಅದು ಆಹಾರ ಸೇವನೆ, ಮಲವಿಸರ್ಜನೆ, ಅಥವಾ ವಾಂತಿಗೆ ಸಂಬಂಧಿಸಿದೆಯೇ ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ.",
  hpiHintHeadache: "ತಲೆನೋವಿಗೆ, ಬೆಳಕು, ಶಬ್ದ ಅಥವಾ ಚಲನೆಯಿಂದ ಅದು ಹೆಚ್ಚಾಗುತ್ತದೆಯೇ, ಮತ್ತು ದೃಷ್ಟಿಯಲ್ಲಿ ಯಾವುದೇ ಬದಲಾವಣೆ ಇದೆಯೇ ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ.",
  pastTitle: "ಹಿಂದಿನ ಮತ್ತು ಪ್ರಸ್ತುತ ಇತಿಹಾಸ",
  pastSubtitle: "ರೋಗಿಗೆ ತಿಳಿದಿರುವ ಮಾಹಿತಿಯನ್ನು ನಮೂದಿಸಿ. ತಿಳಿಯದಿದ್ದರೆ ಖಾಲಿ ಬಿಡಿ.",
  pastMedical: "ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
  pastSurgical: "ಹಿಂದಿನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯ ಇತಿಹಾಸ",
  medications: "ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು",
  allergies: "ಅಲರ್ಜಿಗಳು",
  family: "ಕುಟುಂಬದ ಇತಿಹಾಸ",
  occupation: "ವೃತ್ತಿ",
  diet: "ಆಹಾರ",
  sleep: "ನಿದ್ರೆ",
  smoking: "ಧೂಮಪಾನ / ತಂಬಾಕು",
  alcohol: "ಮದ್ಯಪಾನ",
  reviewTitle: "ವ್ಯವಸ್ಥೆಗಳ ಪರಿಶೀಲನೆ ಮತ್ತು ಪರೀಕ್ಷೆಗಳು",
  reviewSubtitle: "ಇದು ರಚನಾತ್ಮಕ ಮಾಹಿತಿ ಸಂಗ್ರಹ; ಸ್ವಯಂಚಾಲಿತ ರೋಗನಿರ್ಣಯವಲ್ಲ.",
  ros: "ವ್ಯವಸ್ಥೆಗಳ ಪರಿಶೀಲನೆ",
  investigations: "ಹಿಂದಿನ ಪರೀಕ್ಷೆಗಳು",
  documentsTitle: "ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಸೇರಿಸಿ",
  documentsDescription: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್, ಲ್ಯಾಬ್ ವರದಿ ಅಥವಾ ಡಿಸ್ಚಾರ್ಜ್ ಸಾರಾಂಶವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ಪ್ರಸ್ತುತ AI ಡಾಕ್ಯುಮೆಂಟ್ ಪೈಪ್‌ಲೈನ್ ಲಭ್ಯವಿರುವ ಕ್ಲಿನಿಕಲ್ ಮಾಹಿತಿಯನ್ನು ಹೊರತೆಗೆಯುತ್ತದೆ.",
  analyze: "ದಾಖಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
  analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…",
  selectedSuffix: "ದಾಖಲೆ ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ.",
  aiContext: "AI ಮೂಲಕ ಪಡೆದ ಮಾಹಿತಿ",
  safetyScreen: "ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆ",
  safetyText: "ಸಂಭಾವ್ಯ ತುರ್ತು ಲಕ್ಷಣಗಳನ್ನು ಮಾನವ ಟ್ರಯಾಜ್‌ಗಾಗಿ ಗುರುತಿಸಲಾಗುತ್ತದೆ. ವ್ಯವಸ್ಥೆ ರೋಗನಿರ್ಣಯ ಅಥವಾ ಔಷಧ ನೀಡುವುದಿಲ್ಲ.",
  review: "ಹಿಸ್ಟರಿ ಪರಿಶೀಲಿಸಿ",
  reviewSubtitle2: "ವೈದ್ಯರ ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸುವ ಮೊದಲು ಡ್ರಾಫ್ಟ್ ಪರಿಶೀಲಿಸಿ.",
  submit: "ವೈದ್ಯರ ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ",
  submitting: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
  submitted: "ವೈದ್ಯರ ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
  complete: "ನಿಮ್ಮ ಇನ್‌ಟೇಕ್ ಅನ್ನು pending clinical record ಆಗಿ ಉಳಿಸಲಾಗಿದೆ.",
  completionNote: "ಪ್ರಸ್ತುತ ವೈದ್ಯರ ಪರಿಶೀಲನೆ ಪ್ರಕ್ರಿಯೆಯೇ ಅಂತಿಮ ಅಧಿಕಾರ. ಪರಿಶೀಲನೆಯವರೆಗೆ ಇದು trusted longitudinal ಮಾಹಿತಿಯಾಗುವುದಿಲ್ಲ.",
  openRecords: "ಹೆಲ್ತ್ ದಾಖಲೆಗಳನ್ನು ತೆರೆಯಿರಿ",
  backDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
  urgent: "ತುರ್ತು ಗಮನ ಅಗತ್ಯ",
  triageNote: "ಇದು ಟ್ರಯಾಜ್ ಎಸ್ಕಲೇಶನ್ ಸೂಚನೆ, ರೋಗನಿರ್ಣಯವಲ್ಲ.",
  voiceTouch: "ವಾಯ್ಸ್ + ಟಚ್",
  voiceTouchDescription: "ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಲು ಎರಡು ಮಾರ್ಗಗಳು",
  speakPrompt: "ನೀವು ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ ಉತ್ತರಿಸಬಹುದು.",
  redFlagEscalation: "ರೆಡ್-ಫ್ಲ್ಯಾಗ್ ಎಸ್ಕಲೇಶನ್",
  redFlagDescription: "ತುರ್ತು ಲಕ್ಷಣಗಳು ಸಾಮಾನ್ಯ ಇನ್‌ಟೇಕ್ ಅನ್ನು ನಿಲ್ಲಿಸಬಹುದು",
  redFlagBody: "JeevanLink ಸಂರಚಿತ ತುರ್ತು ಲಕ್ಷಣಗಳನ್ನು ಮಾನವ ಗಮನಕ್ಕಾಗಿ ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತದೆ. ಇದು ರೋಗನಿರ್ಣಯ ಅಥವಾ ಔಷಧ ನೀಡುವುದಿಲ್ಲ.",
  verificationGate: "ಪರಿಶೀಲನೆ ಗೇಟ್",
  verificationBody: "ಪ್ರತಿ ಇನ್‌ಟೇಕ್ PENDING ಆಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ. ದಾಖಲೆ trusted ಆಗುವ ಮೊದಲು ವೈದ್ಯರ ಪರಿಶೀಲನೆ ಅಂತಿಮ ಮೂಲವಾಗಿದೆ.",
  continue: "ಮುಂದುವರಿಸಿ",
  back: "ಹಿಂದೆ",
  speak: "ಮಾತನಾಡಿ",
  stop: "ನಿಲ್ಲಿಸಿ",
  listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ…",
  transcribing: "ಪಠ್ಯಕ್ಕೆ ಪರಿವರ್ತಿಸಲಾಗುತ್ತಿದೆ…",
  voiceUnavailable: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಲಭ್ಯವಿಲ್ಲ. ನೀವು ಉತ್ತರವನ್ನು ಟೈಪ್ ಮಾಡಬಹುದು.",
  voiceFailed: "ಧ್ವನಿ ಸೆರೆಹಿಡಿಯಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.",
  transcriptionFailed: "ಈ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಪಠ್ಯಕ್ಕೆ ಪರಿವರ್ತಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.",
  notReported: "ತಿಳಿಸಲಾಗಿಲ್ಲ",
  enterAnswer: "ನಿಮ್ಮ ಉತ್ತರವನ್ನು ನಮೂದಿಸಿ…",
  quickChestPain: "ಎದೆ ನೋವು",
  quickFever: "ಜ್ವರ",
  quickCough: "ಕೆಮ್ಮು",
  quickAbdominalPain: "ಹೊಟ್ಟೆ ನೋವು",
  quickHeadache: "ತಲೆನೋವು",
  quickOther: "ಇತರೆ",
  ayushContext: "ಆಯುಷ್ ಸಂದರ್ಭ",
  ayushIntro: "ವೈದ್ಯರ ನಿರ್ಧಾರವನ್ನು ಬದಲಿಸದೆ ಹೆಚ್ಚುವರಿ ಆಯುರ್ವೇದ ಮಾಹಿತಿ ದಾಖಲಿಸಿ.",
  noDocuments: "ಯಾವುದೇ ಹಿಂದಿನ ದಾಖಲೆ ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ.",
  microphone: "ಮೈಕ್ರೋಫೋನ್",
  consentClinicalHistory: "ಕ್ಲಿನಿಕಲ್ ಹಿಸ್ಟರಿ ಸಂಗ್ರಹಕ್ಕೆ ನಾನು ಒಪ್ಪುತ್ತೇನೆ.",
  consentDocumentProcessing: "ಸಂದರ್ಭ ಸಿದ್ಧಪಡಿಸಲು ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬಹುದು ಎಂದು ನಾನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ.",
  consentClinicianSharing: "ಈ ಡ್ರಾಫ್ಟ್ ಅನ್ನು ಚಿಕಿತ್ಸೆ ನೀಡುವ ವೈದ್ಯರೊಂದಿಗೆ ಪರಿಶೀಲನೆಗಾಗಿ ಹಂಚಿಕೊಳ್ಳಲು ನಾನು ಒಪ್ಪುತ್ತೇನೆ.",
  a11yAudioGuided: "ಆಡಿಯೋ ಗೈಡ್",
  a11yHighContrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
  a11yLargeText: "ದೊಡ್ಡ ಪಠ್ಯ",
  dashavidhaNotesPlaceholder: "ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)",
  prakritiTitle: "ಪ್ರಕೃತಿ (ದೇಹ ಸ್ವಭಾವ)",
  prakritiDescription: "ಜನನದಿಂದ ನಿರ್ಧರಿಸಲ್ಪಟ್ಟ ಮೂಲ ದೇಹ ಸ್ವಭಾವ. ಹತ್ತಿರದ ಶಾಸ್ತ್ರೀಯ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
  vikritiTitle: "ವಿಕೃತಿ (ಪ್ರಸ್ತುತ ಅಸಮತೋಲನ)",
  vikritiDescription: "ಮೂಲ ಸ್ವಭಾವದಿಂದ ಪ್ರಸ್ತುತ ವಿಚಲನ, ಯಾವುದಾದರೂ ಇದ್ದರೆ.",
  saraTitle: "ಸಾರ (ಅಂಗಾಂಶ ಗುಣಮಟ್ಟ)",
  saraDescription: "ದೇಹದ ಅಂಗಾಂಶಗಳ (ಧಾತುಗಳ) ಒಟ್ಟಾರೆ ಗುಣಮಟ್ಟ/ಸಾರ. ಸಂಬಂಧಿಸಿದ್ದರೆ ಯಾವ ಅಂಗಾಂಶ ಎಂದು ಗಮನಿಸಿ.",
  samhananaTitle: "ಸಂಹನನ (ದೇಹ ರಚನೆ)",
  samhananaDescription: "ದೇಹ ರಚನೆಯ ಬಿಗಿತ ಮತ್ತು ಬಲವರ್ಧನೆ.",
  pramanaTitle: "ಪ್ರಮಾಣ (ದೇಹ ಅನುಪಾತ)",
  pramanaDescription: "ಆದರ್ಶಕ್ಕೆ ಹೋಲಿಸಿದರೆ ದೇಹದ ಅಳತೆಗಳ ಅನುಪಾತ.",
  satmyaTitle: "ಸಾತ್ಮ್ಯ (ಹೊಂದಾಣಿಕೆ)",
  satmyaDescription: "ಆಹಾರ, ಹವಾಮಾನ ಮತ್ತು ಜೀವನಶೈಲಿಯಲ್ಲಿ ರೋಗಿ ಅಭ್ಯಾಸವಾಗಿರುವ ಮತ್ತು ಚೆನ್ನಾಗಿ ಹೊಂದಿಕೊಂಡಿರುವುದು.",
  sattvaTitle: "ಸತ್ವ (ಮಾನಸಿಕ ಶಕ್ತಿ)",
  sattvaDescription: "ಮಾನಸಿಕ ಶಕ್ತಿ ಮತ್ತು ಮಾನಸಿಕ ಸ್ಥಿತಿಸ್ಥಾಪಕತ್ವ.",
  aharaShaktiTitle: "ಆಹಾರ ಶಕ್ತಿ (ಜೀರ್ಣ ಸಾಮರ್ಥ್ಯ)",
  aharaShaktiDescription: "ಆಹಾರ ಸೇವಿಸುವ ಸಾಮರ್ಥ್ಯ ಮತ್ತು ಅದನ್ನು ಜೀರ್ಣಿಸಿಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯ — ಪ್ರತ್ಯೇಕವಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತದೆ.",
  abhyavaharanaShaktiLabel: "ಅಭ್ಯವಹರಣ ಶಕ್ತಿ (ಹಸಿವು / ಸೇವನೆ ಸಾಮರ್ಥ್ಯ)",
  jaranaShaktiLabel: "ಜರಣ ಶಕ್ತಿ (ಜೀರ್ಣ / ಚಯಾಪಚಯ ಸಾಮರ್ಥ್ಯ)",
  vyayamaShaktiTitle: "ವ್ಯಾಯಾಮ ಶಕ್ತಿ (ವ್ಯಾಯಾಮ ಸಾಮರ್ಥ್ಯ)",
  vyayamaShaktiDescription: "ದೈಹಿಕ ಸಹಿಷ್ಣುತೆ ಮತ್ತು ಶ್ರಮವನ್ನು ಸಹಿಸುವ ಸಾಮರ್ಥ್ಯ.",
  vayaTitle: "ವಯ (ವಯಸ್ಸಿನ ವರ್ಗ)",
  vayaDescription: "ಶಾಸ್ತ್ರೀಯ ವಯೋ-ವರ್ಗ, ಇದು ದೋಷ ಬಲ ಮತ್ತು ಚಿಕಿತ್ಸಾ ಯೋಜನೆಯ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ.",
  vayaYearsLabel: "ನಿಖರವಾದ ವಯಸ್ಸು ವರ್ಷಗಳಲ್ಲಿ (ಐಚ್ಛಿಕ)",
  aharaViharaPlaceholder: "ವಿಶಿಷ್ಟ ದೈನಂದಿನ ಆಹಾರ ಮತ್ತು ಜೀವನಶೈಲಿ ಮಾದರಿ…",
  nidanaPlaceholder: "ಇದಕ್ಕೆ ಏನು ಪ್ರಚೋದಿಸಿತು ಅಥವಾ ಕಾರಣವಾಯಿತು ಎಂದು ರೋಗಿ ನಂಬುತ್ತಾರೆ…",
  sampraptiPlaceholder: "ರೋಗ ಪ್ರಕ್ರಿಯೆಯ ಬಗ್ಗೆ ಕ್ಲಿನಿಕಲ್ ತರ್ಕ — ಸಾಮಾನ್ಯವಾಗಿ ಕ್ಲಿನಿಷಿಯನ್‌ನಿಂದ ಪೂರ್ಣಗೊಳಿಸಲಾಗುತ್ತದೆ ಅಥವಾ ಪರಿಷ್ಕರಿಸಲಾಗುತ್ತದೆ…",
  doshaVata: "ವಾತ",
  doshaPitta: "ಪಿತ್ತ",
  doshaKapha: "ಕಫ",
  doshaVataPitta: "ವಾತ-ಪಿತ್ತ",
  doshaPittaKapha: "ಪಿತ್ತ-ಕಫ",
  doshaVataKapha: "ವಾತ-ಕಫ",
  doshaSama: "ಸಮ (ತ್ರಿದೋಷಜ / ಸಮತೋಲಿತ)",
  vikritiNoImbalance: "ಗಮನಾರ್ಹ ಅಸಮತೋಲನ ಗಮನಿಸಲಾಗಿಲ್ಲ",
  gradePravara: "ಪ್ರವರ (ಹೆಚ್ಚು)",
  gradeMadhyama: "ಮಧ್ಯಮ (ಮಧ್ಯಮ)",
  gradeAvara: "ಅವರ (ಕಡಿಮೆ)",
  satmyaSama: "ಸಮ ಸಾತ್ಮ್ಯ — ಸಮತೋಲಿತ, ಚೆನ್ನಾಗಿ ಹೊಂದಿಕೊಂಡಿರುವ",
  satmyaVishama: "ವಿಷಮ ಸಾತ್ಮ್ಯ — ಅನಿಯಮಿತ, ಕಳಪೆ ಹೊಂದಾಣಿಕೆ",
  satmyaEkaRasa: "ಏಕ ರಸ ಸಾತ್ಮ್ಯ — ಒಂದು ಪ್ರಧಾನ ರುಚಿಗೆ ಅಭ್ಯಾಸವಾಗಿರುವ",
  vayaBala: "ಬಾಲ — ಬಾಲ್ಯ (ಸುಮಾರು 16 ವರ್ಷಗಳವರೆಗೆ)",
  vayaMadhyama: "ಮಧ್ಯಮ / ಯುವ — ವಯಸ್ಕ (16–70 ವರ್ಷಗಳು)",
  vayaVriddha: "ವೃದ್ಧ — ವೃದ್ಧಾಪ್ಯ (70+ ವರ್ಷಗಳು)",
  dashavidhaReviewTitle: "ದಶವಿಧ ಪರೀಕ್ಷಾ",
};

const ml: ClinicalIntakeText = {
  title: "കൺസൾട്ടേഷനു മുമ്പുള്ള നിങ്ങളുടെ ക്ലിനിക്കൽ ചരിത്രം.",
  subtitle: "ഇന്ന് നിങ്ങളെ ഇവിടെ എത്തിച്ച പ്രശ്നം JeevanLink-നോട് പറയൂ. സംസാരിക്കുകയോ ടാപ്പ് ചെയ്യുകയോ ചെയ്യാം.",
  consentTitle: "സമ്മതവും നിയന്ത്രണവും",
  consentText: "ക്ലിനീഷ്യൻ അവലോകനത്തിനുള്ള ക്ലിനിക്കൽ ചരിത്ര ഡ്രാഫ്റ്റ് തയ്യാറാക്കാൻ നിങ്ങളുടെ ഉത്തരങ്ങൾ ഉപയോഗിക്കും. ഈ ഉപകരണം രോഗനിർണയം നടത്തുകയോ മരുന്ന് നിർദേശിക്കുകയോ ചെയ്യില്ല.",
  listenExplanation: "വിശദീകരണം കേൾക്കുക",
  audioGuided: "ഓഡിയോ മാർഗനിർദ്ദേശമുള്ള സമ്മതം",
  voiceLanguage: "വോയ്സ് ഭാഷ",
  humanVerification: "മാനുഷിക പരിശോധന ആവശ്യമാണ്",
  patient: "രോഗി",
  preConsultation: "കൺസൾട്ടേഷനുമുമ്പുള്ള ക്ലിനിക്കൽ ഇൻടേക്ക്",
  step: "ഘട്ടം",
  of: "ൽ",
  historyMode: "ചരിത്രത്തിന്റെ തരം തിരഞ്ഞെടുക്കുക",
  general: "പൊതുവായ",
  generalDescription: "സ്റ്റാൻഡേർഡ് ക്ലിനിക്കൽ ചരിത്ര അഭിമുഖം",
  ayush: "ആയുഷ് / ആയുർവേദം",
  ayushDescription: "ദശവിധ + ആഹാര-വിഹാര വിവരങ്ങൾ",
  chiefComplaint: "ഇന്ന് നിങ്ങളെ ഇവിടെ എത്തിച്ച പ്രശ്നം എന്താണ്?",
  chiefComplaintSubtitle: "ആദ്യം രോഗിയുടെ സ്വന്തം വാക്കുകളിൽ പറയുക. അടുത്ത ഘട്ടത്തിൽ ചരിത്രം കൂടുതൽ വിശദമാക്കാം.",
  hpiTitle: "നിലവിലെ അസുഖത്തിന്റെ ചരിത്രം",
  hpiSubtitle: "ഈ ചോദ്യങ്ങൾ നിയന്ത്രിത ക്ലിനിക്കൽ ചരിത്ര ഘടന പിന്തുടരുന്നു. സംസാരിച്ചോ ടൈപ്പ് ചെയ്തോ മറുപടി നൽകാം.",
  onset: "എപ്പോൾ തുടങ്ങി?",
  duration: "എത്ര നാളായി ഉണ്ട്?",
  character: "ഇത് എങ്ങനെ വിവരിക്കും?",
  location: "ഇത് എവിടെയാണ്?",
  radiation: "മറ്റെവിടെയെങ്കിലും പടരുന്നുണ്ടോ?",
  severity: "എത്രത്തോളം തീവ്രമാണ്?",
  aggravating: "എന്താണ് ഇത് വഷളാക്കുന്നത്?",
  relieving: "എന്താണ് ഇത് കുറയ്ക്കുന്നത്?",
  associatedSymptoms: "ഇതിനോടൊപ്പം മറ്റ് ലക്ഷണങ്ങളുണ്ടോ?",
  hpiHintChestPain: "നെഞ്ചുവേദനയ്ക്ക്, അത് നിങ്ങളുടെ കൈ, താടിയെല്ല്, കഴുത്ത് അല്ലെങ്കിൽ പുറത്തേക്ക് വ്യാപിക്കുന്നുണ്ടോ, കൂടാതെ വിയർപ്പ് അല്ലെങ്കിൽ ശ്വാസതടസ്സം ഉണ്ടോ എന്നും കുറിക്കുക.",
  hpiHintFever: "പനിക്ക്, അത് തുടർച്ചയായതാണോ അതോ വന്നുപോകുന്നതാണോ, അളന്നിട്ടുണ്ടെങ്കിൽ ഏറ്റവും ഉയർന്ന താപനില എത്രയായിരുന്നു എന്നും കുറിക്കുക.",
  hpiHintCough: "ചുമയ്ക്ക്, അത് വരണ്ടതാണോ അതോ കഫത്തോടെയാണോ, കഫമുണ്ടെങ്കിൽ അതിന്റെ നിറം എന്താണെന്നും കുറിക്കുക.",
  hpiHintAbdominalPain: "വയറുവേദനയ്ക്ക്, അത് ഭക്ഷണം, മലവിസർജ്ജനം, അല്ലെങ്കിൽ ഛർദ്ദിയുമായി ബന്ധപ്പെട്ടതാണോ എന്നും കുറിക്കുക.",
  hpiHintHeadache: "തലവേദനയ്ക്ക്, വെളിച്ചം, ശബ്ദം അല്ലെങ്കിൽ ചലനം അതിനെ വഷളാക്കുന്നുണ്ടോ, കാഴ്ചയിൽ എന്തെങ്കിലും മാറ്റമുണ്ടോ എന്നും കുറിക്കുക.",
  pastTitle: "മുൻകാലവും നിലവിലെ ചരിത്രവും",
  pastSubtitle: "രോഗിക്ക് അറിയാവുന്ന വിവരങ്ങൾ നൽകുക. അറിയാത്തത് ശൂന്യമായി വിടുക.",
  pastMedical: "മുൻകാല മെഡിക്കൽ ചരിത്രം",
  pastSurgical: "മുൻകാല ശസ്ത്രക്രിയാ ചരിത്രം",
  medications: "നിലവിലെ മരുന്നുകൾ",
  allergies: "അലർജികൾ",
  family: "കുടുംബ ചരിത്രം",
  occupation: "തൊഴിൽ",
  diet: "ഭക്ഷണക്രമം",
  sleep: "ഉറക്കം",
  smoking: "പുകവലി / പുകയില",
  alcohol: "മദ്യം",
  reviewTitle: "സിസ്റ്റം റിവ്യൂ & പരിശോധനകൾ",
  reviewSubtitle: "ഇത് ഘടനാപരമായ വിവരശേഖരണമാണ്; സ്വയമേവ രോഗനിർണയം അല്ല.",
  ros: "സിസ്റ്റം റിവ്യൂ",
  investigations: "മുൻപരിശോധനകൾ",
  documentsTitle: "മുൻകാല മെഡിക്കൽ രേഖകൾ ചേർക്കുക",
  documentsDescription: "പ്രിസ്ക്രിപ്ഷൻ, ലാബ് റിപ്പോർട്ട് അല്ലെങ്കിൽ ഡിസ്ചാർജ് സംഗ്രഹം അപ്‌ലോഡ് ചെയ്യുക. നിലവിലെ AI ഡോക്യുമെന്റ് പൈപ്പ്‌ലൈൻ ലഭ്യമായ ക്ലിനിക്കൽ വിവരങ്ങൾ പുറത്തെടുക്കും.",
  analyze: "രേഖകൾ വിശകലനം ചെയ്യുക",
  analyzing: "വിശകലനം ചെയ്യുന്നു…",
  selectedSuffix: "രേഖ തിരഞ്ഞെടുത്തു.",
  aiContext: "AI പുറത്തെടുത്ത വിവരം",
  safetyScreen: "സുരക്ഷാ പരിശോധന",
  safetyText: "സാധ്യമായ അടിയന്തര ലക്ഷണങ്ങൾ മനുഷ്യ ട്രയാജിനായി ഫ്ലാഗ് ചെയ്യും. സിസ്റ്റം രോഗനിർണയം നടത്തുകയോ മരുന്ന് നിർദേശിക്കുകയോ ചെയ്യില്ല.",
  review: "ചരിത്രം അവലോകനം ചെയ്യുക",
  reviewSubtitle2: "ക്ലിനീഷ്യൻ പരിശോധനയ്ക്ക് അയയ്ക്കുന്നതിന് മുമ്പ് ഡ്രാഫ്റ്റ് പരിശോധിക്കുക.",
  submit: "ക്ലിനീഷ്യൻ പരിശോധനയ്ക്ക് അയയ്ക്കുക",
  submitting: "അയയ്ക്കുന്നു…",
  submitted: "ക്ലിനീഷ്യൻ പരിശോധനയ്ക്ക് അയച്ചു",
  complete: "നിങ്ങളുടെ ഇൻടേക്ക് pending clinical record ആയി സംരക്ഷിച്ചു.",
  completionNote: "നിലവിലെ ക്ലിനീഷ്യൻ പരിശോധനാ പ്രക്രിയയാണ് അന്തിമ അധികാരം. പരിശോധന വരെ ഇത് വിശ്വസനീയമായ longitudinal വിവരമാകില്ല.",
  openRecords: "ഹെൽത്ത് റെക്കോർഡുകൾ തുറക്കുക",
  backDashboard: "ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക",
  urgent: "അടിയന്തര ശ്രദ്ധ ഫ്ലാഗ് ചെയ്തു",
  triageNote: "ഇത് ട്രയാജ് എസ്കലേഷൻ സിഗ്നലാണ്, രോഗനിർണയം അല്ല.",
  voiceTouch: "വോയ്സ് + ടച്ച്",
  voiceTouchDescription: "ഓരോ ചോദ്യത്തിനും മറുപടി നൽകാൻ രണ്ട് വഴികൾ",
  speakPrompt: "സംസാരിച്ചോ ടൈപ്പ് ചെയ്തോ മറുപടി നൽകാം.",
  redFlagEscalation: "റെഡ്-ഫ്ലാഗ് എസ്കലേഷൻ",
  redFlagDescription: "അടിയന്തര ലക്ഷണങ്ങൾ സാധാരണ ഇൻടേക്ക് നിർത്താം",
  redFlagBody: "JeevanLink ക്രമീകരിച്ച അടിയന്തര ലക്ഷണങ്ങൾ മനുഷ്യ ശ്രദ്ധയ്ക്കായി ഫ്ലാഗ് ചെയ്യുന്നു. ഇത് രോഗനിർണയമോ മരുന്ന് നിർദേശമോ അല്ല.",
  verificationGate: "പരിശോധന ഗേറ്റ്",
  verificationBody: "ഓരോ ഇൻടേക്കും PENDING ആയി സംരക്ഷിക്കും. രേഖ trusted ആകുന്നതിന് മുമ്പ് ക്ലിനീഷ്യൻ പരിശോധനയാണ് അന്തിമ ഉറവിടം.",
  continue: "തുടരുക",
  back: "പിന്നോട്ട്",
  speak: "സംസാരിക്കുക",
  stop: "നിർത്തുക",
  listening: "കേൾക്കുന്നു…",
  transcribing: "ടെക്സ്റ്റാക്കി മാറ്റുന്നു…",
  voiceUnavailable: "ഈ ബ്രൗസറിൽ വോയ്സ് റെക്കോർഡിംഗ് ലഭ്യമല്ല. നിങ്ങൾക്ക് മറുപടി ടൈപ്പ് ചെയ്യാം.",
  voiceFailed: "വോയ്സ് ക്യാപ്ചർ പൂർത്തിയാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.",
  transcriptionFailed: "ഈ റെക്കോർഡിംഗ് ടെക്സ്റ്റാക്കി മാറ്റാനായില്ല. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.",
  notReported: "അറിയിച്ചിട്ടില്ല",
  enterAnswer: "നിങ്ങളുടെ മറുപടി നൽകുക…",
  quickChestPain: "നെഞ്ചുവേദന",
  quickFever: "പനി",
  quickCough: "ചുമ",
  quickAbdominalPain: "വയറുവേദന",
  quickHeadache: "തലവേദന",
  quickOther: "മറ്റുള്ളവ",
  ayushContext: "ആയുഷ് പശ്ചാത്തലം",
  ayushIntro: "ക്ലിനീഷ്യന്റെ തീരുമാനം മാറ്റാതെ അധിക ആയുർവേദ വിവരങ്ങൾ രേഖപ്പെടുത്തുക.",
  noDocuments: "മുൻ രേഖകളൊന്നും തിരഞ്ഞെടുത്തിട്ടില്ല.",
  microphone: "മൈക്രോഫോൺ",
  consentClinicalHistory: "ക്ലിനിക്കൽ ചരിത്ര ശേഖരണത്തിന് ഞാൻ സമ്മതിക്കുന്നു.",
  consentDocumentProcessing: "പശ്ചാത്തലം തയ്യാറാക്കാൻ മെഡിക്കൽ രേഖകൾ പ്രോസസ്സ് ചെയ്യാം എന്ന് ഞാൻ മനസ്സിലാക്കുന്നു.",
  consentClinicianSharing: "ഈ ഡ്രാഫ്റ്റ് ചികിത്സിക്കുന്ന ക്ലിനീഷ്യനുമായി അവലോകനത്തിനായി പങ്കിടാൻ ഞാൻ സമ്മതിക്കുന്നു.",
  a11yAudioGuided: "ഓഡിയോ ഗൈഡ്",
  a11yHighContrast: "ഉയർന്ന കോൺട്രാസ്റ്റ്",
  a11yLargeText: "വലിയ ടെക്സ്റ്റ്",
  dashavidhaNotesPlaceholder: "അധിക കുറിപ്പുകൾ (ഐച്ഛികം)",
  prakritiTitle: "പ്രകൃതി (ശരീര ഘടന)",
  prakritiDescription: "ജനനം മുതൽ നിർണ്ണയിക്കപ്പെട്ട അടിസ്ഥാന ശരീര ഘടന. ഏറ്റവും അടുത്ത ക്ലാസിക്കൽ തരം തിരഞ്ഞെടുക്കുക.",
  vikritiTitle: "വികൃതി (നിലവിലെ അസന്തുലിതാവസ്ഥ)",
  vikritiDescription: "അടിസ്ഥാന ഘടനയിൽ നിന്നുള്ള നിലവിലെ വ്യതിയാനം, ഉണ്ടെങ്കിൽ.",
  saraTitle: "സാര (കോശ ഗുണനിലവാരം)",
  saraDescription: "ശരീര കോശങ്ങളുടെ (ധാതുക്കളുടെ) മൊത്തത്തിലുള്ള ഗുണനിലവാരം/സാരാംശം. പ്രസക്തമെങ്കിൽ ഏത് കോശമെന്ന് ശ്രദ്ധിക്കുക.",
  samhananaTitle: "സംഹനന (ശരീര നിർമ്മിതി)",
  samhananaDescription: "ശരീര നിർമ്മിതിയുടെ ഇറുക്കവും ഏകീകരണവും.",
  pramanaTitle: "പ്രമാണ (ശരീര അനുപാതം)",
  pramanaDescription: "ആദർശവുമായി താരതമ്യപ്പെടുത്തുമ്പോൾ ശരീര അളവുകളുടെ അനുപാതം.",
  satmyaTitle: "സാത്മ്യ (അനുയോജ്യത)",
  satmyaDescription: "ഭക്ഷണം, കാലാവസ്ഥ, ജീവിതശൈലി എന്നിവയിൽ രോഗി ശീലിച്ചതും നന്നായി പൊരുത്തപ്പെട്ടതും.",
  sattvaTitle: "സത്വ (മാനസിക ശക്തി)",
  sattvaDescription: "മാനസിക ശക്തിയും മാനസിക പ്രതിരോധശേഷിയും.",
  aharaShaktiTitle: "ആഹാര ശക്തി (ദഹന ശേഷി)",
  aharaShaktiDescription: "ഭക്ഷണം കഴിക്കാനുള്ള ശേഷിയും അത് ദഹിപ്പിക്കാനുള്ള ശേഷിയും — പ്രത്യേകം വിലയിരുത്തുന്നു.",
  abhyavaharanaShaktiLabel: "അഭ്യവഹരണ ശക്തി (വിശപ്പ് / ഉപഭോഗ ശേഷി)",
  jaranaShaktiLabel: "ജരണ ശക്തി (ദഹന / ഉപാപചയ ശേഷി)",
  vyayamaShaktiTitle: "വ്യായാമ ശക്തി (വ്യായാമ ശേഷി)",
  vyayamaShaktiDescription: "ശാരീരിക സഹനശക്തിയും അധ്വാനം സഹിക്കാനുള്ള ശേഷിയും.",
  vayaTitle: "വയ (പ്രായ വിഭാഗം)",
  vayaDescription: "ദോഷ ശക്തിയെയും ചികിത്സാ ആസൂത്രണത്തെയും ബാധിക്കുന്ന ക്ലാസിക്കൽ പ്രായ-വിഭാഗം.",
  vayaYearsLabel: "കൃത്യമായ പ്രായം വർഷങ്ങളിൽ (ഐച്ഛികം)",
  aharaViharaPlaceholder: "സാധാരണ ദൈനംദിന ഭക്ഷണക്രമവും ജീവിതശൈലി രീതിയും…",
  nidanaPlaceholder: "ഇതിന് കാരണമായത് എന്താണെന്ന് രോഗി വിശ്വസിക്കുന്നു…",
  sampraptiPlaceholder: "രോഗ പ്രക്രിയയെക്കുറിച്ചുള്ള ക്ലിനിക്കൽ യുക്തി — സാധാരണയായി ക്ലിനിഷ്യൻ പൂർത്തിയാക്കുകയോ പരിഷ്കരിക്കുകയോ ചെയ്യുന്നു…",
  doshaVata: "വാത",
  doshaPitta: "പിത്ത",
  doshaKapha: "കഫ",
  doshaVataPitta: "വാത-പിത്ത",
  doshaPittaKapha: "പിത്ത-കഫ",
  doshaVataKapha: "വാത-കഫ",
  doshaSama: "സമ (ത്രിദോഷജ / സന്തുലിതം)",
  vikritiNoImbalance: "കാര്യമായ അസന്തുലിതാവസ്ഥ ശ്രദ്ധയിൽപ്പെട്ടിട്ടില്ല",
  gradePravara: "പ്രവര (ഉയർന്നത്)",
  gradeMadhyama: "മധ്യമ (മിതം)",
  gradeAvara: "അവര (താഴ്ന്നത്)",
  satmyaSama: "സമ സാത്മ്യ — സന്തുലിതം, നന്നായി പൊരുത്തപ്പെട്ടത്",
  satmyaVishama: "വിഷമ സാത്മ്യ — ക്രമരഹിതം, മോശം പൊരുത്തപ്പെടൽ",
  satmyaEkaRasa: "ഏക രസ സാത്മ്യ — ഒരു പ്രധാന രുചിയോട് ശീലിച്ചത്",
  vayaBala: "ബാല — ബാല്യം (ഏകദേശം 16 വയസ്സ് വരെ)",
  vayaMadhyama: "മധ്യമ / യുവ — മുതിർന്നവർ (16–70 വയസ്സ്)",
  vayaVriddha: "വൃദ്ധ — വാർദ്ധക്യം (70+ വയസ്സ്)",
  dashavidhaReviewTitle: "ദശവിധ പരീക്ഷ",
};

const pa: ClinicalIntakeText = {
  title: "ਸਲਾਹ ਤੋਂ ਪਹਿਲਾਂ ਤੁਹਾਡਾ ਕਲੀਨੀਕਲ ਇਤਿਹਾਸ।",
  subtitle: "ਅੱਜ ਤੁਹਾਨੂੰ ਇੱਥੇ ਲੈ ਕੇ ਆਈ ਸਮੱਸਿਆ JeevanLink ਨੂੰ ਦੱਸੋ। ਬੋਲੋ ਜਾਂ ਟੈਪ ਕਰੋ।",
  consentTitle: "ਸਹਿਮਤੀ ਅਤੇ ਨਿਯੰਤਰਣ",
  consentText: "ਤੁਹਾਡੇ ਜਵਾਬ ਕਲੀਨੀਸ਼ੀਅਨ ਦੀ ਸਮੀਖਿਆ ਲਈ ਕਲੀਨੀਕਲ ਇਤਿਹਾਸ ਦਾ ਡਰਾਫਟ ਬਣਾਉਣ ਲਈ ਵਰਤੇ ਜਾਣਗੇ। ਇਹ ਸਾਧਨ ਨਿਦਾਨ ਜਾਂ ਦਵਾਈ ਨਹੀਂ ਦਿੰਦਾ।",
  listenExplanation: "ਵਿਆਖਿਆ ਸੁਣੋ",
  audioGuided: "ਆਡੀਓ ਮਾਰਗਦਰਸ਼ਿਤ ਸਹਿਮਤੀ",
  voiceLanguage: "ਆਵਾਜ਼ ਦੀ ਭਾਸ਼ਾ",
  humanVerification: "ਮਨੁੱਖੀ ਤਸਦੀਕ ਲਾਜ਼ਮੀ ਹੈ",
  patient: "ਮਰੀਜ਼",
  preConsultation: "ਸਲਾਹ ਤੋਂ ਪਹਿਲਾਂ ਕਲੀਨੀਕਲ ਇਨਟੇਕ",
  step: "ਕਦਮ",
  of: "ਵਿੱਚੋਂ",
  historyMode: "ਇਤਿਹਾਸ ਦੀ ਕਿਸਮ ਚੁਣੋ",
  general: "ਸਧਾਰਨ",
  generalDescription: "ਮਿਆਰੀ ਕਲੀਨੀਕਲ ਇਤਿਹਾਸ ਇੰਟਰਵਿਊ",
  ayush: "ਆਯੁਸ਼ / ਆਯੁਰਵੇਦ",
  ayushDescription: "ਦਸ਼ਵਿਧ + ਆਹਾਰ-ਵਿਹਾਰ ਜਾਣਕਾਰੀ",
  chiefComplaint: "ਅੱਜ ਤੁਹਾਨੂੰ ਕਿਹੜੀ ਸਮੱਸਿਆ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
  chiefComplaintSubtitle: "ਪਹਿਲਾਂ ਮਰੀਜ਼ ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੇ। ਅੱਗੇ ਇਤਿਹਾਸ ਹੋਰ ਸਪਸ਼ਟ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।",
  hpiTitle: "ਮੌਜੂਦਾ ਬਿਮਾਰੀ ਦਾ ਇਤਿਹਾਸ",
  hpiSubtitle: "ਇਹ ਸਵਾਲ ਨਿਯੰਤਰਿਤ ਕਲੀਨੀਕਲ ਇਤਿਹਾਸ ਢਾਂਚੇ ਦੀ ਪਾਲਣਾ ਕਰਦੇ ਹਨ। ਮਰੀਜ਼ ਬੋਲ ਜਾਂ ਟਾਈਪ ਕਰ ਸਕਦਾ ਹੈ।",
  onset: "ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਇਆ?",
  duration: "ਕਿੰਨੇ ਸਮੇਂ ਤੋਂ ਹੈ?",
  character: "ਤੁਸੀਂ ਇਸਨੂੰ ਕਿਵੇਂ ਵਰਣਨ ਕਰੋਗੇ?",
  location: "ਇਹ ਕਿੱਥੇ ਹੈ?",
  radiation: "ਕੀ ਇਹ ਹੋਰ ਕਿਤੇ ਫੈਲਦਾ ਹੈ?",
  severity: "ਕਿੰਨਾ ਗੰਭੀਰ ਹੈ?",
  aggravating: "ਇਸਨੂੰ ਕੀ ਵਧਾਉਂਦਾ ਹੈ?",
  relieving: "ਇਸਨੂੰ ਕੀ ਘਟਾਉਂਦਾ ਹੈ?",
  associatedSymptoms: "ਕੀ ਇਸਦੇ ਨਾਲ ਹੋਰ ਲੱਛਣ ਹਨ?",
  hpiHintChestPain: "ਛਾਤੀ ਦੇ ਦਰਦ ਲਈ, ਇਹ ਵੀ ਦੱਸੋ ਕਿ ਕੀ ਇਹ ਤੁਹਾਡੀ ਬਾਂਹ, ਜਬਾੜੇ, ਗਰਦਨ ਜਾਂ ਪਿੱਠ ਵੱਲ ਫੈਲਦਾ ਹੈ, ਅਤੇ ਕੀ ਇਸਦੇ ਨਾਲ ਪਸੀਨਾ ਜਾਂ ਸਾਹ ਲੈਣ ਵਿੱਚ ਤਕਲੀਫ਼ ਹੁੰਦੀ ਹੈ।",
  hpiHintFever: "ਬੁਖਾਰ ਲਈ, ਇਹ ਵੀ ਦੱਸੋ ਕਿ ਇਹ ਲਗਾਤਾਰ ਹੈ ਜਾਂ ਆਉਂਦਾ-ਜਾਂਦਾ ਹੈ, ਅਤੇ ਜੇ ਮਾਪਿਆ ਹੋਵੇ ਤਾਂ ਸਭ ਤੋਂ ਵੱਧ ਤਾਪਮਾਨ ਕੀ ਸੀ।",
  hpiHintCough: "ਖੰਘ ਲਈ, ਇਹ ਵੀ ਦੱਸੋ ਕਿ ਇਹ ਸੁੱਕੀ ਹੈ ਜਾਂ ਕਫ਼ ਵਾਲੀ, ਅਤੇ ਜੇ ਕਫ਼ ਹੈ ਤਾਂ ਇਸਦਾ ਰੰਗ ਕੀ ਹੈ।",
  hpiHintAbdominalPain: "ਪੇਟ ਦਰਦ ਲਈ, ਇਹ ਵੀ ਦੱਸੋ ਕਿ ਕੀ ਇਸਦਾ ਸਬੰਧ ਖਾਣ, ਟੱਟੀ, ਜਾਂ ਉਲਟੀ ਨਾਲ ਹੈ।",
  hpiHintHeadache: "ਸਿਰ ਦਰਦ ਲਈ, ਇਹ ਵੀ ਦੱਸੋ ਕਿ ਕੀ ਰੌਸ਼ਨੀ, ਆਵਾਜ਼ ਜਾਂ ਹਿੱਲਣ ਨਾਲ ਇਹ ਵਧਦਾ ਹੈ, ਅਤੇ ਕੀ ਨਜ਼ਰ ਵਿੱਚ ਕੋਈ ਬਦਲਾਅ ਹੈ।",
  pastTitle: "ਪਿਛਲਾ ਅਤੇ ਮੌਜੂਦਾ ਇਤਿਹਾਸ",
  pastSubtitle: "ਮਰੀਜ਼ ਨੂੰ ਜੋ ਜਾਣਕਾਰੀ ਪਤਾ ਹੈ ਉਹ ਦਰਜ ਕਰੋ। ਨਾ ਪਤਾ ਹੋਵੇ ਤਾਂ ਖਾਲੀ ਛੱਡੋ।",
  pastMedical: "ਪਿਛਲਾ ਮੈਡੀਕਲ ਇਤਿਹਾਸ",
  pastSurgical: "ਪਿਛਲੀ ਸਰਜਰੀ ਦਾ ਇਤਿਹਾਸ",
  medications: "ਮੌਜੂਦਾ ਦਵਾਈਆਂ",
  allergies: "ਐਲਰਜੀਆਂ",
  family: "ਪਰਿਵਾਰਕ ਇਤਿਹਾਸ",
  occupation: "ਪੇਸ਼ਾ",
  diet: "ਖੁਰਾਕ",
  sleep: "ਨੀਂਦ",
  smoking: "ਸਿਗਰਟ / ਤੰਬਾਕੂ",
  alcohol: "ਸ਼ਰਾਬ",
  reviewTitle: "ਸਿਸਟਮ ਰਿਵਿਊ ਅਤੇ ਜਾਂਚਾਂ",
  reviewSubtitle: "ਇਹ ਢਾਂਚਾਬੱਧ ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਕਰਨਾ ਹੈ; ਸਵੈਚਾਲਿਤ ਨਿਦਾਨ ਨਹੀਂ।",
  ros: "ਸਿਸਟਮ ਰਿਵਿਊ",
  investigations: "ਪਿਛਲੀਆਂ ਜਾਂਚਾਂ",
  documentsTitle: "ਪਿਛਲੇ ਮੈਡੀਕਲ ਦਸਤਾਵੇਜ਼ ਜੋੜੋ",
  documentsDescription: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ, ਲੈਬ ਰਿਪੋਰਟ ਜਾਂ ਡਿਸਚਾਰਜ ਸੰਖੇਪ ਅਪਲੋਡ ਕਰੋ। ਮੌਜੂਦਾ AI ਦਸਤਾਵੇਜ਼ ਪਾਈਪਲਾਈਨ ਉਪਲਬਧ ਕਲੀਨੀਕਲ ਜਾਣਕਾਰੀ ਕੱਢੇਗੀ।",
  analyze: "ਦਸਤਾਵੇਜ਼ਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
  analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…",
  selectedSuffix: "ਦਸਤਾਵੇਜ਼ ਚੁਣੇ ਗਏ ਹਨ।",
  aiContext: "AI ਤੋਂ ਪ੍ਰਾਪਤ ਸੰਦਰਭ",
  safetyScreen: "ਸੁਰੱਖਿਆ ਜਾਂਚ",
  safetyText: "ਸੰਭਾਵਿਤ ਐਮਰਜੈਂਸੀ ਲੱਛਣਾਂ ਨੂੰ ਮਨੁੱਖੀ ਟ੍ਰਾਇਜ ਲਈ ਫਲੈਗ ਕੀਤਾ ਜਾਵੇਗਾ। ਸਿਸਟਮ ਨਿਦਾਨ ਜਾਂ ਦਵਾਈ ਨਹੀਂ ਦੇਵੇਗਾ।",
  review: "ਇਤਿਹਾਸ ਦੀ ਸਮੀਖਿਆ",
  reviewSubtitle2: "ਕਲੀਨੀਸ਼ੀਅਨ ਸਮੀਖਿਆ ਲਈ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਡਰਾਫਟ ਜਾਂਚੋ।",
  submit: "ਕਲੀਨੀਸ਼ੀਅਨ ਸਮੀਖਿਆ ਲਈ ਭੇਜੋ",
  submitting: "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…",
  submitted: "ਕਲੀਨੀਸ਼ੀਅਨ ਤਸਦੀਕ ਲਈ ਭੇਜਿਆ ਗਿਆ",
  complete: "ਤੁਹਾਡਾ ਇਨਟੇਕ ਪੈਂਡਿੰਗ ਕਲੀਨੀਕਲ ਰਿਕਾਰਡ ਵਜੋਂ ਸੇਵ ਹੋ ਗਿਆ ਹੈ।",
  completionNote: "ਮੌਜੂਦਾ ਕਲੀਨੀਸ਼ੀਅਨ ਤਸਦੀਕ ਪ੍ਰਕਿਰਿਆ ਅੰਤਿਮ ਅਧਿਕਾਰ ਹੈ। ਤਸਦੀਕ ਹੋਣ ਤੱਕ ਇਹ trusted longitudinal ਜਾਣਕਾਰੀ ਨਹੀਂ ਬਣੇਗੀ।",
  openRecords: "ਹੈਲਥ ਰਿਕਾਰਡ ਖੋਲ੍ਹੋ",
  backDashboard: "ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ ਜਾਓ",
  urgent: "ਤੁਰੰਤ ਧਿਆਨ ਲੋੜੀਂਦਾ",
  triageNote: "ਇਹ ਟ੍ਰਾਇਜ ਐਸਕਲੇਸ਼ਨ ਸੰਕੇਤ ਹੈ, ਨਿਦਾਨ ਨਹੀਂ।",
  voiceTouch: "ਆਵਾਜ਼ + ਟੱਚ",
  voiceTouchDescription: "ਹਰ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦੇਣ ਦੇ ਦੋ ਤਰੀਕੇ",
  speakPrompt: "ਤੁਸੀਂ ਬੋਲ ਕੇ ਜਾਂ ਟਾਈਪ ਕਰਕੇ ਜਵਾਬ ਦੇ ਸਕਦੇ ਹੋ।",
  redFlagEscalation: "ਰੈੱਡ-ਫਲੈਗ ਐਸਕਲੇਸ਼ਨ",
  redFlagDescription: "ਤੁਰੰਤ ਲੱਛਣ ਆਮ ਇਨਟੇਕ ਨੂੰ ਰੋਕ ਸਕਦੇ ਹਨ",
  redFlagBody: "JeevanLink ਨਿਰਧਾਰਤ ਤੁਰੰਤ ਲੱਛਣਾਂ ਨੂੰ ਮਨੁੱਖੀ ਧਿਆਨ ਲਈ ਫਲੈਗ ਕਰਦਾ ਹੈ। ਇਹ ਨਿਦਾਨ ਜਾਂ ਦਵਾਈ ਨਹੀਂ ਦਿੰਦਾ।",
  verificationGate: "ਤਸਦੀਕ ਗੇਟ",
  verificationBody: "ਹਰ ਇਨਟੇਕ PENDING ਵਜੋਂ ਸੇਵ ਹੁੰਦਾ ਹੈ। ਰਿਕਾਰਡ trusted ਬਣਨ ਤੋਂ ਪਹਿਲਾਂ ਕਲੀਨੀਸ਼ੀਅਨ ਦੀ ਤਸਦੀਕ ਅੰਤਿਮ ਸਰੋਤ ਹੈ।",
  continue: "ਜਾਰੀ ਰੱਖੋ",
  back: "ਪਿੱਛੇ",
  speak: "ਬੋਲੋ",
  stop: "ਰੋਕੋ",
  listening: "ਸੁਣ ਰਹੇ ਹਾਂ…",
  transcribing: "ਟੈਕਸਟ ਵਿੱਚ ਬਦਲ ਰਹੇ ਹਾਂ…",
  voiceUnavailable: "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਵੌਇਸ ਰਿਕਾਰਡਿੰਗ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਤੁਸੀਂ ਜਵਾਬ ਟਾਈਪ ਕਰ ਸਕਦੇ ਹੋ।",
  voiceFailed: "ਵੌਇਸ ਕੈਪਚਰ ਪੂਰਾ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਟਾਈਪ ਕਰੋ।",
  transcriptionFailed: "ਇਸ ਰਿਕਾਰਡਿੰਗ ਨੂੰ ਟੈਕਸਟ ਵਿੱਚ ਨਹੀਂ ਬਦਲ ਸਕੇ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਟਾਈਪ ਕਰੋ।",
  notReported: "ਦੱਸਿਆ ਨਹੀਂ ਗਿਆ",
  enterAnswer: "ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ…",
  quickChestPain: "ਛਾਤੀ ਵਿੱਚ ਦਰਦ",
  quickFever: "ਬੁਖਾਰ",
  quickCough: "ਖੰਘ",
  quickAbdominalPain: "ਪੇਟ ਦਰਦ",
  quickHeadache: "ਸਿਰ ਦਰਦ",
  quickOther: "ਹੋਰ",
  ayushContext: "ਆਯੁਸ਼ ਸੰਦਰਭ",
  ayushIntro: "ਕਲੀਨੀਸ਼ੀਅਨ ਦੇ ਫੈਸਲੇ ਨੂੰ ਬਦਲੇ ਬਿਨਾਂ ਵਾਧੂ ਆਯੁਰਵੇਦਿਕ ਸੰਦਰਭ ਦਰਜ ਕਰੋ।",
  noDocuments: "ਕੋਈ ਪਿਛਲੇ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਚੁਣੇ ਗਏ।",
  microphone: "ਮਾਈਕ੍ਰੋਫੋਨ",
  consentClinicalHistory: "ਮੈਂ ਕਲੀਨੀਕਲ ਹਿਸਟਰੀ ਕੈਪਚਰ ਲਈ ਸਹਿਮਤ ਹਾਂ।",
  consentDocumentProcessing: "ਮੈਂ ਸਮਝਦਾ/ਸਮਝਦੀ ਹਾਂ ਕਿ ਸੰਦਰਭ ਤਿਆਰ ਕਰਨ ਲਈ ਮੈਡੀਕਲ ਦਸਤਾਵੇਜ਼ ਪ੍ਰੋਸੈਸ ਕੀਤੇ ਜਾ ਸਕਦੇ ਹਨ।",
  consentClinicianSharing: "ਮੈਂ ਇਸ ਡਰਾਫਟ ਨੂੰ ਇਲਾਜ ਕਰ ਰਹੇ ਕਲੀਨੀਸ਼ੀਅਨ ਨਾਲ ਸਮੀਖਿਆ ਲਈ ਸਾਂਝਾ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹਾਂ।",
  a11yAudioGuided: "ਆਡੀਓ ਗਾਈਡ",
  a11yHighContrast: "ਉੱਚ ਕੰਟ੍ਰਾਸਟ",
  a11yLargeText: "ਵੱਡਾ ਟੈਕਸਟ",
  dashavidhaNotesPlaceholder: "ਵਾਧੂ ਨੋਟਸ (ਵਿਕਲਪਿਕ)",
  prakritiTitle: "ਪ੍ਰਕ੍ਰਿਤੀ (ਸਰੀਰਕ ਬਣਤਰ)",
  prakritiDescription: "ਜਨਮ ਤੋਂ ਨਿਰਧਾਰਿਤ ਮੂਲ ਸਰੀਰਕ ਬਣਤਰ। ਸਭ ਤੋਂ ਨਜ਼ਦੀਕੀ ਸ਼ਾਸਤਰੀ ਕਿਸਮ ਚੁਣੋ।",
  vikritiTitle: "ਵਿਕ੍ਰਿਤੀ (ਮੌਜੂਦਾ ਅਸੰਤੁਲਨ)",
  vikritiDescription: "ਮੂਲ ਬਣਤਰ ਤੋਂ ਮੌਜੂਦਾ ਵਿਚਲਨ, ਜੇ ਕੋਈ ਹੋਵੇ।",
  saraTitle: "ਸਾਰ (ਟਿਸ਼ੂ ਗੁਣਵੱਤਾ)",
  saraDescription: "ਸਰੀਰ ਦੇ ਟਿਸ਼ੂਆਂ (ਧਾਤੂਆਂ) ਦੀ ਸਮੁੱਚੀ ਗੁਣਵੱਤਾ/ਸਾਰ। ਸੰਬੰਧਿਤ ਹੋਣ 'ਤੇ ਕਿਹੜਾ ਟਿਸ਼ੂ ਹੈ ਇਹ ਨੋਟ ਕਰੋ।",
  samhananaTitle: "ਸੰਹਨਨ (ਸਰੀਰ ਬਣਤਰ)",
  samhananaDescription: "ਸਰੀਰ ਬਣਤਰ ਦੀ ਕਸਾਵਟ ਅਤੇ ਏਕੀਕਰਨ।",
  pramanaTitle: "ਪ੍ਰਮਾਣ (ਸਰੀਰ ਅਨੁਪਾਤ)",
  pramanaDescription: "ਆਦਰਸ਼ ਦੇ ਮੁਕਾਬਲੇ ਸਰੀਰ ਦੇ ਮਾਪਾਂ ਦਾ ਅਨੁਪਾਤ।",
  satmyaTitle: "ਸਾਤਮਯ (ਅਨੁਕੂਲਤਾ)",
  satmyaDescription: "ਖੁਰਾਕ, ਜਲਵਾਯੂ ਅਤੇ ਜੀਵਨਸ਼ੈਲੀ ਵਿੱਚ ਮਰੀਜ਼ ਜਿਸਦਾ ਆਦੀ ਅਤੇ ਚੰਗੀ ਤਰ੍ਹਾਂ ਅਨੁਕੂਲਿਤ ਹੈ।",
  sattvaTitle: "ਸਤਵ (ਮਾਨਸਿਕ ਸ਼ਕਤੀ)",
  sattvaDescription: "ਮਨੋਵਿਗਿਆਨਕ ਸ਼ਕਤੀ ਅਤੇ ਮਾਨਸਿਕ ਲਚਕੀਲਾਪਣ।",
  aharaShaktiTitle: "ਆਹਾਰ ਸ਼ਕਤੀ (ਪਾਚਨ ਸਮਰੱਥਾ)",
  aharaShaktiDescription: "ਭੋਜਨ ਲੈਣ ਦੀ ਸਮਰੱਥਾ ਅਤੇ ਇਸਨੂੰ ਹਜ਼ਮ ਕਰਨ ਦੀ ਸਮਰੱਥਾ — ਵੱਖਰੇ ਤੌਰ 'ਤੇ ਮੁਲਾਂਕਿਤ।",
  abhyavaharanaShaktiLabel: "ਅਭਯਵਹਰਣ ਸ਼ਕਤੀ (ਭੁੱਖ / ਗ੍ਰਹਿਣ ਸਮਰੱਥਾ)",
  jaranaShaktiLabel: "ਜਾਰਣ ਸ਼ਕਤੀ (ਪਾਚਨ / ਪਾਚਕ ਸਮਰੱਥਾ)",
  vyayamaShaktiTitle: "ਵਿਆਯਾਮ ਸ਼ਕਤੀ (ਕਸਰਤ ਸਮਰੱਥਾ)",
  vyayamaShaktiDescription: "ਸਰੀਰਕ ਸਹਿਣਸ਼ੀਲਤਾ ਅਤੇ ਮਿਹਨਤ ਸਹਿਣ ਦੀ ਸਮਰੱਥਾ।",
  vayaTitle: "ਵਯ (ਉਮਰ ਵਰਗ)",
  vayaDescription: "ਸ਼ਾਸਤਰੀ ਉਮਰ-ਵਰਗ, ਜੋ ਦੋਸ਼ ਸ਼ਕਤੀ ਅਤੇ ਇਲਾਜ ਯੋਜਨਾ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ।",
  vayaYearsLabel: "ਸਹੀ ਉਮਰ ਸਾਲਾਂ ਵਿੱਚ (ਵਿਕਲਪਿਕ)",
  aharaViharaPlaceholder: "ਆਮ ਰੋਜ਼ਾਨਾ ਖੁਰਾਕ ਅਤੇ ਜੀਵਨਸ਼ੈਲੀ ਪੈਟਰਨ…",
  nidanaPlaceholder: "ਮਰੀਜ਼ ਸੋਚਦਾ ਹੈ ਕਿ ਇਸਦਾ ਕਾਰਨ ਜਾਂ ਟ੍ਰਿਗਰ ਕੀ ਸੀ…",
  sampraptiPlaceholder: "ਬਿਮਾਰੀ ਦੀ ਪ੍ਰਕਿਰਿਆ 'ਤੇ ਕਲੀਨਿਕਲ ਤਰਕ — ਆਮ ਤੌਰ 'ਤੇ ਕਲੀਨੀਸ਼ੀਅਨ ਦੁਆਰਾ ਪੂਰਾ ਜਾਂ ਸੁਧਾਰਿਆ ਜਾਂਦਾ ਹੈ…",
  doshaVata: "ਵਾਤ",
  doshaPitta: "ਪਿੱਤ",
  doshaKapha: "ਕਫ",
  doshaVataPitta: "ਵਾਤ-ਪਿੱਤ",
  doshaPittaKapha: "ਪਿੱਤ-ਕਫ",
  doshaVataKapha: "ਵਾਤ-ਕਫ",
  doshaSama: "ਸਮ (ਤ੍ਰਿਦੋਸ਼ਜ / ਸੰਤੁਲਿਤ)",
  vikritiNoImbalance: "ਕੋਈ ਮਹੱਤਵਪੂਰਨ ਅਸੰਤੁਲਨ ਨਹੀਂ ਦੇਖਿਆ ਗਿਆ",
  gradePravara: "ਪ੍ਰਵਰ (ਉੱਚ)",
  gradeMadhyama: "ਮੱਧਮ (ਦਰਮਿਆਨਾ)",
  gradeAvara: "ਅਵਰ (ਘੱਟ)",
  satmyaSama: "ਸਮ ਸਾਤਮਯ — ਸੰਤੁਲਿਤ, ਚੰਗੀ ਤਰ੍ਹਾਂ ਅਨੁਕੂਲਿਤ",
  satmyaVishama: "ਵਿਸ਼ਮ ਸਾਤਮਯ — ਅਨਿਯਮਿਤ, ਮਾੜੀ ਅਨੁਕੂਲਤਾ",
  satmyaEkaRasa: "ਏਕ ਰਸ ਸਾਤਮਯ — ਇੱਕ ਪ੍ਰਮੁੱਖ ਸੁਆਦ ਦਾ ਆਦੀ",
  vayaBala: "ਬਾਲ — ਬਚਪਨ (ਲਗਭਗ 16 ਸਾਲ ਤੱਕ)",
  vayaMadhyama: "ਮੱਧਮ / ਯੁਵਾ — ਬਾਲਗ (16–70 ਸਾਲ)",
  vayaVriddha: "ਵ੍ਰਿੱਧ — ਬੁਢਾਪਾ (70+ ਸਾਲ)",
  dashavidhaReviewTitle: "ਦਸ਼ਵਿਧ ਪਰੀਖਿਆ",
};

const or: ClinicalIntakeText = {
  title: "ପରାମର୍ଶ ପୂର୍ବରୁ ଆପଣଙ୍କର କ୍ଲିନିକାଲ ଇତିହାସ।",
  subtitle: "ଆଜି ଆପଣଙ୍କୁ ଏଠାକୁ ଆଣିଥିବା ସମସ୍ୟା JeevanLinkକୁ କହନ୍ତୁ। କଥା କହନ୍ତୁ କିମ୍ବା ଟ୍ୟାପ୍ କରନ୍ତୁ।",
  consentTitle: "ସମ୍ମତି ଏବଂ ନିୟନ୍ତ୍ରଣ",
  consentText: "କ୍ଲିନିସିଆନ୍ ସମୀକ୍ଷା ପାଇଁ କ୍ଲିନିକାଲ ଇତିହାସର ଡ୍ରାଫ୍ଟ ତିଆରି କରିବାରେ ଆପଣଙ୍କ ଉତ୍ତର ବ୍ୟବହୃତ ହେବ। ଏହି ଟୁଲ୍ ରୋଗ ନିର୍ଣ୍ଣୟ କିମ୍ବା ଔଷଧ ଦେଉନାହିଁ।",
  listenExplanation: "ବ୍ୟାଖ୍ୟା ଶୁଣନ୍ତୁ",
  audioGuided: "ଅଡିଓ-ନିର୍ଦ୍ଦେଶିତ ସମ୍ମତି",
  voiceLanguage: "ଭଏସ୍ ଭାଷା",
  humanVerification: "ମାନବ ଯାଞ୍ଚ ଆବଶ୍ୟକ",
  patient: "ରୋଗୀ",
  preConsultation: "ପରାମର୍ଶ ପୂର୍ବ କ୍ଲିନିକାଲ ଇନଟେକ୍",
  step: "ପଦକ୍ରମ",
  of: "ରୁ",
  historyMode: "ଇତିହାସର ପ୍ରକାର ବାଛନ୍ତୁ",
  general: "ସାଧାରଣ",
  generalDescription: "ମାନକ କ୍ଲିନିକାଲ ଇତିହାସ ସାକ୍ଷାତକାର",
  ayush: "ଆୟୁଷ / ଆୟୁର୍ବେଦ",
  ayushDescription: "ଦଶବିଧ + ଆହାର-ବିହାର ବିବରଣୀ",
  chiefComplaint: "ଆଜି ଆପଣଙ୍କୁ ଏଠାକୁ ଆଣିଥିବା ସମସ୍ୟା କଣ?",
  chiefComplaintSubtitle: "ପ୍ରଥମେ ରୋଗୀଙ୍କ ନିଜ ଶବ୍ଦରେ କହନ୍ତୁ। ପରବର୍ତ୍ତୀ ପଦକ୍ରମରେ ଇତିହାସକୁ ଅଧିକ ବିସ୍ତାର କରିପାରିବେ।",
  hpiTitle: "ବର୍ତ୍ତମାନ ରୋଗର ଇତିହାସ",
  hpiSubtitle: "ଏହି ପ୍ରଶ୍ନଗୁଡିକ ଏକ ନିୟନ୍ତ୍ରିତ କ୍ଲିନିକାଲ ଇତିହାସ ଗଠନକୁ ଅନୁସରଣ କରେ। କଥା କହିବା କିମ୍ବା ଟାଇପ୍ କରିବା ସମ୍ଭବ।",
  onset: "କେବେ ଆରମ୍ଭ ହେଲା?",
  duration: "କେତେ ଦିନ ହେଲା?",
  character: "ଆପଣ ଏହାକୁ କିପରି ବର୍ଣ୍ଣନା କରିବେ?",
  location: "ଏହା କେଉଁଠି ଅଛି?",
  radiation: "ଏହା ଅନ୍ୟ କୌଣସି ସ୍ଥାନକୁ ପ୍ରସାରିତ ହେଉଛି କି?",
  severity: "କେତେ ତୀବ୍ର?",
  aggravating: "କଣ କଲେ ଏହା ବଢ଼େ?",
  relieving: "କଣ କଲେ ଏହା କମେ?",
  associatedSymptoms: "ଏହା ସହିତ ଅନ୍ୟ କୌଣସି ଲକ୍ଷଣ ଅଛି କି?",
  hpiHintChestPain: "ଛାତି ବେଦନା ପାଇଁ, ଏହା ମଧ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ ଯେ ଏହା ଆପଣଙ୍କ ବାହୁ, ଚୋବେଇ, ବେକ କିମ୍ବା ପିଠିକୁ ବ୍ୟାପେ କି, ଏବଂ ଏହା ସହିତ ଝାଳ କିମ୍ବା ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ ହୁଏ କି।",
  hpiHintFever: "ଜ୍ୱର ପାଇଁ, ଏହା ମଧ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ ଯେ ଏହା ନିରନ୍ତର କି ଆସେ-ଯାଏ, ଏବଂ ମାପିଥିଲେ ସର୍ବାଧିକ ତାପମାତ୍ରା କେତେ ଥିଲା।",
  hpiHintCough: "କାଶ ପାଇଁ, ଏହା ମଧ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ ଯେ ଏହା ଶୁଖିଲା କି କଫ ସହିତ, ଏବଂ କଫ ଥିଲେ ତାହାର ରଙ୍ଗ କଣ।",
  hpiHintAbdominalPain: "ପେଟ ବେଦନା ପାଇଁ, ଏହା ମଧ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ ଯେ ଏହା ଖାଇବା, ମଳତ୍ୟାଗ, କିମ୍ବା ବାନ୍ତି ସହିତ ସମ୍ପର୍କିତ କି।",
  hpiHintHeadache: "ମୁଣ୍ଡବିନ୍ଧା ପାଇଁ, ଆଲୋକ, ଶବ୍ଦ କିମ୍ବା ଗତି ଦ୍ୱାରା ଏହା ବଢ଼େ କି, ଏବଂ ଦୃଷ୍ଟିରେ କୌଣସି ପରିବର୍ତ୍ତନ ଅଛି କି ତାହା ମଧ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ।",
  pastTitle: "ପୂର୍ବ ଏବଂ ବର୍ତ୍ତମାନର ଇତିହାସ",
  pastSubtitle: "ରୋଗୀଙ୍କୁ ଜଣାଥିବା ସୂଚନା ଦିଅନ୍ତୁ। ଜଣା ନଥିଲେ ଖାଲି ରଖନ୍ତୁ।",
  pastMedical: "ପୂର୍ବ ଚିକିତ୍ସା ଇତିହାସ",
  pastSurgical: "ପୂର୍ବ ଶଲ୍ୟଚିକିତ୍ସା ଇତିହାସ",
  medications: "ବର୍ତ୍ତମାନର ଔଷଧ",
  allergies: "ଆଲର୍ଜି",
  family: "ପରିବାରିକ ଇତିହାସ",
  occupation: "ପେଶା",
  diet: "ଖାଦ୍ୟ",
  sleep: "ନିଦ୍ରା",
  smoking: "ଧୂମପାନ / ତମାଖୁ",
  alcohol: "ମଦ୍ୟପାନ",
  reviewTitle: "ସିଷ୍ଟମ ରିଭ୍ୟୁ ଏବଂ ପରୀକ୍ଷା",
  reviewSubtitle: "ଏହା ଗଠିତ ସୂଚନା ସଂଗ୍ରହ; ସ୍ୱୟଂଚାଳିତ ରୋଗ ନିର୍ଣ୍ଣୟ ନୁହେଁ।",
  ros: "ସିଷ୍ଟମ ରିଭ୍ୟୁ",
  investigations: "ପୂର୍ବ ପରୀକ୍ଷା",
  documentsTitle: "ପୂର୍ବ ଚିକିତ୍ସା ଦଲିଲ ଯୋଡନ୍ତୁ",
  documentsDescription: "ପ୍ରେସକ୍ରିପସନ୍, ଲ୍ୟାବ୍ ରିପୋର୍ଟ କିମ୍ବା ଡିସଚାର୍ଜ ସାରାଂଶ ଅପଲୋଡ୍ କରନ୍ତୁ। ବର୍ତ୍ତମାନର AI ଡକ୍ୟୁମେଣ୍ଟ ପାଇପଲାଇନ୍ ଉପଲବ୍ଧ କ୍ଲିନିକାଲ ସୂଚନା ବାହାର କରିବ।",
  analyze: "ଦଲିଲ ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
  analyzing: "ବିଶ୍ଳେଷଣ ହେଉଛି…",
  selectedSuffix: "ଟି ଦଲିଲ ଚୟନ ହୋଇଛି।",
  aiContext: "AI ଦ୍ୱାରା ମିଳିଥିବା ସନ୍ଦର୍ଭ",
  safetyScreen: "ସୁରକ୍ଷା ଯାଞ୍ଚ",
  safetyText: "ସମ୍ଭାବ୍ୟ ଜରୁରୀ ଲକ୍ଷଣଗୁଡିକୁ ମାନବ ଟ୍ରାଏଜ ପାଇଁ ଚିହ୍ନିତ କରାଯିବ। ସିଷ୍ଟମ ରୋଗ ନିର୍ଣ୍ଣୟ କିମ୍ବା ଔଷଧ ଦେବ ନାହିଁ।",
  review: "ଇତିହାସ ସମୀକ୍ଷା କରନ୍ତୁ",
  reviewSubtitle2: "କ୍ଲିନିସିଆନ୍ ସମୀକ୍ଷାକୁ ପଠାଇବା ପୂର୍ବରୁ ଡ୍ରାଫ୍ଟକୁ ଯାଞ୍ଚ କରନ୍ତୁ।",
  submit: "କ୍ଲିନିସିଆନ୍ ସମୀକ୍ଷାକୁ ପଠାନ୍ତୁ",
  submitting: "ପଠାଯାଉଛି…",
  submitted: "କ୍ଲିନିସିଆନ୍ ଯାଞ୍ଚ ପାଇଁ ପଠାଯାଇଛି",
  complete: "ଆପଣଙ୍କ ଇନଟେକ୍ ପେଣ୍ଡିଂ କ୍ଲିନିକାଲ ରେକର୍ଡ ଭାବେ ସଂରକ୍ଷିତ ହୋଇଛି।",
  completionNote: "ବର୍ତ୍ତମାନର କ୍ଲିନିସିଆନ୍ ଯାଞ୍ଚ ପ୍ରକ୍ରିୟା ହିଁ ଶେଷ ଅଧିକାର। ଯାଞ୍ଚ ପୂର୍ବରୁ ଏହା trusted longitudinal ସୂଚନା ହେବ ନାହିଁ।",
  openRecords: "ହେଲ୍ଥ୍ ରେକର୍ଡ ଖୋଲନ୍ତୁ",
  backDashboard: "ଡ୍ୟାଶବୋର୍ଡକୁ ଫେରନ୍ତୁ",
  urgent: "ଜରୁରୀ ଧ୍ୟାନ ଆବଶ୍ୟକ",
  triageNote: "ଏହା ଟ୍ରାଏଜ ଏସ୍କାଲେସନ୍ ସଙ୍କେତ, ରୋଗ ନିର୍ଣ୍ଣୟ ନୁହେଁ।",
  voiceTouch: "ଭଏସ୍ + ଟଚ୍",
  voiceTouchDescription: "ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନର ଉତ୍ତର ପାଇଁ ଦୁଇଟି ଉପାୟ",
  speakPrompt: "ଆପଣ କଥା କହି କିମ୍ବା ଟାଇପ୍ କରି ଉତ୍ତର ଦେଇପାରିବେ।",
  redFlagEscalation: "ରେଡ୍-ଫ୍ଲାଗ୍ ଏସ୍କାଲେସନ୍",
  redFlagDescription: "ଜରୁରୀ ଲକ୍ଷଣ ସାଧାରଣ ଇନଟେକ୍ ବନ୍ଦ କରିପାରେ",
  redFlagBody: "JeevanLink ନିର୍ଦ୍ଧାରିତ ଜରୁରୀ ଲକ୍ଷଣକୁ ମାନବ ଧ୍ୟାନ ପାଇଁ ଫ୍ଲାଗ୍ କରେ। ଏହା ରୋଗ ନିର୍ଣ୍ଣୟ କିମ୍ବା ଔଷଧ ଦିଏ ନାହିଁ।",
  verificationGate: "ଯାଞ୍ଚ ଗେଟ୍",
  verificationBody: "ପ୍ରତ୍ୟେକ ଇନଟେକ୍ PENDING ଭାବରେ ସେଭ୍ ହୁଏ। ରେକର୍ଡ trusted ହେବା ପୂର୍ବରୁ କ୍ଲିନିସିଆନ୍ ଯାଞ୍ଚ ହେଉଛି ଶେଷ ଉତ୍ସ।",
  continue: "ଆଗକୁ ଯାଆନ୍ତୁ",
  back: "ପଛକୁ",
  speak: "କହନ୍ତୁ",
  stop: "ବନ୍ଦ କରନ୍ତୁ",
  listening: "ଶୁଣୁଛି…",
  transcribing: "ଟେକ୍ସଟ୍‌କୁ ପରିବର୍ତ୍ତନ ହେଉଛି…",
  voiceUnavailable: "ଏହି ବ୍ରାଉଜରରେ ଭଏସ୍ ରେକର୍ଡିଂ ଉପଲବ୍ଧ ନାହିଁ। ଆପଣ ଉତ୍ତର ଟାଇପ୍ କରିପାରିବେ।",
  voiceFailed: "ଭଏସ୍ କ୍ୟାପଚର୍ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇନି। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ କିମ୍ବା ଟାଇପ୍ କରନ୍ତୁ।",
  transcriptionFailed: "ଏହି ରେକର୍ଡିଂକୁ ଟେକ୍ସଟ୍‌ରେ ପରିବର୍ତ୍ତନ କରିହେଲା ନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ କିମ୍ବା ଟାଇପ୍ କରନ୍ତୁ।",
  notReported: "ଜଣାଇ ନାହାନ୍ତି",
  enterAnswer: "ଆପଣଙ୍କ ଉତ୍ତର ଲେଖନ୍ତୁ…",
  quickChestPain: "ଛାତି ବେଦନା",
  quickFever: "ଜ୍ୱର",
  quickCough: "କାଶ",
  quickAbdominalPain: "ପେଟ ବେଦନା",
  quickHeadache: "ମୁଣ୍ଡବେଦନା",
  quickOther: "ଅନ୍ୟ",
  ayushContext: "ଆୟୁଷ ସନ୍ଦର୍ଭ",
  ayushIntro: "କ୍ଲିନିସିଆନ୍ ଙ୍କ ନିଷ୍ପତ୍ତିକୁ ବଦଳାଇନ ଅତିରିକ୍ତ ଆୟୁର୍ବେଦିକ ସୂଚନା ଦିଅନ୍ତୁ।",
  noDocuments: "ପୂର୍ବରୁ କୌଣସି ଦଲିଲ ଚୟନ ହୋଇନାହିଁ।",
  microphone: "ମାଇକ୍ରୋଫୋନ୍",
  consentClinicalHistory: "ମୁଁ କ୍ଲିନିକାଲ ଇତିହାସ ସଂଗ୍ରହ ପାଇଁ ସମ୍ମତ।",
  consentDocumentProcessing: "ସନ୍ଦର୍ଭ ପ୍ରସ୍ତୁତ କରିବା ପାଇଁ ଚିକିତ୍ସା ଦଲିଲ ପ୍ରକ୍ରିୟାକରଣ ହୋଇପାରେ ବୋଲି ମୁଁ ବୁଝୁଛି।",
  consentClinicianSharing: "ଏହି ଡ୍ରାଫ୍ଟକୁ ଚିକିତ୍ସା କରୁଥିବା କ୍ଲିନିସିଆନ୍ ସହ ସମୀକ୍ଷା ପାଇଁ ଭାଗ କରିବାକୁ ମୁଁ ସମ୍ମତ।",
  a11yAudioGuided: "ଅଡିଓ ଗାଇଡ୍",
  a11yHighContrast: "ଉଚ୍ଚ କଣ୍ଟ୍ରାଷ୍ଟ",
  a11yLargeText: "ବଡ଼ ଟେକ୍ସଟ୍",
  dashavidhaNotesPlaceholder: "ଅତିରିକ୍ତ ଟିପ୍ପଣୀ (ଇଚ୍ଛାଧୀନ)",
  prakritiTitle: "ପ୍ରକୃତି (ଶାରୀରିକ ଗଠନ)",
  prakritiDescription: "ଜନ୍ମରୁ ନିର୍ଦ୍ଧାରିତ ମୂଳ ଶାରୀରିକ ଗଠନ। ନିକଟତମ ଶାସ୍ତ୍ରୀୟ ପ୍ରକାର ବାଛନ୍ତୁ।",
  vikritiTitle: "ବିକୃତି (ବର୍ତ୍ତମାନ ଅସନ୍ତୁଳନ)",
  vikritiDescription: "ମୂଳ ଗଠନରୁ ବର୍ତ୍ତମାନ ବିଚ୍ୟୁତି, ଯଦି କିଛି ଥାଏ।",
  saraTitle: "ସାର (ଟିସୁ ଗୁଣବତ୍ତା)",
  saraDescription: "ଶରୀରର ଟିସୁଗୁଡ଼ିକର (ଧାତୁ) ସାମଗ୍ରିକ ଗୁଣବତ୍ତା/ସାର। ପ୍ରାସଙ୍ଗିକ ହେଲେ କେଉଁ ଟିସୁ ତାହା ଉଲ୍ଲେଖ କରନ୍ତୁ।",
  samhananaTitle: "ସଂହନନ (ଶରୀର ଗଠନ)",
  samhananaDescription: "ଶରୀର ଗଠନର ଦୃଢ଼ତା ଏବଂ ଏକୀକରଣ।",
  pramanaTitle: "ପ୍ରମାଣ (ଶରୀର ଅନୁପାତ)",
  pramanaDescription: "ଆଦର୍ଶ ତୁଳନାରେ ଶରୀର ମାପର ଅନୁପାତ।",
  satmyaTitle: "ସାତ୍ମ୍ୟ (ଅନୁକୂଳତା)",
  satmyaDescription: "ଖାଦ୍ୟ, ଜଳବାୟୁ ଏବଂ ଜୀବନଶୈଳୀରେ ରୋଗୀ ଅଭ୍ୟସ୍ତ ଏବଂ ଭଲ ଭାବରେ ଖାପ ଖୁଆଇଥିବା।",
  sattvaTitle: "ସତ୍ତ୍ୱ (ମାନସିକ ଶକ୍ତି)",
  sattvaDescription: "ମାନସିକ ଶକ୍ତି ଏବଂ ମାନସିକ ସ୍ଥିତିସ୍ଥାପକତା।",
  aharaShaktiTitle: "ଆହାର ଶକ୍ତି (ପାଚନ କ୍ଷମତା)",
  aharaShaktiDescription: "ଖାଦ୍ୟ ଗ୍ରହଣ କରିବାର କ୍ଷମତା ଏବଂ ତାହା ପଚାଇବାର କ୍ଷମତା — ପୃଥକ ଭାବରେ ମୂଲ୍ୟାୟନ କରାଯାଏ।",
  abhyavaharanaShaktiLabel: "ଅଭ୍ୟବହରଣ ଶକ୍ତି (କ୍ଷୁଧା / ଗ୍ରହଣ କ୍ଷମତା)",
  jaranaShaktiLabel: "ଜରଣ ଶକ୍ତି (ପାଚନ / ବିପାକ କ୍ଷମତା)",
  vyayamaShaktiTitle: "ବ୍ୟାୟାମ ଶକ୍ତି (ବ୍ୟାୟାମ କ୍ଷମତା)",
  vyayamaShaktiDescription: "ଶାରୀରିକ ସହନଶୀଳତା ଏବଂ ପରିଶ୍ରମ ସହ୍ୟ କରିବାର କ୍ଷମତା।",
  vayaTitle: "ବୟ (ବୟସ ବର୍ଗ)",
  vayaDescription: "ଶାସ୍ତ୍ରୀୟ ବୟସ-ବର୍ଗ, ଯାହା ଦୋଷ ବଳ ଏବଂ ଚିକିତ୍ସା ଯୋଜନାକୁ ପ୍ରଭାବିତ କରେ।",
  vayaYearsLabel: "ସଠିକ୍ ବୟସ ବର୍ଷରେ (ଇଚ୍ଛାଧୀନ)",
  aharaViharaPlaceholder: "ସାଧାରଣ ଦୈନନ୍ଦିନ ଖାଦ୍ୟ ଏବଂ ଜୀବନଶୈଳୀ ଢାଞ୍ଚା…",
  nidanaPlaceholder: "ରୋଗୀ ବିଶ୍ୱାସ କରନ୍ତି ଯେ ଏହାର କାରଣ କଣ ବା କେଉଁଥିରୁ ଆରମ୍ଭ ହେଲା…",
  sampraptiPlaceholder: "ରୋଗ ପ୍ରକ୍ରିୟା ଉପରେ କ୍ଲିନିକାଲ୍ ତର୍କ — ସାଧାରଣତଃ କ୍ଲିନିସିଆନ୍‌ ଦ୍ୱାରା ସମ୍ପୂର୍ଣ୍ଣ କିମ୍ବା ପରିମାର୍ଜିତ ହୁଏ…",
  doshaVata: "ବାତ",
  doshaPitta: "ପିତ୍ତ",
  doshaKapha: "କଫ",
  doshaVataPitta: "ବାତ-ପିତ୍ତ",
  doshaPittaKapha: "ପିତ୍ତ-କଫ",
  doshaVataKapha: "ବାତ-କଫ",
  doshaSama: "ସମ (ତ୍ରିଦୋଷଜ / ସନ୍ତୁଳିତ)",
  vikritiNoImbalance: "କୌଣସି ଉଲ୍ଲେଖନୀୟ ଅସନ୍ତୁଳନ ଲକ୍ଷ୍ୟ କରାଯାଇନାହିଁ",
  gradePravara: "ପ୍ରବର (ଉଚ୍ଚ)",
  gradeMadhyama: "ମଧ୍ୟମ (ମଧ୍ୟମ)",
  gradeAvara: "ଅବର (ନିମ୍ନ)",
  satmyaSama: "ସମ ସାତ୍ମ୍ୟ — ସନ୍ତୁଳିତ, ଭଲ ଭାବରେ ଖାପ ଖୁଆଇଥିବା",
  satmyaVishama: "ବିଷମ ସାତ୍ମ୍ୟ — ଅନିୟମିତ, ଖରାପ ଅନୁକୂଳତା",
  satmyaEkaRasa: "ଏକ ରସ ସାତ୍ମ୍ୟ — ଏକ ପ୍ରଧାନ ସ୍ୱାଦର ଅଭ୍ୟସ୍ତ",
  vayaBala: "ବାଳ — ଶୈଶବ (ପ୍ରାୟ 16 ବର୍ଷ ପର୍ଯ୍ୟନ୍ତ)",
  vayaMadhyama: "ମଧ୍ୟମ / ଯୁବା — ପ୍ରାପ୍ତବୟସ୍କ (16–70 ବର୍ଷ)",
  vayaVriddha: "ବୃଦ୍ଧ — ବାର୍ଧକ୍ୟ (70+ ବର୍ଷ)",
  dashavidhaReviewTitle: "ଦଶବିଧ ପରୀକ୍ଷା",
};

const as: ClinicalIntakeText = {
  title: "পৰামৰ্শৰ আগতে আপোনাৰ ক্লিনিকেল ইতিহাস।",
  subtitle: "আজি আপোনাক ইয়ালৈ অনা সমস্যাটো JeevanLink-ক কওক। কথা কওক বা টেপ কৰক।",
  consentTitle: "সন্মতি আৰু নিয়ন্ত্ৰণ",
  consentText: "ক্লিনিচিয়ান পৰ্যালোচনাৰ বাবে ক্লিনিকেল ইতিহাসৰ খচৰা তৈয়াৰ কৰাত আপোনাৰ উত্তৰ ব্যৱহাৰ কৰা হ’ব। এই টুলে ৰোগ নিৰ্ণয় বা ঔষধ নিৰ্ধাৰণ নকৰে।",
  listenExplanation: "ব্যাখ্যা শুনক",
  audioGuided: "অডিঅ’-নিৰ্দেশিত সন্মতি",
  voiceLanguage: "ভইচৰ ভাষা",
  humanVerification: "মানৱ যাচাই প্ৰয়োজন",
  patient: "ৰোগী",
  preConsultation: "পৰামৰ্শ-পূৰ্ব ক্লিনিকেল ইনটেক",
  step: "পদক্ষেপ",
  of: "ৰ",
  historyMode: "ইতিহাসৰ ধৰণ বাছক",
  general: "সাধাৰণ",
  generalDescription: "মানক ক্লিনিকেল ইতিহাসৰ সাক্ষাৎকাৰ",
  ayush: "আয়ুষ / আয়ুৰ্বেদ",
  ayushDescription: "দশবিধ + আহাৰ-বিহাৰ তথ্য",
  chiefComplaint: "আজি আপোনাক ইয়ালৈ অনা সমস্যাটো কি?",
  chiefComplaintSubtitle: "প্ৰথমে ৰোগীয়ে নিজৰ ভাষাত কওক। পিছৰ ধাপত ইতিহাস অধিক বিশদ কৰিব পাৰি।",
  hpiTitle: "বৰ্তমান অসুস্থতাৰ ইতিহাস",
  hpiSubtitle: "এই প্ৰশ্নসমূহে এটা নিয়ন্ত্ৰিত ক্লিনিকেল ইতিহাস গঠন অনুসৰণ কৰে। কথা কৈ বা টাইপ কৰি উত্তৰ দিব পাৰি।",
  onset: "কেতিয়া আৰম্ভ হৈছিল?",
  duration: "কিমান দিন ধৰি আছে?",
  character: "আপুনি ইয়াক কেনেকৈ বৰ্ণনা কৰিব?",
  location: "ই ক’ত আছে?",
  radiation: "ই আন ঠাইলৈ বিয়পি যায় নেকি?",
  severity: "কিমান তীব্ৰ?",
  aggravating: "কিহে ইয়াক বঢ়ায়?",
  relieving: "কিহে ইয়াক কমায়?",
  associatedSymptoms: "ইয়াৰ লগত আন কোনো লক্ষণ আছে নেকি?",
  hpiHintChestPain: "বুকুৰ বিষৰ বাবে, ই আপোনাৰ বাহু, চোৱাল, ডিঙি বা পিঠিলৈ বিয়পি পৰে নেকি, আৰু ইয়াৰ সৈতে ঘাম অহা বা উশাহ-নিশাহত অসুবিধা হয় নেকি সেয়াও উল্লেখ কৰক।",
  hpiHintFever: "জ্বৰৰ বাবে, ই একেৰাহে থাকে নে আহি থাকে, আৰু জোখ লৈছিল যদি সৰ্বাধিক উষ্ণতা কিমান আছিল সেয়াও উল্লেখ কৰক।",
  hpiHintCough: "কাহৰ বাবে, ই শুকান নে গেঁহেতযুক্ত, আৰু গেঁহেত থাকিলে তাৰ ৰং কি সেয়াও উল্লেখ কৰক।",
  hpiHintAbdominalPain: "পেটৰ বিষৰ বাবে, ই খোৱা, পেট পৰিষ্কাৰ হোৱা, বা বমিৰ সৈতে জড়িত নেকি সেয়াও উল্লেখ কৰক।",
  hpiHintHeadache: "মূৰৰ বিষৰ বাবে, পোহৰ, শব্দ বা লৰচৰত ই বাঢ়ে নেকি, আৰু দৃষ্টিত কোনো সলনি আছে নেকি সেয়াও উল্লেখ কৰক।",
  pastTitle: "পূৰ্ব আৰু বৰ্তমানৰ ইতিহাস",
  pastSubtitle: "ৰোগীয়ে জনা তথ্য দিয়ক। নাজানিলে খালী ৰাখক।",
  pastMedical: "পূৰ্ব চিকিৎসা ইতিহাস",
  pastSurgical: "পূৰ্ব অস্ত্ৰোপচাৰৰ ইতিহাস",
  medications: "বৰ্তমানৰ ঔষধ",
  allergies: "এলাৰ্জী",
  family: "পাৰিবাৰিক ইতিহাস",
  occupation: "পেচা",
  diet: "খাদ্যাভ্যাস",
  sleep: "টোপনি",
  smoking: "ধূমপান / তামোল",
  alcohol: "মদ্যপান",
  reviewTitle: "চিষ্টেম ৰিভিউ আৰু পৰীক্ষা",
  reviewSubtitle: "এইটো গঠনমূলক তথ্য সংগ্ৰহ; স্বয়ংক্ৰিয় ৰোগ নিৰ্ণয় নহয়।",
  ros: "চিষ্টেম ৰিভিউ",
  investigations: "পূৰ্বৰ পৰীক্ষা",
  documentsTitle: "পূৰ্বৰ চিকিৎসা নথি যোগ কৰক",
  documentsDescription: "প্ৰেছক্ৰিপচন, লেবৰেটৰী ৰিপ’ৰ্ট বা ডিছচাৰ্জ সাৰাংশ আপলোড কৰক। বৰ্তমানৰ AI নথি পাইপলাইনে উপলব্ধ ক্লিনিকেল তথ্য উলিয়াব।",
  analyze: "নথি বিশ্লেষণ কৰক",
  analyzing: "বিশ্লেষণ হৈ আছে…",
  selectedSuffix: "টা নথি বাছনি কৰা হৈছে।",
  aiContext: "AI-ৰ পৰা পোৱা তথ্য",
  safetyScreen: "নিৰাপত্তা পৰীক্ষা",
  safetyText: "সম্ভাৱ্য জৰুৰী লক্ষণসমূহ মানৱ ট্ৰায়াজৰ বাবে চিহ্নিত কৰা হ’ব। ছিষ্টেমে ৰোগ নিৰ্ণয় বা ঔষধ নিদিয়ে।",
  review: "ইতিহাস পৰ্যালোচনা কৰক",
  reviewSubtitle2: "ক্লিনিচিয়ান পৰ্যালোচনালৈ পঠোৱাৰ আগতে খচৰা পৰীক্ষা কৰক।",
  submit: "ক্লিনিচিয়ান পৰ্যালোচনালৈ পঠিয়াওক",
  submitting: "পঠিওৱা হৈছে…",
  submitted: "ক্লিনিচিয়ান যাচাইৰ বাবে পঠিওৱা হৈছে",
  complete: "আপোনাৰ ইনটেক পেণ্ডিং ক্লিনিকেল ৰেকৰ্ড হিচাপে সংৰক্ষণ কৰা হৈছে।",
  completionNote: "বৰ্তমানৰ ক্লিনিচিয়ান যাচাই প্ৰক্ৰিয়াই চূড়ান্ত কৰ্তৃত্ব ধৰে। যাচাই নোহোৱালৈকে ই trusted longitudinal তথ্য নহ’ব।",
  openRecords: "হেল্থ ৰেকৰ্ড খোলক",
  backDashboard: "ডেশ্বব’ৰ্ডলৈ উভতি যাওক",
  urgent: "জৰুৰী মনোযোগ প্ৰয়োজন",
  triageNote: "এইটো ট্ৰায়াজ এস্কেলেচন সংকেত, ৰোগ নিৰ্ণয় নহয়।",
  voiceTouch: "ভইচ + টাচ",
  voiceTouchDescription: "প্ৰতিটো প্ৰশ্নৰ উত্তৰ দিয়াৰ দুটা উপায়",
  speakPrompt: "আপুনি কথা কৈ বা টাইপ কৰি উত্তৰ দিব পাৰে।",
  redFlagEscalation: "ৰেড-ফ্লেগ এস্কেলেচন",
  redFlagDescription: "জৰুৰী লক্ষণে সাধাৰণ ইনটেক বন্ধ কৰিব পাৰে",
  redFlagBody: "JeevanLink-এ নিৰ্ধাৰিত জৰুৰী লক্ষণসমূহ মানৱ মনোযোগৰ বাবে ফ্লেগ কৰে। ই ৰোগ নিৰ্ণয় বা ঔষধ প্ৰদান নকৰে।",
  verificationGate: "যাচাই গেট",
  verificationBody: "প্ৰতিটো ইনটেক PENDING হিচাপে সংৰক্ষণ কৰা হয়। ৰেকৰ্ড trusted হোৱাৰ আগতে ক্লিনিচিয়ান যাচাই হৈছে চূড়ান্ত উৎস।",
  continue: "আগলৈ যাওক",
  back: "পিছলৈ",
  speak: "কওক",
  stop: "ৰখাওক",
  listening: "শুনিছোঁ…",
  transcribing: "টেক্সটলৈ ৰূপান্তৰ কৰা হৈছে…",
  voiceUnavailable: "এই ব্ৰাউজাৰত ভইচ ৰেকৰ্ডিং উপলব্ধ নহয়। আপুনি উত্তৰ টাইপ কৰিব পাৰে।",
  voiceFailed: "ভইচ কেপচাৰ সম্পূৰ্ণ নহ’ল। পুনৰ চেষ্টা কৰক বা টাইপ কৰক।",
  transcriptionFailed: "এই ৰেকৰ্ডিংটো টেক্সটলৈ ৰূপান্তৰ কৰিব পৰা নগ’ল। পুনৰ চেষ্টা কৰক বা টাইপ কৰক।",
  notReported: "জানোৱা হোৱা নাই",
  enterAnswer: "আপোনাৰ উত্তৰ লিখক…",
  quickChestPain: "বুকুৰ বিষ",
  quickFever: "জ্বৰ",
  quickCough: "কাহ",
  quickAbdominalPain: "পেটৰ বিষ",
  quickHeadache: "মূৰৰ বিষ",
  quickOther: "অন্যান্য",
  ayushContext: "আয়ুষ প্ৰসংগ",
  ayushIntro: "ক্লিনিচিয়ানৰ সিদ্ধান্তক সলনি নকৰাকৈ অতিৰিক্ত আয়ুৰ্বেদিক তথ্য লিখক।",
  noDocuments: "কোনো পূৰ্বৰ নথি বাছনি কৰা হোৱা নাই।",
  microphone: "মাইক্ৰ’ফোন",
  consentClinicalHistory: "মই ক্লিনিকেল ইতিহাস সংগ্ৰহৰ বাবে সন্মত।",
  consentDocumentProcessing: "প্ৰসংগ প্ৰস্তুত কৰিবলৈ চিকিৎসা নথি প্ৰক্ৰিয়াকৰণ হ’ব পাৰে বুলি মই বুজি পাইছোঁ।",
  consentClinicianSharing: "এই খচৰা চিকিৎসা কৰা ক্লিনিচিয়ানৰ সৈতে পৰ্যালোচনাৰ বাবে শ্বেয়াৰ কৰিবলৈ মই সন্মত।",
  a11yAudioGuided: "অডিঅ' গাইড",
  a11yHighContrast: "উচ্চ কনট্ৰাষ্ট",
  a11yLargeText: "ডাঙৰ লিখনী",
  dashavidhaNotesPlaceholder: "অতিৰিক্ত টোকা (বৈকল্পিক)",
  prakritiTitle: "প্ৰকৃতি (শাৰীৰিক গঠন)",
  prakritiDescription: "জন্মৰ পৰা নিৰ্ধাৰিত মূল শাৰীৰিক গঠন। আটাইতকৈ ওচৰৰ শাস্ত্ৰীয় প্ৰকাৰ বাছনি কৰক।",
  vikritiTitle: "বিকৃতি (বৰ্তমান অসন্তুলন)",
  vikritiDescription: "মূল গঠনৰ পৰা বৰ্তমান বিচ্যুতি, যদি থাকে।",
  saraTitle: "সাৰ (টিছু গুণগত মান)",
  saraDescription: "শৰীৰৰ টিছুবোৰৰ (ধাতুৰ) সামগ্ৰিক গুণগত মান/সাৰ। প্ৰাসংগিক হ'লে কোনটো টিছু তাক উল্লেখ কৰক।",
  samhananaTitle: "সংহনন (শৰীৰ গঠন)",
  samhananaDescription: "শৰীৰ গঠনৰ দৃঢ়তা আৰু একত্ৰীকৰণ।",
  pramanaTitle: "প্ৰমাণ (শৰীৰ অনুপাত)",
  pramanaDescription: "আদৰ্শৰ তুলনাত শৰীৰৰ জোখৰ অনুপাত।",
  satmyaTitle: "সাত্ম্য (উপযুক্ততা)",
  satmyaDescription: "আহাৰ, বতৰ আৰু জীৱনশৈলীত ৰোগী অভ্যস্ত আৰু ভালদৰে খাপ খুৱাই লোৱা বিষয়।",
  sattvaTitle: "সত্ত্ব (মানসিক শক্তি)",
  sattvaDescription: "মানসিক শক্তি আৰু মানসিক স্থিতিস্থাপকতা।",
  aharaShaktiTitle: "আহাৰ শক্তি (হজম ক্ষমতা)",
  aharaShaktiDescription: "আহাৰ গ্ৰহণ কৰাৰ ক্ষমতা আৰু ইয়াক হজম কৰাৰ ক্ষমতা — পৃথকভাৱে মূল্যায়ন কৰা হয়।",
  abhyavaharanaShaktiLabel: "অভ্যৱহৰণ শক্তি (ভোক / গ্ৰহণ ক্ষমতা)",
  jaranaShaktiLabel: "জাৰণ শক্তি (হজম / বিপাক ক্ষমতা)",
  vyayamaShaktiTitle: "ব্যায়াম শক্তি (ব্যায়াম ক্ষমতা)",
  vyayamaShaktiDescription: "শাৰীৰিক সহনশীলতা আৰু পৰিশ্ৰম সহ্য কৰাৰ ক্ষমতা।",
  vayaTitle: "বয় (বয়স শ্ৰেণী)",
  vayaDescription: "শাস্ত্ৰীয় বয়স-শ্ৰেণী, যিয়ে দোষ বল আৰু চিকিৎসা পৰিকল্পনাত প্ৰভাৱ পেলায়।",
  vayaYearsLabel: "সঠিক বয়স বছৰত (বৈকল্পিক)",
  aharaViharaPlaceholder: "সাধাৰণ দৈনিক আহাৰ আৰু জীৱনশৈলীৰ ধৰণ…",
  nidanaPlaceholder: "ৰোগীয়ে বিশ্বাস কৰে যে ইয়াৰ কাৰণ বা প্ৰৱৰ্তক কি আছিল…",
  sampraptiPlaceholder: "ৰোগ প্ৰক্ৰিয়াৰ ওপৰত ক্লিনিকেল যুক্তি — সাধাৰণতে ক্লিনিছিয়ানৰ দ্বাৰা সম্পূৰ্ণ বা পৰিমাৰ্জিত কৰা হয়…",
  doshaVata: "বাত",
  doshaPitta: "পিত্ত",
  doshaKapha: "কফ",
  doshaVataPitta: "বাত-পিত্ত",
  doshaPittaKapha: "পিত্ত-কফ",
  doshaVataKapha: "বাত-কফ",
  doshaSama: "সম (ত্ৰিদোষজ / সন্তুলিত)",
  vikritiNoImbalance: "কোনো উল্লেখযোগ্য অসন্তুলন লক্ষ্য কৰা হোৱা নাই",
  gradePravara: "প্ৰৱৰ (উচ্চ)",
  gradeMadhyama: "মধ্যম (মধ্যম)",
  gradeAvara: "অৱৰ (নিম্ন)",
  satmyaSama: "সম সাত্ম্য — সন্তুলিত, ভালদৰে খাপ খুৱাই লোৱা",
  satmyaVishama: "বিষম সাত্ম্য — অনিয়মিত, দুৰ্বল খাপ খোৱা",
  satmyaEkaRasa: "একৰস সাত্ম্য — এটা প্ৰধান সোৱাদৰ অভ্যাস",
  vayaBala: "বাল — শৈশৱ (প্ৰায় ১৬ বছৰলৈকে)",
  vayaMadhyama: "মধ্যম / যুৱা — প্ৰাপ্তবয়স্ক (১৬–৭০ বছৰ)",
  vayaVriddha: "বৃদ্ধ — বৃদ্ধাৱস্থা (৭০+ বছৰ)",
  dashavidhaReviewTitle: "দশবিধ পৰীক্ষা",
};

export const CLINICAL_INTAKE_COPY: Record<string, ClinicalIntakeText> = {
  en,
  hi,
  bn,
  ta,
  te,
  mr,
  gu,
  kn,
  ml,
  pa,
  or,
  as,
};
